### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  id: NoStartupFormException
  children:
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: NoStartupFormException
  nameWithType: NoStartupFormException
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  type: Class
  summary: "通过 Visual Basic 应用程序模型引发此异常时<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>未设置属性。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm*>"
  remarks: "Visual Basic 应用程序模型时，需要应用程序设置<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>属性在运行前的<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>方法。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> 如果未设置的属性，Visual Basic 应用程序模型将引发此异常。 有关详细信息，请参阅[扩展 Visual Basic 应用程序模型](~/add/includes/ajax-current-ext-md.md)。      1> [!NOTE]&1;> 了解如何使用设置启动窗体**项目设计器**，请参阅[应用程序页，项目设计器 (Visual Basic 中)](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]

      public class NoStartupFormException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  id: '#ctor'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新实例<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;></xref>类。"
  remarks: "Visual Basic 应用程序模型时，需要应用程序设置<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A>属性在运行前的<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A>方法。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun%2A> </xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.MainForm%2A> 如果未设置的属性，Visual Basic 应用程序模型将引发此异常。 有关详细信息，请参阅[扩展 Visual Basic 应用程序模型](~/add/includes/ajax-current-ext-md.md)。       下表显示<xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>.</xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>实例的初始属性的值      |||  |-|-|  |属性 |值 |  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中)。 |  |<xref:System.Exception.Message%2A>|本地化的错误消息字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException ();
    parameters: []
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新实例<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;></xref>与指定的错误消息的类。"
  remarks: "内容`message`参数旨在为人所理解。 此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。       <xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException>继承自<xref:System.Exception>.</xref:System.Exception></xref:Microsoft.VisualBasic.ApplicationServices.NoStartupFormException> 此构造函数设置的属性<xref:System.Exception>对象下表中所示。</xref:System.Exception>      |||  |-|-|  |属性 |值 |  |<xref:System.Exception.InnerException%2A>|空引用 (`Nothing`在 Visual Basic 中) |  |<xref:System.Exception.Message%2A>|`message`字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述错误的消息。"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新实例<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;></xref>用序列化数据的类。"
  remarks: "在反序列化，以便重建通过流传输的异常对象过程中调用此构造函数。"
  syntax:
    content: protected NoStartupFormException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref>保存关于所引发异常的序列化的对象数据的对象。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>包含有关源或目标的上下文信息的对象。</xref:System.Runtime.Serialization.StreamingContext>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  langs:
  - csharp
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "初始化的新实例<xref href=&quot;Microsoft.VisualBasic.ApplicationServices.NoStartupFormException&quot;></xref>使用指定的错误消息和对导致此异常的内部异常的引用的类。"
  remarks: "内容`message`参数旨在为人所理解。 此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。       前一个异常的直接结果应包含中的前一个异常的引用引发的异常，<xref:System.Exception.InnerException%2A>属性。</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>属性返回的相同值，如果传递到构造函数中，则为空引用<xref:System.Exception.InnerException%2A>属性不会提供给构造函数的内部异常值。</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       下表显示<xref:System.ApplicationException>.</xref:System.ApplicationException>实例的初始属性的值      |||  |-|-|  |属性 |值 |  |<xref:System.Exception.InnerException%2A>|`inner`引用。 |  |<xref:System.Exception.Message%2A>|`message`字符串。 |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public NoStartupFormException (string message, Exception inner);
    parameters:
    - id: message
      type: System.String
      description: "A<xref:System.String>对错误进行描述的对象。</xref:System.String>"
    - id: inner
      type: System.Exception
      description: "<xref:System.Exception>导致当前异常的对象。</xref:System.Exception> 如果<xref:System.Exception.InnerException*>参数不是 null 引用 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref>在 Visual Basic 中)，处理内部异常的 catch 块中引发当前异常。</xref:System.Exception.InnerException*>"
  overload: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException()
  nameWithType: NoStartupFormException.NoStartupFormException()
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException()
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String)
  nameWithType: NoStartupFormException.NoStartupFormException(String)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(SerializationInfo,StreamingContext)
  nameWithType: NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor(System.String,System.Exception)
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException(String,Exception)
  nameWithType: NoStartupFormException.NoStartupFormException(String,Exception)
  fullName: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.NoStartupFormException(String,Exception)
- uid: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.NoStartupFormException
  isExternal: false
  name: NoStartupFormException
  nameWithType: NoStartupFormException.NoStartupFormException
