### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  id: ShutdownEventHandler
  langs:
  - csharp
  name: ShutdownEventHandler
  nameWithType: ShutdownEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.ShutdownEventHandler
  type: Delegate
  summary: "表示将处理的方法<xref uid=&quot;langword_csharp_My.Application.Shutdown&quot; name=&quot;My.Application.Shutdown&quot; href=&quot;&quot;></xref>事件。"
  remarks: "在 Visual Basic 中，你不需要显式使用此委托。 有关详细信息，请参阅<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown>。</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown>"
  example:
  - "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.Shutdown?displayProperty=fullName>  \n  \n [Overview of the Visual Basic Application Model](~/add/includes/ajax-current-ext-md.md)"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void ShutdownEventHandler(object sender, EventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
