### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.InternalConfigEventArgs
  id: InternalConfigEventArgs
  children:
  - System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  - System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  langs:
  - csharp
  name: InternalConfigEventArgs
  nameWithType: InternalConfigEventArgs
  fullName: System.Configuration.Internal.InternalConfigEventArgs
  type: Class
  summary: "定义一个类，用于指定配置事件的事件自变量的.NET Framework 基础结构。"
  syntax:
    content: 'public sealed class InternalConfigEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Internal.InternalConfigEventArgs
  langs:
  - csharp
  name: InternalConfigEventArgs(String)
  nameWithType: InternalConfigEventArgs.InternalConfigEventArgs(String)
  fullName: System.Configuration.Internal.InternalConfigEventArgs.InternalConfigEventArgs(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "初始化的新实例<xref href=&quot;System.Configuration.Internal.InternalConfigEventArgs&quot;></xref>类。"
  syntax:
    content: public InternalConfigEventArgs (string configPath);
    parameters:
    - id: configPath
      type: System.String
      description: "配置路径。"
  overload: System.Configuration.Internal.InternalConfigEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  id: ConfigPath
  parent: System.Configuration.Internal.InternalConfigEventArgs
  langs:
  - csharp
  name: ConfigPath
  nameWithType: InternalConfigEventArgs.ConfigPath
  fullName: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "获取或设置与相关的配置路径<xref href=&quot;System.Configuration.Internal.InternalConfigEventArgs&quot;></xref>对象。"
  syntax:
    content: public string ConfigPath { get; set; }
    return:
      type: System.String
      description: "指定配置路径的字符串值。"
  overload: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Configuration.Internal.InternalConfigEventArgs.#ctor(System.String)
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: InternalConfigEventArgs(String)
  nameWithType: InternalConfigEventArgs.InternalConfigEventArgs(String)
  fullName: System.Configuration.Internal.InternalConfigEventArgs.InternalConfigEventArgs(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: ConfigPath
  nameWithType: InternalConfigEventArgs.ConfigPath
  fullName: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath
- uid: System.Configuration.Internal.InternalConfigEventArgs.#ctor*
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: InternalConfigEventArgs
  nameWithType: InternalConfigEventArgs.InternalConfigEventArgs
- uid: System.Configuration.Internal.InternalConfigEventArgs.ConfigPath*
  parent: System.Configuration.Internal.InternalConfigEventArgs
  isExternal: false
  name: ConfigPath
  nameWithType: InternalConfigEventArgs.ConfigPath
