### YamlMime:ManagedReference
items:
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection
  id: XmlSerializerSection
  children:
  - System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  - System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  - System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  - System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  - System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  langs:
  - csharp
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection
  type: Class
  summary: "处理用于配置 XML 序列化的 XML 元素。"
  remarks: "此类用于处理[ \\&lt; xmlSerializer\\&gt;元素](../Topic/%3CxmlSerializer%3E%20Element.md)。"
  syntax:
    content: 'public sealed class XmlSerializerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  id: '#ctor'
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.XmlSerializerSection()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Xml.Serialization.Configuration.XmlSerializerSection&quot;></xref>类。"
  syntax:
    content: public XmlSerializerSection ();
    parameters: []
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  id: CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "获取或设置一个值，确定是否进度包含额外检查<xref:System.Xml.Serialization.XmlSerializer>完成。</xref:System.Xml.Serialization.XmlSerializer>"
  remarks: "不要使用此方法。 与此相反，设置`checkDeserializerAdvances`属性[ \\&lt; xmlSerializer\\&gt;元素](../Topic/%3CxmlSerializer%3E%20Element.md)。"
  syntax:
    content: public bool CheckDeserializeAdvances { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果在进行检查;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  id: Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  id: TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "返回指定为创建的临时文件的位置。"
  syntax:
    content: public string TempFilesLocation { get; set; }
    return:
      type: System.String
      description: "已指定为创建的临时文件的位置。"
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  id: UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  langs:
  - csharp
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Serialization.Configuration
  summary: "获取或设置一个值，该值指示指定的对象是使用旧的序列化程序生成。"
  syntax:
    content: public bool UseLegacySerializerGeneration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果该对象使用旧的序列化程序生成;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection()
  nameWithType: XmlSerializerSection.XmlSerializerSection()
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.XmlSerializerSection()
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
  fullName: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.#ctor*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: XmlSerializerSection
  nameWithType: XmlSerializerSection.XmlSerializerSection
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.CheckDeserializeAdvances*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: CheckDeserializeAdvances
  nameWithType: XmlSerializerSection.CheckDeserializeAdvances
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.Properties*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: Properties
  nameWithType: XmlSerializerSection.Properties
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.TempFilesLocation*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: TempFilesLocation
  nameWithType: XmlSerializerSection.TempFilesLocation
- uid: System.Xml.Serialization.Configuration.XmlSerializerSection.UseLegacySerializerGeneration*
  parent: System.Xml.Serialization.Configuration.XmlSerializerSection
  isExternal: false
  name: UseLegacySerializerGeneration
  nameWithType: XmlSerializerSection.UseLegacySerializerGeneration
