### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings
  id: UdpRetransmissionSettings
  children:
  - System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor
  - System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32)
  - System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32,System.TimeSpan,System.TimeSpan,System.TimeSpan)
  - System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound
  - System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound
  - System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission
  - System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount
  - System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount
  - System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound
  - System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound
  - System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission
  langs:
  - csharp
  name: UdpRetransmissionSettings
  nameWithType: UdpRetransmissionSettings
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings
  type: Class
  summary: "指定 UDP 传输设置。"
  syntax:
    content: public sealed class UdpRetransmissionSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: UdpRetransmissionSettings()
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Channels.UdpRetransmissionSettings&quot;></xref>类。"
  syntax:
    content: public UdpRetransmissionSettings ();
    parameters: []
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32)
  id: '#ctor(System.Int32,System.Int32)'
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: UdpRetransmissionSettings(Int32,Int32)
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32)
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32)
  type: Constructor
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Channels.UdpRetransmissionSettings&quot;></xref>类指定的最大单播重新传输多播的最大重新传输计数和计数。"
  syntax:
    content: public UdpRetransmissionSettings (int maxUnicastRetransmitCount, int maxMulticastRetransmitCount);
    parameters:
    - id: maxUnicastRetransmitCount
      type: System.Int32
      description: "最大单播重新传输计数。"
    - id: maxMulticastRetransmitCount
      type: System.Int32
      description: "最大多播重新传输计数。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32,System.TimeSpan,System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.Int32,System.Int32,System.TimeSpan,System.TimeSpan,System.TimeSpan)'
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Channels.UdpRetransmissionSettings&quot;></xref>类指定的最大单播重新传输计数和最大的多路广播重新传输计数、 延迟下限、 延迟上限和每次重新传输的最大延迟。"
  syntax:
    content: public UdpRetransmissionSettings (int maxUnicastRetransmitCount, int maxMulticastRetransmitCount, TimeSpan delayLowerBound, TimeSpan delayUpperBound, TimeSpan maxDelayPerRetransmission);
    parameters:
    - id: maxUnicastRetransmitCount
      type: System.Int32
      description: "最大单播重新传输计数。"
    - id: maxMulticastRetransmitCount
      type: System.Int32
      description: "最大多播重新传输计数。"
    - id: delayLowerBound
      type: System.TimeSpan
      description: "界限低于延迟时间。"
    - id: delayUpperBound
      type: System.TimeSpan
      description: "延迟上限。"
    - id: maxDelayPerRetransmission
      type: System.TimeSpan
      description: "每次重新传输最大延迟。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound
  id: DelayLowerBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettings.DelayLowerBound
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "获取或设置的下限的延迟时间重新传输设置。"
  syntax:
    content: public TimeSpan DelayLowerBound { get; set; }
    return:
      type: System.TimeSpan
      description: "重新传输设置下限的延迟。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound
  id: DelayUpperBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettings.DelayUpperBound
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "获取或设置的重新传输设置上限的延迟。"
  syntax:
    content: public TimeSpan DelayUpperBound { get; set; }
    return:
      type: System.TimeSpan
      description: "重新传输设置上限的延迟。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission
  id: MaxDelayPerRetransmission
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettings.MaxDelayPerRetransmission
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "获取或设置每次重新传输设置的重新传输的最大延迟。"
  syntax:
    content: public TimeSpan MaxDelayPerRetransmission { get; set; }
    return:
      type: System.TimeSpan
      description: "每次重新传输设置的重新传输最大延迟。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "获取或设置最大的多路广播重新传输计数。"
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "最大的多路广播重新传输计数中。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "获取或设置最大单播重新传输计数。"
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "最大单播重新传输计数。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound
  id: ShouldSerializeDelayLowerBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: ShouldSerializeDelayLowerBound()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayLowerBound()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound()
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "指示 UDP 传输设置是否应序列化的下限延迟。"
  syntax:
    content: public bool ShouldSerializeDelayLowerBound ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>如果 UDP 传输设置应序列化的下限延迟;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound
  id: ShouldSerializeDelayUpperBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: ShouldSerializeDelayUpperBound()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayUpperBound()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound()
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "指示 UDP 传输设置是否应序列化的上限延迟。"
  syntax:
    content: public bool ShouldSerializeDelayUpperBound ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>如果 UDP 传输设置应序列化的上限延迟;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission
  id: ShouldSerializeMaxDelayPerRetransmission
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  langs:
  - csharp
  name: ShouldSerializeMaxDelayPerRetransmission()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission()
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Channels
  summary: "指示 UDP 传输设置是否应序列化每次重新传输的最大延迟。"
  syntax:
    content: public bool ShouldSerializeMaxDelayPerRetransmission ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;></xref>如果 UDP 传输设置应序列化每次重新传输; 的最大延迟否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: UdpRetransmissionSettings()
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings()
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32)
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: UdpRetransmissionSettings(Int32,Int32)
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32)
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor(System.Int32,System.Int32,System.TimeSpan,System.TimeSpan,System.TimeSpan)
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.UdpRetransmissionSettings(Int32,Int32,TimeSpan,TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettings.DelayLowerBound
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettings.DelayUpperBound
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettings.MaxDelayPerRetransmission
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeDelayLowerBound()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayLowerBound()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeDelayUpperBound()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayUpperBound()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound()
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeMaxDelayPerRetransmission()
  nameWithType: UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission()
  fullName: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission()
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.#ctor*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: UdpRetransmissionSettings
  nameWithType: UdpRetransmissionSettings.UdpRetransmissionSettings
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayLowerBound*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: DelayLowerBound
  nameWithType: UdpRetransmissionSettings.DelayLowerBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.DelayUpperBound*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: DelayUpperBound
  nameWithType: UdpRetransmissionSettings.DelayUpperBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxDelayPerRetransmission*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettings.MaxDelayPerRetransmission
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpRetransmissionSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayLowerBound*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeDelayLowerBound
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayLowerBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeDelayUpperBound*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeDelayUpperBound
  nameWithType: UdpRetransmissionSettings.ShouldSerializeDelayUpperBound
- uid: System.ServiceModel.Channels.UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission*
  parent: System.ServiceModel.Channels.UdpRetransmissionSettings
  isExternal: false
  name: ShouldSerializeMaxDelayPerRetransmission
  nameWithType: UdpRetransmissionSettings.ShouldSerializeMaxDelayPerRetransmission
