### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthenticationSection
  id: AuthenticationSection
  children:
  - System.Web.Configuration.AuthenticationSection.#ctor
  - System.Web.Configuration.AuthenticationSection.Forms
  - System.Web.Configuration.AuthenticationSection.Mode
  - System.Web.Configuration.AuthenticationSection.Passport
  - System.Web.Configuration.AuthenticationSection.Properties
  - System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: AuthenticationSection
  nameWithType: AuthenticationSection
  fullName: System.Web.Configuration.AuthenticationSection
  type: Class
  summary: "配置 Web 应用程序的身份验证。 此类不能被继承。"
  remarks: "AuthenticationSection 类使您能够以编程方式访问和修改`authentication`配置文件节。      1> [!NOTE]&1;> AuthenticationSection 可将信息写入到根据定义的部分属性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值为<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>的限制的配置文件的相关部分 在层次结构不允许层次结构中的配置文件中写入任何尝试会对由分析器生成的错误消息中。 但是，此类可用于读取层次结构中的任何级别的配置信息。 有关安全性和可伸缩性，建议你使用外部存储库，例如数据库、 保留用户的凭据。"
  example:
  - "This section provides two code examples. The first demonstrates how to specify values declaratively for several attributes of the `authentication` section, which can also be accessed as members of the AuthenticationSection class. The second demonstrates how to use the AuthenticationSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `authentication` section.  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security, it is recommended the use of an external database to store the users' credentials. For more information about building secure ASP.NET applications search the Microsoft MSDN Web site (http://msdn.microsoft.com) for \"Securing Your ASP.NET Application\", and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication\".  \n  \n```  \n<authentication mode=\"Forms\">  \n  <forms name=\"MyAppCookieName\" loginUrl=\"login.aspx\">  \n    <credentials passwordFormat=\"SHA1\">  \n      <user name=\"Kim\"  \n         password=\"07B7F3EE06F278DB966BE960E7CBBD103DF30CA6\"/>  \n      <user name=\"John\"  \n         password=\"BA56E5E0366D003E98EA1C7F04ABF8FCB3753889\"/>  \n    </credentials>  \n  </forms>  \n</authentication>  \n```  \n  \n The following code example demonstrates how to use the AuthenticationSection class.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#1](~/add/codesnippet/csharp/t-system.web.configurati_68_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_68_1.vb)]"
  syntax:
    content: 'public sealed class AuthenticationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: AuthenticationSection()
  nameWithType: AuthenticationSection.AuthenticationSection()
  fullName: System.Web.Configuration.AuthenticationSection.AuthenticationSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.AuthenticationSection&quot;></xref>类。"
  remarks: "AuthenticationSection 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.AuthenticationSection>类通过<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.AuthenticationSection>"
  example:
  - "The following code example shows how to obtain a <xref:System.Web.Configuration.AuthenticationSection> object.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#2](~/add/codesnippet/csharp/m-system.web.configurati_46_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#2](~/add/codesnippet/visualbasic/m-system.web.configurati_46_1.vb)]"
  syntax:
    content: public AuthenticationSection ();
    parameters: []
  overload: System.Web.Configuration.AuthenticationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.Forms
  id: Forms
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Forms
  nameWithType: AuthenticationSection.Forms
  fullName: System.Web.Configuration.AuthenticationSection.Forms
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取窗体元素属性。"
  remarks: ''
  example:
  - "The following code example shows how to use the Forms element property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#5](~/add/codesnippet/csharp/p-system.web.configurati_29_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#5](~/add/codesnippet/visualbasic/p-system.web.configurati_29_1.vb)]"
  syntax:
    content: public System.Web.Configuration.FormsAuthenticationConfiguration Forms { get; }
    return:
      type: System.Web.Configuration.FormsAuthenticationConfiguration
      description: "一个包含在基于窗体的身份验证过程中使用的信息的窗体元素属性。"
  overload: System.Web.Configuration.AuthenticationSection.Forms*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.Mode
  id: Mode
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Mode
  nameWithType: AuthenticationSection.Mode
  fullName: System.Web.Configuration.AuthenticationSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置身份验证模式。"
  remarks: ''
  example:
  - "The following code example shows how to use the Mode property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/csharp/p-system.web.configurati_400_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_400_1.vb)]"
  syntax:
    content: public System.Web.Configuration.AuthenticationMode Mode { get; set; }
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "之一<xref href=&quot;System.Web.Configuration.AuthenticationMode&quot;></xref>值。"
  overload: System.Web.Configuration.AuthenticationSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.Passport
  id: Passport
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Passport
  nameWithType: AuthenticationSection.Passport
  fullName: System.Web.Configuration.AuthenticationSection.Passport
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取 Passport 元素属性。"
  remarks: ''
  example:
  - "The following code example shows how to use the Passport element property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#3](~/add/codesnippet/csharp/p-system.web.configurati_165_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_165_1.vb)]"
  syntax:
    content: public System.Web.Configuration.PassportAuthentication Passport { get; }
    return:
      type: System.Web.Configuration.PassportAuthentication
      description: "一个包含在基于 passport 的身份验证过程中使用的信息的 Passport 元素属性。"
  overload: System.Web.Configuration.AuthenticationSection.Passport*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.Properties
  id: Properties
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Properties
  nameWithType: AuthenticationSection.Properties
  fullName: System.Web.Configuration.AuthenticationSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.AuthenticationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.AuthenticationSection
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: AuthenticationSection.Reset(ConfigurationElement)
  fullName: System.Web.Configuration.AuthenticationSection.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "要添加。"
  overload: System.Web.Configuration.AuthenticationSection.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.AuthenticationSection.#ctor
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: AuthenticationSection()
  nameWithType: AuthenticationSection.AuthenticationSection()
  fullName: System.Web.Configuration.AuthenticationSection.AuthenticationSection()
- uid: System.Web.Configuration.AuthenticationSection.Forms
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Forms
  nameWithType: AuthenticationSection.Forms
  fullName: System.Web.Configuration.AuthenticationSection.Forms
- uid: System.Web.Configuration.FormsAuthenticationConfiguration
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthenticationConfiguration
  nameWithType: FormsAuthenticationConfiguration
  fullName: System.Web.Configuration.FormsAuthenticationConfiguration
- uid: System.Web.Configuration.AuthenticationSection.Mode
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Mode
  nameWithType: AuthenticationSection.Mode
  fullName: System.Web.Configuration.AuthenticationSection.Mode
- uid: System.Web.Configuration.AuthenticationMode
  parent: System.Web.Configuration
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: System.Web.Configuration.AuthenticationMode
- uid: System.Web.Configuration.AuthenticationSection.Passport
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Passport
  nameWithType: AuthenticationSection.Passport
  fullName: System.Web.Configuration.AuthenticationSection.Passport
- uid: System.Web.Configuration.PassportAuthentication
  parent: System.Web.Configuration
  isExternal: false
  name: PassportAuthentication
  nameWithType: PassportAuthentication
  fullName: System.Web.Configuration.PassportAuthentication
- uid: System.Web.Configuration.AuthenticationSection.Properties
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Properties
  nameWithType: AuthenticationSection.Properties
  fullName: System.Web.Configuration.AuthenticationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AuthenticationSection.Reset(System.Configuration.ConfigurationElement)
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: AuthenticationSection.Reset(ConfigurationElement)
  fullName: System.Web.Configuration.AuthenticationSection.Reset(ConfigurationElement)
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.AuthenticationSection.#ctor*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: AuthenticationSection
  nameWithType: AuthenticationSection.AuthenticationSection
- uid: System.Web.Configuration.AuthenticationSection.Forms*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Forms
  nameWithType: AuthenticationSection.Forms
- uid: System.Web.Configuration.AuthenticationSection.Mode*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Mode
  nameWithType: AuthenticationSection.Mode
- uid: System.Web.Configuration.AuthenticationSection.Passport*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Passport
  nameWithType: AuthenticationSection.Passport
- uid: System.Web.Configuration.AuthenticationSection.Properties*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Properties
  nameWithType: AuthenticationSection.Properties
- uid: System.Web.Configuration.AuthenticationSection.Reset*
  parent: System.Web.Configuration.AuthenticationSection
  isExternal: false
  name: Reset
  nameWithType: AuthenticationSection.Reset
