### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsPersonalization
  id: WebPartsPersonalization
  children:
  - System.Web.Configuration.WebPartsPersonalization.#ctor
  - System.Web.Configuration.WebPartsPersonalization.Authorization
  - System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  - System.Web.Configuration.WebPartsPersonalization.Properties
  - System.Web.Configuration.WebPartsPersonalization.Providers
  langs:
  - csharp
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization
  fullName: System.Web.Configuration.WebPartsPersonalization
  type: Class
  summary: "允许您指定个性化设置提供程序并设置个性化授权。 此类不能被继承。"
  remarks: "WebPartsPersonalization 提供配置支持的 Web 部件，如个性化设置提供程序和个性化设置授权的个性化设置选项。"
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `webParts` section, which can also be accessed as members of the WebPartsPersonalization class.  \n  \n The following configuration file example shows how to specify values declaratively for the `webParts` section.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization  \n      defaultProvider=\"AspNetSqlPersonalizationProvider\">  \n        <!—- Providers may only be defined at the   \n            application level -->  \n      <providers>  \n         <add name=\"AspNetSqlPersonalizationProvider\"  \ntype=\"System.Web.UI.WebControls.WebParts.SqlPersonalizationProvider\"  \n            connectionStringName=\"LocalSqlServer\"  \n            applicationName=\"/\" />        \n      </providers>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"*\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n  </webParts>   \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the WebPartsPersonalization class.  \n  \n This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/csharp/t-system.web.configurati_85_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#3](~/add/codesnippet/visualbasic/t-system.web.configurati_85_1.vb)]"
  syntax:
    content: 'public sealed class WebPartsPersonalization : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: WebPartsPersonalization()
  nameWithType: WebPartsPersonalization.WebPartsPersonalization()
  fullName: System.Web.Configuration.WebPartsPersonalization.WebPartsPersonalization()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.WebPartsPersonalization&quot;></xref>类使用默认设置。"
  remarks: "此构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 此类的实例是可从<xref:System.Web.Configuration.WebPartsSection.Personalization%2A>属性。</xref:System.Web.Configuration.WebPartsSection.Personalization%2A>"
  syntax:
    content: public WebPartsPersonalization ();
    parameters: []
  overload: System.Web.Configuration.WebPartsPersonalization.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization
  id: Authorization
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
  fullName: System.Web.Configuration.WebPartsPersonalization.Authorization
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取<xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;></xref>对象，其中包含当前 Web 应用程序的 Web 部件个性化授权。"
  remarks: "必须有至少一个有效的谓词关联与每个<xref:System.Web.Configuration.AuthorizationRule>集合中的对象。</xref:System.Web.Configuration.AuthorizationRule>"
  example:
  - "The following code example shows how to use the Authorization property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#15](~/add/codesnippet/csharp/p-system.web.configurati_18_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#15](~/add/codesnippet/visualbasic/p-system.web.configurati_18_1.vb)]"
  syntax:
    content: public System.Web.Configuration.WebPartsPersonalizationAuthorization Authorization { get; }
    return:
      type: System.Web.Configuration.WebPartsPersonalizationAuthorization
      description: "<xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;> </xref>对象，其中包含当前 Web 应用程序的 Web 部件个性化授权。"
  overload: System.Web.Configuration.WebPartsPersonalization.Authorization*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
  fullName: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置默认 Web 部件个性化设置提供程序的名称。"
  remarks: "<xref:System.Web.Configuration.WebPartsPersonalization.Providers%2A>属性包含 Web 部件个性化设置提供程序当前的 Web 应用程序。</xref:System.Web.Configuration.WebPartsPersonalization.Providers%2A>"
  example:
  - "The following code example shows how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#13](~/add/codesnippet/csharp/p-system.web.configurati_333_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#13](~/add/codesnippet/visualbasic/p-system.web.configurati_333_1.vb)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "默认 Web 部件个性化设置提供程序的名称。"
  overload: System.Web.Configuration.WebPartsPersonalization.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalization.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalization.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.WebPartsPersonalization.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalization.Providers
  id: Providers
  parent: System.Web.Configuration.WebPartsPersonalization
  langs:
  - csharp
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
  fullName: System.Web.Configuration.WebPartsPersonalization.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取<xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;></xref>集合，其中包含当前 Web 应用程序的 Web 部件个性化设置提供程序。"
  remarks: "仅可以在 Web 应用程序级别 （在 Web.config 文件中） 定义 web 部件个性化设置提供程序。"
  example:
  - "The following code example shows how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.WebPartsSection> class.  \n  \n [!code-cs[System.Web.Configuration.WebPartsSection#14](~/add/codesnippet/csharp/p-system.web.configurati_148_1.cs)]\n [!code-vb[System.Web.Configuration.WebPartsSection#14](~/add/codesnippet/visualbasic/p-system.web.configurati_148_1.vb)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "A <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref>集合，其中包含当前 Web 应用程序的 Web 部件个性化设置提供程序。"
  overload: System.Web.Configuration.WebPartsPersonalization.Providers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: WebPartsPersonalization()
  nameWithType: WebPartsPersonalization.WebPartsPersonalization()
  fullName: System.Web.Configuration.WebPartsPersonalization.WebPartsPersonalization()
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
  fullName: System.Web.Configuration.WebPartsPersonalization.Authorization
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization
  parent: System.Web.Configuration
  isExternal: false
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
  fullName: System.Web.Configuration.WebPartsPersonalization.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.WebPartsPersonalization.Properties
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalization.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsPersonalization.Providers
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
  fullName: System.Web.Configuration.WebPartsPersonalization.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.WebPartsPersonalization.#ctor*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: WebPartsPersonalization
  nameWithType: WebPartsPersonalization.WebPartsPersonalization
- uid: System.Web.Configuration.WebPartsPersonalization.Authorization*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Authorization
  nameWithType: WebPartsPersonalization.Authorization
- uid: System.Web.Configuration.WebPartsPersonalization.DefaultProvider*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: DefaultProvider
  nameWithType: WebPartsPersonalization.DefaultProvider
- uid: System.Web.Configuration.WebPartsPersonalization.Properties*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalization.Properties
- uid: System.Web.Configuration.WebPartsPersonalization.Providers*
  parent: System.Web.Configuration.WebPartsPersonalization
  isExternal: false
  name: Providers
  nameWithType: WebPartsPersonalization.Providers
