### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.ApplicationType
  id: ApplicationType
  children:
  - System.IdentityModel.Services.ApplicationType.AspNetWebApplication
  - System.IdentityModel.Services.ApplicationType.WcfServiceApplication
  langs:
  - csharp
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: System.IdentityModel.Services.ApplicationType
  type: Enum
  summary: "指定类型的应用程序。"
  syntax:
    content: public enum ApplicationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.IdentityModel.Services.ApplicationType.AspNetWebApplication
  id: AspNetWebApplication
  parent: System.IdentityModel.Services.ApplicationType
  langs:
  - csharp
  name: AspNetWebApplication
  nameWithType: ApplicationType.AspNetWebApplication
  fullName: System.IdentityModel.Services.ApplicationType.AspNetWebApplication
  type: Field
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "ASP.NET Web 应用程序。"
  syntax:
    content: AspNetWebApplication
    return:
      type: System.IdentityModel.Services.ApplicationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.ApplicationType.WcfServiceApplication
  id: WcfServiceApplication
  parent: System.IdentityModel.Services.ApplicationType
  langs:
  - csharp
  name: WcfServiceApplication
  nameWithType: ApplicationType.WcfServiceApplication
  fullName: System.IdentityModel.Services.ApplicationType.WcfServiceApplication
  type: Field
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "A[!INCLUDE[vsindigo](~/add/includes/vsindigo-md.md)]应用程序。"
  syntax:
    content: WcfServiceApplication
    return:
      type: System.IdentityModel.Services.ApplicationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.IdentityModel.Services.ApplicationType.AspNetWebApplication
  parent: System.IdentityModel.Services.ApplicationType
  isExternal: false
  name: AspNetWebApplication
  nameWithType: ApplicationType.AspNetWebApplication
  fullName: System.IdentityModel.Services.ApplicationType.AspNetWebApplication
- uid: System.IdentityModel.Services.ApplicationType
  parent: System.IdentityModel.Services
  isExternal: false
  name: ApplicationType
  nameWithType: ApplicationType
  fullName: System.IdentityModel.Services.ApplicationType
- uid: System.IdentityModel.Services.ApplicationType.WcfServiceApplication
  parent: System.IdentityModel.Services.ApplicationType
  isExternal: false
  name: WcfServiceApplication
  nameWithType: ApplicationType.WcfServiceApplication
  fullName: System.IdentityModel.Services.ApplicationType.WcfServiceApplication
