### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  id: ServiceSettingsResponseInfo
  children:
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  langs:
  - csharp
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  type: Class
  summary: "包含对等请求对等解析程序服务的设置时返回的信息。"
  remarks: "此类的实例主要用于从解析程序服务到该服务的网络客户端传递服务设置响应信息。"
  syntax:
    content: >-
      [System.ServiceModel.MessageContract(IsWrapped=false)]

      public class ServiceSettingsResponseInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "初始化的新默认实例<xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;></xref>类。"
  remarks: "默认值`control`设置为 true。"
  syntax:
    content: public ServiceSettingsResponseInfo ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;></xref>类提供的引用策略值。"
  syntax:
    content: public ServiceSettingsResponseInfo (bool control);
    parameters:
    - id: control
      type: System.Boolean
      description: "<xref:System.Boolean>指示解析程序服务是否传递引用。</xref:System.Boolean>"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  id: ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "获取或设置是否传递引用解析程序服务。"
  syntax:
    content: public bool ControlMeshShape { get; set; }
    return:
      type: System.Boolean
      description: "如果传递来自参与网格的对等节点的引用; 则为 true否则，false 它们将被忽略。"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  id: HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "指示是否包含此类型的序列化的实例的消息的正文格式是否正确。"
  syntax:
    content: public bool HasBody ();
    parameters: []
    return:
      type: System.Boolean
      description: "如果发件人; 正确格式的服务设置响应信息的正文为，true如果不是，false。"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody
  nameWithType: ServiceSettingsResponseInfo.HasBody
