### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement
  id: ServicePrincipalNameElement
  children:
  - System.ServiceModel.Configuration.ServicePrincipalNameElement.#ctor
  - System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties
  - System.ServiceModel.Configuration.ServicePrincipalNameElement.Value
  langs:
  - csharp
  name: ServicePrincipalNameElement
  nameWithType: ServicePrincipalNameElement
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement
  type: Class
  summary: "表示一个配置元素，指定客户端用于唯一标识服务的实例的主体名称。 此类不能被继承。"
  remarks: "有关服务主体名称的详细信息，请参阅[服务主体名称](http://go.microsoft.com/fwlink/?LinkId=96656)。"
  syntax:
    content: 'public sealed class ServicePrincipalNameElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  langs:
  - csharp
  name: ServicePrincipalNameElement()
  nameWithType: ServicePrincipalNameElement.ServicePrincipalNameElement()
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.ServicePrincipalNameElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.ServicePrincipalNameElement&quot;></xref>类。"
  syntax:
    content: public ServicePrincipalNameElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ServicePrincipalNameElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  langs:
  - csharp
  name: Properties
  nameWithType: ServicePrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value
  id: Value
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  langs:
  - csharp
  name: Value
  nameWithType: ServicePrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置此配置元素包装的服务主体名称。"
  syntax:
    content: public string Value { get; set; }
    return:
      type: System.String
      description: "此配置元素包装的服务主体名称。"
  overload: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.#ctor
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: ServicePrincipalNameElement()
  nameWithType: ServicePrincipalNameElement.ServicePrincipalNameElement()
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.ServicePrincipalNameElement()
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: ServicePrincipalNameElement.Properties
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: ServicePrincipalNameElement.Value
  fullName: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.#ctor*
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: ServicePrincipalNameElement
  nameWithType: ServicePrincipalNameElement.ServicePrincipalNameElement
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Properties*
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: Properties
  nameWithType: ServicePrincipalNameElement.Properties
- uid: System.ServiceModel.Configuration.ServicePrincipalNameElement.Value*
  parent: System.ServiceModel.Configuration.ServicePrincipalNameElement
  isExternal: false
  name: Value
  nameWithType: ServicePrincipalNameElement.Value
