### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationEventArgs
  id: WorkflowApplicationEventArgs
  children:
  - System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  - System.Activities.WorkflowApplicationEventArgs.InstanceId
  langs:
  - csharp
  name: WorkflowApplicationEventArgs
  nameWithType: WorkflowApplicationEventArgs
  fullName: System.Activities.WorkflowApplicationEventArgs
  type: Class
  summary: "与关联的事件的基类<xref href=&quot;System.Activities.WorkflowApplication&quot;> </xref> 。"
  remarks: "中还使用 WorkflowApplicationEventArgs<xref:System.Activities.WorkflowApplication.Unloaded%2A>处理程序<xref:System.Activities.WorkflowApplication>实例。</xref:System.Activities.WorkflowApplication> </xref:System.Activities.WorkflowApplication.Unloaded%2A>"
  example:
  - "The following code example inspects the WorkflowApplicationEventArgs passed into the <xref:System.Activities.WorkflowApplication.Unloaded%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays the <xref:System.Activities.WorkflowApplicationEventArgs.InstanceId%2A> of the workflow that was unloaded.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#3](~/add/codesnippet/csharp/t-system.activities.work_2_1.cs)]"
  syntax:
    content: 'public class WorkflowApplicationEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  id: GetInstanceExtensions``1
  parent: System.Activities.WorkflowApplicationEventArgs
  langs:
  - csharp
  name: GetInstanceExtensions()
  nameWithType: WorkflowApplicationEventArgs.GetInstanceExtensions()
  fullName: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions()
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  syntax:
    content: 'public System.Collections.Generic.IEnumerable<T> GetInstanceExtensions<T> () where T : class;'
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{T}
      description: "要添加。"
  overload: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions<T>*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationEventArgs.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationEventArgs
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationEventArgs.InstanceId
  fullName: System.Activities.WorkflowApplicationEventArgs.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "工作流实例的唯一标识符。"
  remarks: ''
  example:
  - "The following code example inspects the <xref:System.Activities.WorkflowApplicationEventArgs> passed into the <xref:System.Activities.WorkflowApplication.Unloaded%2A> handler of a <xref:System.Activities.WorkflowApplication> instance and displays the InstanceId of the workflow that was unloaded.  \n  \n [!code-cs[CFX_WorkflowApplicationExample#3](~/add/codesnippet/csharp/p-system.activities.work_4_1.cs)]"
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: "唯一的标识符。"
  overload: System.Activities.WorkflowApplicationEventArgs.InstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions``1
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: GetInstanceExtensions()
  nameWithType: WorkflowApplicationEventArgs.GetInstanceExtensions()
  fullName: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions()
- uid: System.Collections.Generic.IEnumerable{T}
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<T>
  nameWithType: IEnumerable<T>
  fullName: System.Collections.Generic.IEnumerable<T>
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<T>
  - name: <
    nameWithType: <
    fullName: <
  - uid: T
    name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Activities.WorkflowApplicationEventArgs.InstanceId
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationEventArgs.InstanceId
  fullName: System.Activities.WorkflowApplicationEventArgs.InstanceId
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationEventArgs.GetInstanceExtensions<T>*
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: GetInstanceExtensions<T>
  nameWithType: WorkflowApplicationEventArgs.GetInstanceExtensions<T>
- uid: System.Activities.WorkflowApplicationEventArgs.InstanceId*
  parent: System.Activities.WorkflowApplicationEventArgs
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationEventArgs.InstanceId
