### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "定义控件充当用于将 Web 部件连接中的转换器的配置控件而实现的协定。"
  remarks: "Transformer 要求用户对其进行配置时，可以显示配置控件。 配置控件提供用户界面 (UI)，用户可以选择将转换的值。 在连接区域呈现。 <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>方法将返回配置控件。</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       您可以重写<xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>方法如果转换器需要自定义的 UI。</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> 配置控件必须实现 ITransformerConfigurationControl 接口，其中包括<xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>和<xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>事件。</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> 这些事件发生时 transformer 控件已不配置或配置成功，分别。"
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Transformer 配置未完成时发生。"
  remarks: "Web 部件控件实现<xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>transformer 配置未完成，或者是因为用户已取消配置无法执行配置时引发此事件。</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Transformer 配置成功完成时发生。"
  remarks: "Web 部件控件实现<xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>transformer 配置成功完成时引发此事件。</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
