### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  id: IssuedTokenParametersEndpointAddressElement
  children:
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  - System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  langs:
  - csharp
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  type: Class
  summary: "表示一个配置元素，指定颁发安全令牌的终结点。 此类不能被继承。"
  syntax:
    content: 'public sealed class IssuedTokenParametersEndpointAddressElement : System.ServiceModel.Configuration.EndpointAddressElementBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.EndpointAddressElementBase
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Address
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Copy(System.ServiceModel.Configuration.EndpointAddressElementBase)
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Headers
  - System.ServiceModel.Configuration.EndpointAddressElementBase.Identity
  - System.ServiceModel.Configuration.EndpointAddressElementBase.InitializeFrom(System.ServiceModel.EndpointAddress)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: IssuedTokenParametersEndpointAddressElement()
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement&quot;></xref>类。"
  syntax:
    content: public IssuedTokenParametersEndpointAddressElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  id: Binding
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置要使用的绑定类型。"
  remarks: "类型必须具有一个已注册的配置节，才能加以引用。 该类型是按节名而不是绑定的类型名注册的。"
  syntax:
    content: public string Binding { get; set; }
    return:
      type: System.String
      description: "要使用的绑定类型。"
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  id: BindingConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置要实例化终结点时使用的绑定配置的名称。 绑定配置必须在范围内，定义终结点时。"
  remarks: "绑定配置必须在范围内，定义终结点时。"
  syntax:
    content: public string BindingConfiguration { get; set; }
    return:
      type: System.String
      description: "要实例化终结点时使用的绑定配置的名称。"
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.EndpointAddressElementBase
  isExternal: false
  name: System.ServiceModel.Configuration.EndpointAddressElementBase
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: IssuedTokenParametersEndpointAddressElement()
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement()
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
  fullName: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.#ctor*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: IssuedTokenParametersEndpointAddressElement
  nameWithType: IssuedTokenParametersEndpointAddressElement.IssuedTokenParametersEndpointAddressElement
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Binding*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Binding
  nameWithType: IssuedTokenParametersEndpointAddressElement.Binding
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.BindingConfiguration*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: BindingConfiguration
  nameWithType: IssuedTokenParametersEndpointAddressElement.BindingConfiguration
- uid: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement.Properties*
  parent: System.ServiceModel.Configuration.IssuedTokenParametersEndpointAddressElement
  isExternal: false
  name: Properties
  nameWithType: IssuedTokenParametersEndpointAddressElement.Properties
