### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SqlCacheDependencyDatabase
  id: SqlCacheDependencyDatabase
  children:
  - System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  - System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  - System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  - System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  - System.Web.Configuration.SqlCacheDependencyDatabase.Name
  - System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  - System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  langs:
  - csharp
  name: SqlCacheDependencyDatabase
  nameWithType: SqlCacheDependencyDatabase
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase
  type: Class
  summary: "配置 ASP.NET 应用程序的 SQL 缓存依赖关系数据库。 此类不能被继承。"
  remarks: "SqlCacheDependencyDatabase 允许你以编程方式访问和修改`databases`元素`sqlCacheDependency`中的节点`caching`配置节。       SQL 缓存依赖项使缓存的数据与原始的源同步。 配置 ASP.NET 应用程序的缓存与特定 SQL Server 数据库表的实例中存储的项之间的关系之后<xref:System.Web.Caching.SqlCacheDependency>类监视可能发生的更改的表。</xref:System.Web.Caching.SqlCacheDependency>"
  example:
  - "The following code example shows how to obtain the SqlCacheDependencyDatabase object from the configuration file of an existing Web application.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#1](~/add/codesnippet/visualbasic/t-system.web.configurati_17_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#1](~/add/codesnippet/csharp/t-system.web.configurati_17_1.cs)]"
  syntax:
    content: 'public sealed class SqlCacheDependencyDatabase : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: SqlCacheDependencyDatabase(String,String)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>使用传递的参数的类。"
  remarks: ''
  example:
  - "The following example shows how to use this constructor.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#6](~/add/codesnippet/visualbasic/5e38fe68-b87d-487a-9066-_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#6](~/add/codesnippet/csharp/5e38fe68-b87d-487a-9066-_1.cs)]"
  syntax:
    content: public SqlCacheDependencyDatabase (string name, string connectionStringName);
    parameters:
    - id: name
      type: System.String
      description: "一个字符串，指定使用的名称<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>来标识数据库。"
    - id: connectionStringName
      type: System.String
      description: "一个字符串，指定的名称中的连接字符串<xref uid=&quot;langword_csharp_connectionStrings&quot; name=&quot;connectionStrings&quot; href=&quot;&quot;></xref>要用于连接到此数据库的部分。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: SqlCacheDependencyDatabase(String,String,Int32)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>类。"
  remarks: ''
  example:
  - "The following example shows how to use this constructor.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#5](~/add/codesnippet/visualbasic/de5448cc-1e38-425a-ac5d-_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#5](~/add/codesnippet/csharp/de5448cc-1e38-425a-ac5d-_1.cs)]"
  syntax:
    content: public SqlCacheDependencyDatabase (string name, string connectionStringName, int pollTime);
    parameters:
    - id: name
      type: System.String
      description: "一个字符串，指定使用的名称<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>来标识数据库。"
    - id: connectionStringName
      type: System.String
      description: "一个字符串，指定的名称中的连接字符串<xref uid=&quot;langword_csharp_connectionStrings&quot; name=&quot;connectionStrings&quot; href=&quot;&quot;></xref>要用于连接到此数据库的部分。"
    - id: pollTime
      type: System.Int32
      description: "数据库轮询时间，以毫秒为单位。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  id: ConnectionStringName
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置数据库的连接名称。"
  remarks: "ConnectionStringName 属性允许您以编程方式访问和修改`connectionName`属性`add`元素`databases`配置文件中的节点。 连接名称标识中的某个元素`connectionStrings`部分，其中包含的数据库连接字符串。"
  example:
  - "The following code example shows how to use the ConnectionStringName property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#4](~/add/codesnippet/visualbasic/p-system.web.configurati_380_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#4](~/add/codesnippet/csharp/p-system.web.configurati_380_1.cs)]"
  syntax:
    content: public string ConnectionStringName { get; set; }
    return:
      type: System.String
      description: "一个字符串，指定数据库连接字符串中的名称<xref uid=&quot;langword_csharp_connectionStrings&quot; name=&quot;connectionStrings&quot; href=&quot;&quot;></xref>配置节。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  id: ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElementProperty ElementProperty { get; }
    return:
      type: System.Configuration.ConfigurationElementProperty
      description: "要添加。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  id: Name
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置数据库的名称。"
  remarks: "名称属性允许您以编程方式访问和修改`name`属性`add`元素`databases`配置文件中的节点。       `name`属性标识其表用于<xref:System.Web.Caching.SqlCacheDependency>.</xref:System.Web.Caching.SqlCacheDependency>的数据库"
  example:
  - "The following code example shows how to use the Name property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#3](~/add/codesnippet/visualbasic/p-system.web.configurati_277_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#3](~/add/codesnippet/csharp/p-system.web.configurati_277_1.cs)]"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "一个字符串，指定使用的名称<xref href=&quot;System.Web.Configuration.SqlCacheDependencyDatabase&quot;></xref>来标识数据库。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  id: PollTime
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置的频率<xref href=&quot;System.Web.Caching.SqlCacheDependency&quot;></xref>轮询更改的数据库表。"
  remarks: "PollTime 属性允许您以编程方式访问和修改`pollTime`属性`add`元素`databases`配置文件中的节点。       配置 ASP.NET 应用程序的缓存与特定 SQL Server 数据库表的实例中存储的项之间的关系之后<xref:System.Web.Caching.SqlCacheDependency>类监视表，以便当表更改中的项，该项是自动更新中或从缓存中删除。</xref:System.Web.Caching.SqlCacheDependency> 监视发生在由 PollTime 指定的频率。"
  example:
  - "The following code example shows how to use the PollTime property.  \n  \n [!code-vb[System.Web.Configuration.SqlCacheDependencyDatabase#2](~/add/codesnippet/visualbasic/p-system.web.configurati_251_1.vb)]\n [!code-cs[System.Web.Configuration.SqlCacheDependencyDatabase#2](~/add/codesnippet/csharp/p-system.web.configurati_251_1.cs)]"
  syntax:
    content: public int PollTime { get; set; }
    return:
      type: System.Int32
      description: "数据库轮询时间，以毫秒为单位。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  id: Properties
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  langs:
  - csharp
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.SqlCacheDependencyDatabase.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String)
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase(String,String)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor(System.String,System.String,System.Int32)
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase(String,String,Int32)
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.SqlCacheDependencyDatabase(String,String,Int32)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty
- uid: System.Configuration.ConfigurationElementProperty
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementProperty
  nameWithType: ConfigurationElementProperty
  fullName: System.Configuration.ConfigurationElementProperty
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Name
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
  fullName: System.Web.Configuration.SqlCacheDependencyDatabase.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.#ctor*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: SqlCacheDependencyDatabase
  nameWithType: SqlCacheDependencyDatabase.SqlCacheDependencyDatabase
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ConnectionStringName*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ConnectionStringName
  nameWithType: SqlCacheDependencyDatabase.ConnectionStringName
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.ElementProperty*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: ElementProperty
  nameWithType: SqlCacheDependencyDatabase.ElementProperty
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Name*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Name
  nameWithType: SqlCacheDependencyDatabase.Name
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.PollTime*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: PollTime
  nameWithType: SqlCacheDependencyDatabase.PollTime
- uid: System.Web.Configuration.SqlCacheDependencyDatabase.Properties*
  parent: System.Web.Configuration.SqlCacheDependencyDatabase
  isExternal: false
  name: Properties
  nameWithType: SqlCacheDependencyDatabase.Properties
