### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.IServerWebConfig
  id: IServerWebConfig
  children:
  - System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: IServerWebConfig
  nameWithType: IServerWebConfig
  fullName: System.EnterpriseServices.Internal.IServerWebConfig
  type: Interface
  summary: "创建 SOAP 启用 COM + 应用程序的 Web.config 文件并将组件条目添加到要发布应用程序中的 COM 接口的文件。"
  remarks: "仅可由实现 IServerWebConfig 接口<xref:System.EnterpriseServices.Internal.ServerWebConfig>类，并仅在.NET Framework 基础结构中使用。</xref:System.EnterpriseServices.Internal.ServerWebConfig> 而不是实现此接口或 IServerWebConfig 接口对象进行实例化，使用<xref:System.EnterpriseServices.Internal.Publish>类，该类实现<xref:System.EnterpriseServices.Internal.IComSoapPublisher>接口。</xref:System.EnterpriseServices.Internal.IComSoapPublisher> </xref:System.EnterpriseServices.Internal.Publish>       IServerWebConfig 由.NET Framework 在内部使用。 不需要在代码中直接使用它。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("6261e4b5-572a-4142-a2f9-1fe1a0c97097")]

      public interface IServerWebConfig
  implements: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "将 XML 元素添加到 Web.config 文件，以便在 SOAP 启用 COM + 应用程序中正在发布的 COM 接口。"
  remarks: "请参阅<xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A>实现详细信息的方法。</xref:System.EnterpriseServices.Internal.ServerWebConfig.AddElement%2A> 但是，不需要调用`AddElement`直接的方法。"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string Mode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "现有的 Web.config 文件的路径。"
    - id: AssemblyName
      type: System.String
      description: "包含所添加的类型的程序集的名称。"
    - id: TypeName
      type: System.String
      description: "所添加的类型的名称。"
    - id: ProgId
      type: System.String
      description: "所添加的类型编程标识符。"
    - id: Mode
      type: System.String
      description: "对应于中的成员的名称的字符串常量<xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;></xref>枚举，指示如何激活的已知对象。"
    - id: Error
      type: System.String
      description: "可以向其写入一条错误消息字符串。"
  overload: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "创建 SOAP 启用 COM + 应用程序的 Web.config 文件，以便该文件已准备好添加为要发布的 COM 接口的 XML 元素。"
  remarks: "请参阅<xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A>实现详细信息的方法。</xref:System.EnterpriseServices.Internal.ServerWebConfig.Create%2A> 但是，不需要调用`Create`直接。"
  syntax:
    content: public void Create (string FilePath, string FileRootName, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "在其中创建配置文件的文件夹。"
    - id: FileRootName
      type: System.String
      description: "字符串值 （例如，为 Web.config 的 Web） 添加的配置扩展。"
    - id: Error
      type: System.String
      description: "可以向其写入一条错误消息字符串。"
  overload: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: IServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: IServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.IServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.IServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: IServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.IServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.IServerWebConfig
  isExternal: false
  name: Create
  nameWithType: IServerWebConfig.Create
