### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CacheSection
  id: CacheSection
  children:
  - System.Web.Configuration.CacheSection.#ctor
  - System.Web.Configuration.CacheSection.DisableExpiration
  - System.Web.Configuration.CacheSection.DisableMemoryCollection
  - System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit
  - System.Web.Configuration.CacheSection.PrivateBytesLimit
  - System.Web.Configuration.CacheSection.PrivateBytesPollTime
  - System.Web.Configuration.CacheSection.Properties
  langs:
  - csharp
  name: CacheSection
  nameWithType: CacheSection
  fullName: System.Web.Configuration.CacheSection
  type: Class
  summary: "配置 ASP.NET 应用程序的全局缓存设置。 此类不能被继承。"
  remarks: "CacheSection 类使您能够以编程方式访问和修改`<cache>`配置文件节。       ASP.NET 缓存功能实现的<xref:System.Web.Caching.Cache>类。</xref:System.Web.Caching.Cache> 有关详细信息，请参阅[Caching](~/add/includes/ajax-current-ext-md.md)。      1> [!NOTE]&1;> CacheSection 可将信息写入到根据定义的部分属性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值为<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>的限制的配置文件的相关部分 在层次结构不允许层次结构中的配置文件中写入任何尝试会对由分析器生成的错误消息中。 但是，此类可用于读取层次结构中的任何级别的配置信息。       缓存是一个用于存储经常访问的数据的特定于应用程序的哈希表。 应用程序和会话状态是类似于缓存中，正在非常类似，由于其应用程序范围的应用程序状态。 缓存和应用程序状态机制之间的最大差异之一是缓存支持这种依赖性，使得可以在生成应用程序发生某些事件时，会自动删除缓存的项的依赖关系。"
  example:
  - "The following code example shows a page and the related code file used to  access the  CacheSection section attributes.  \n  \n [!code-cs[System.Web.Configuration.CacheSection#11](~/add/codesnippet/csharp/t-system.web.configurati_81_1.aspx)]\n [!code-vb[System.Web.Configuration.CacheSection#11](~/add/codesnippet/visualbasic/t-system.web.configurati_81_1.aspx)]  \n  \n [!code-vb[System.Web.Configuration.CacheSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_81_2.vb)]\n [!code-cs[System.Web.Configuration.CacheSection#1](~/add/codesnippet/csharp/t-system.web.configurati_81_2.cs)]"
  syntax:
    content: 'public sealed class CacheSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: CacheSection()
  nameWithType: CacheSection.CacheSection()
  fullName: System.Web.Configuration.CacheSection.CacheSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.CacheSection&quot;></xref>类。"
  remarks: "CacheSection 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.CacheSection>类通过<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.CacheSection>"
  example:
  - >-
    [!code-vb[System.Web.Configuration.CacheSection#2](~/add/codesnippet/visualbasic/m-system.web.configurati_30_1.vb)]
     [!code-cs[System.Web.Configuration.CacheSection#2](~/add/codesnippet/csharp/m-system.web.configurati_30_1.cs)]
  syntax:
    content: public CacheSection ();
    parameters: []
  overload: System.Web.Configuration.CacheSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.DisableExpiration
  id: DisableExpiration
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: DisableExpiration
  nameWithType: CacheSection.DisableExpiration
  fullName: System.Web.Configuration.CacheSection.DisableExpiration
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值指示是否禁用缓存过期时间。"
  remarks: "如果 DisableExpiration 属性设置为`true`，永不过期的缓存的项。 此设置被为了帮助调试应用程序代码中的缓存行为。 时要格外小心禁用缓存过期时间，因为这可能会导致项目缓存的时间超过它们是有效的。      1> [!NOTE]&1;> 要添加到输出缓存的页，必须建立该页面的过期策略。 你可以执行此操作以声明方式与[@ OutputCache](http://msdn.microsoft.com/en-us/28a9e101-fb44-4198-9cb6-b8a52312fec2)指令或以编程方式使用<xref:System.Web.HttpCachePolicy.SetExpires%2A>方法。</xref:System.Web.HttpCachePolicy.SetExpires%2A> 有关详细信息，请参阅[如何︰ 为 ASP.NET 页面缓存设置过期值](~/add/includes/ajax-current-ext-md.md)。"
  example:
  - "The following code example shows how to use the DisableExpiration property.  \n  \n [!code-vb[System.Web.Configuration.CacheSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_391_1.vb)]\n [!code-cs[System.Web.Configuration.CacheSection#4](~/add/codesnippet/csharp/p-system.web.configurati_391_1.cs)]"
  syntax:
    content: public bool DisableExpiration { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果禁用了缓存过期时间;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.CacheSection.DisableExpiration*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.DisableMemoryCollection
  id: DisableMemoryCollection
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: DisableMemoryCollection
  nameWithType: CacheSection.DisableMemoryCollection
  fullName: System.Web.Configuration.CacheSection.DisableMemoryCollection
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值指示是否禁用缓存内存集合。"
  remarks: "如果 DisableMemoryCollection 属性设置为`true`，对缓存相关 API 的调用将产生任何影响。       如果 DisableMemoryCollection 属性设置为`true`，缓存不会尝试收集未使用的项。 请小心使用此设置，因为禁用内存集合快速将导致应用程序的内存不足条件。       此设置不起 ASP.NET 内部缓存在或上输出缓存。 有关不同类型的缓存的详细信息，请参阅[Caching](~/add/includes/ajax-current-ext-md.md)。"
  example:
  - "The following code example shows how to use the DisableMemoryCollection property.  \n  \n [!code-vb[System.Web.Configuration.CacheSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_298_1.vb)]\n [!code-cs[System.Web.Configuration.CacheSection#3](~/add/codesnippet/csharp/p-system.web.configurati_298_1.cs)]"
  syntax:
    content: public bool DisableMemoryCollection { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果缓存内存集合处于禁用状态;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.CacheSection.DisableMemoryCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit
  id: PercentagePhysicalMemoryUsedLimit
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: PercentagePhysicalMemoryUsedLimit
  nameWithType: CacheSection.PercentagePhysicalMemoryUsedLimit
  fullName: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值虚拟内存使用情况的最大百分比。"
  remarks: "PercentagePhysicalMemoryUsedLimit 属性指定高压力条件的阈值。 如在达到此阈值，则缓存系统逐渐开始更积极的清理措施。"
  example:
  - >-
    [!code-vb[System.Web.Configuration.CacheSection#7](~/add/codesnippet/visualbasic/p-system.web.configurati_357_1.vb)]
     [!code-cs[System.Web.Configuration.CacheSection#7](~/add/codesnippet/csharp/p-system.web.configurati_357_1.cs)]
  syntax:
    content: public int PercentagePhysicalMemoryUsedLimit { get; set; }
    return:
      type: System.Int32
      description: "虚拟内存使用率的最大百分比。 默认值为 90%。"
  overload: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.PrivateBytesLimit
  id: PrivateBytesLimit
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: PrivateBytesLimit
  nameWithType: CacheSection.PrivateBytesLimit
  fullName: System.Web.Configuration.CacheSection.PrivateBytesLimit
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值的工作进程专用空间的最大大小。"
  remarks: "PrivateBytesLimit 属性指定高压力条件的阈值。 如在达到此阈值，则缓存系统逐渐开始更积极的清理措施。"
  example:
  - >-
    [!code-vb[System.Web.Configuration.CacheSection#6](~/add/codesnippet/visualbasic/p-system.web.configurati_382_1.vb)]
     [!code-cs[System.Web.Configuration.CacheSection#6](~/add/codesnippet/csharp/p-system.web.configurati_382_1.cs)]
  syntax:
    content: public long PrivateBytesLimit { get; set; }
    return:
      type: System.Int64
      description: "为工作进程分配的专用空间最大数目，以字节为单位。 默认值为 0"
  overload: System.Web.Configuration.CacheSection.PrivateBytesLimit*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.PrivateBytesPollTime
  id: PrivateBytesPollTime
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: PrivateBytesPollTime
  nameWithType: CacheSection.PrivateBytesPollTime
  fullName: System.Web.Configuration.CacheSection.PrivateBytesPollTime
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值的工作进程内存使用量的轮询时间间隔。"
  remarks: "此轮询很高，可能需要进行调整，缓存修整算法的反应速度和轮询作出的调用数之间的权衡。"
  syntax:
    content: public TimeSpan PrivateBytesPollTime { get; set; }
    return:
      type: System.TimeSpan
      description: "辅助进程内存使用量的轮询之间的时间间隔。 默认值为 2 分钟。"
  overload: System.Web.Configuration.CacheSection.PrivateBytesPollTime*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CacheSection.Properties
  id: Properties
  parent: System.Web.Configuration.CacheSection
  langs:
  - csharp
  name: Properties
  nameWithType: CacheSection.Properties
  fullName: System.Web.Configuration.CacheSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.CacheSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.CacheSection.#ctor
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: CacheSection()
  nameWithType: CacheSection.CacheSection()
  fullName: System.Web.Configuration.CacheSection.CacheSection()
- uid: System.Web.Configuration.CacheSection.DisableExpiration
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: DisableExpiration
  nameWithType: CacheSection.DisableExpiration
  fullName: System.Web.Configuration.CacheSection.DisableExpiration
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.CacheSection.DisableMemoryCollection
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: DisableMemoryCollection
  nameWithType: CacheSection.DisableMemoryCollection
  fullName: System.Web.Configuration.CacheSection.DisableMemoryCollection
- uid: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PercentagePhysicalMemoryUsedLimit
  nameWithType: CacheSection.PercentagePhysicalMemoryUsedLimit
  fullName: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.CacheSection.PrivateBytesLimit
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PrivateBytesLimit
  nameWithType: CacheSection.PrivateBytesLimit
  fullName: System.Web.Configuration.CacheSection.PrivateBytesLimit
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.CacheSection.PrivateBytesPollTime
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PrivateBytesPollTime
  nameWithType: CacheSection.PrivateBytesPollTime
  fullName: System.Web.Configuration.CacheSection.PrivateBytesPollTime
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Web.Configuration.CacheSection.Properties
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: Properties
  nameWithType: CacheSection.Properties
  fullName: System.Web.Configuration.CacheSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.CacheSection.#ctor*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: CacheSection
  nameWithType: CacheSection.CacheSection
- uid: System.Web.Configuration.CacheSection.DisableExpiration*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: DisableExpiration
  nameWithType: CacheSection.DisableExpiration
- uid: System.Web.Configuration.CacheSection.DisableMemoryCollection*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: DisableMemoryCollection
  nameWithType: CacheSection.DisableMemoryCollection
- uid: System.Web.Configuration.CacheSection.PercentagePhysicalMemoryUsedLimit*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PercentagePhysicalMemoryUsedLimit
  nameWithType: CacheSection.PercentagePhysicalMemoryUsedLimit
- uid: System.Web.Configuration.CacheSection.PrivateBytesLimit*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PrivateBytesLimit
  nameWithType: CacheSection.PrivateBytesLimit
- uid: System.Web.Configuration.CacheSection.PrivateBytesPollTime*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: PrivateBytesPollTime
  nameWithType: CacheSection.PrivateBytesPollTime
- uid: System.Web.Configuration.CacheSection.Properties*
  parent: System.Web.Configuration.CacheSection
  isExternal: false
  name: Properties
  nameWithType: CacheSection.Properties
