### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  id: ConfigurationElementInterceptor
  children:
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  langs:
  - csharp
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  type: Class
  summary: "有的任意元素和属性，则用户可以指定 Windows Identity Foundation (WIF) 配置架构的部分例如，当指定的自定义令牌处理程序。 实现 ConfigurationElementInterceptor 类是为了处理这种情况。"
  syntax:
    content: 'public class ConfigurationElementInterceptor : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;></xref>类。"
  syntax:
    content: public ConfigurationElementInterceptor ();
    parameters: []
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  id: ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "获取此元素的节点的子级。"
  syntax:
    content: public System.Xml.XmlNodeList ChildNodes { get; }
    return:
      type: System.Xml.XmlNodeList
      description: "子节点的集合。 <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>如果此元素具有任何子节点。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  id: DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "从配置文件读取 XML。"
  syntax:
    content: protected override void DeserializeElement (System.Xml.XmlReader reader, bool serializeCollectionKey);
    parameters:
    - id: reader
      type: System.Xml.XmlReader
      description: "<xref:System.Xml.XmlReader>从配置文件进行读取。</xref:System.Xml.XmlReader>"
    - id: serializeCollectionKey
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>只序列化集合键属性;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  id: ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "获取此实例所表示的 XML 元素。"
  syntax:
    content: public System.Xml.XmlElement ElementAsXml { get; }
    return:
      type: System.Xml.XmlElement
      description: "XML 元素中。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  id: OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "获取一个值，该值指示反序列化过程中是否遇到未知的属性。 始终返回<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  remarks: "<xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>类专门实现来处理任意、 用户定义的特性和元素。</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> 因此，此方法返回`true`当.NET Framework 检测到的无法识别的元素或属性需要运行分析器。"
  syntax:
    content: protected override bool OnDeserializeUnrecognizedAttribute (string name, string value);
    parameters:
    - id: name
      type: System.String
      description: "无法识别的属性名称。"
    - id: value
      type: System.String
      description: "无法识别的属性值。"
    return:
      type: System.Boolean
      description: "始终返回<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>，指示已遇到无法识别的属性。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  id: OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "获取一个值，该值指示反序列化过程中是否遇到未知的元素。 始终返回<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  remarks: "<xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor>类专门实现来处理任意、 用户定义的特性和元素。</xref:System.IdentityModel.Configuration.ConfigurationElementInterceptor> 因此，此方法返回`true`当.NET Framework 检测到的无法识别的元素或属性需要运行分析器。"
  syntax:
    content: protected override bool OnDeserializeUnrecognizedElement (string elementName, System.Xml.XmlReader reader);
    parameters:
    - id: elementName
      type: System.String
      description: "未知子元素的名称。"
    - id: reader
      type: System.Xml.XmlReader
      description: "用于反序列化 XML 读取器。"
    return:
      type: System.Boolean
      description: "始终返回<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>，指示已遇到未识别的元素。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  id: Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  langs:
  - csharp
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "重置的内部状态<xref href=&quot;System.IdentityModel.Configuration.ConfigurationElementInterceptor&quot;></xref>对象，包括锁定和属性集合。"
  syntax:
    content: protected override void Reset (System.Configuration.ConfigurationElement parentElement);
    parameters:
    - id: parentElement
      type: System.Configuration.ConfigurationElement
      description: "配置元素的父节点。"
  overload: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor()
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor()
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ConfigurationElementInterceptor()
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement(XmlReader,Boolean)
  nameWithType: ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(XmlReader,Boolean)
- uid: System.Xml.XmlReader
  parent: System.Xml
  isExternal: true
  name: XmlReader
  nameWithType: XmlReader
  fullName: System.Xml.XmlReader
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
- uid: System.Xml.XmlElement
  parent: System.Xml
  isExternal: false
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute(String,String)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement(String,XmlReader)
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(String,XmlReader)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset(ConfigurationElement)
  nameWithType: ConfigurationElementInterceptor.Reset(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(ConfigurationElement)
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.#ctor*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ConfigurationElementInterceptor
  nameWithType: ConfigurationElementInterceptor.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ChildNodes
  nameWithType: ConfigurationElementInterceptor.ChildNodes
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: DeserializeElement
  nameWithType: ConfigurationElementInterceptor.DeserializeElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: ElementAsXml
  nameWithType: ConfigurationElementInterceptor.ElementAsXml
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedAttribute
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: OnDeserializeUnrecognizedElement
  nameWithType: ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset*
  parent: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: Reset
  nameWithType: ConfigurationElementInterceptor.Reset
