### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationException
  id: WorkflowApplicationException
  children:
  - System.Activities.WorkflowApplicationException.#ctor
  - System.Activities.WorkflowApplicationException.#ctor(System.String)
  - System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  langs:
  - csharp
  name: WorkflowApplicationException
  nameWithType: WorkflowApplicationException
  fullName: System.Activities.WorkflowApplicationException
  type: Class
  summary: "提供用于处理工作流应用程序执行过程中发生错误的基类。"
  syntax:
    content: 'public class WorkflowApplicationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException()
  nameWithType: WorkflowApplicationException.WorkflowApplicationException()
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>类。"
  syntax:
    content: public WorkflowApplicationException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>类的异常的文本字符串说明。"
  syntax:
    content: public WorkflowApplicationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "应用程序异常的说明。"
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>从序列化流检索有关此异常的数据所需的上下文和序列化信息的类。"
  syntax:
    content: protected WorkflowApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "序列化或反序列化的应用程序异常对象所需的信息。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "源和目标的给定序列化的流中和其他调用方定义的上下文。"
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>类的异常的文本字符串说明和导致应用程序异常的其他异常。"
  remarks: "应用程序异常因响应内部异常引发，并且可以使用来自内部异常的信息更恰当处理错误。"
  syntax:
    content: public WorkflowApplicationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "应用程序异常的说明。"
    - id: innerException
      type: System.Exception
      description: "异常有因果关系的应用程序异常。"
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Guid)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>类的异常的文本字符串说明，并使用它的唯一标识符。"
  syntax:
    content: public WorkflowApplicationException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "应用程序异常的说明。"
    - id: instanceId
      type: System.Guid
      description: "全局唯一标识符。"
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: WorkflowApplicationException(String,Guid,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "创建的新实例<xref href=&quot;System.Activities.WorkflowApplicationException&quot;></xref>异常、 其唯一标识符和其他异常的应用程序异常导致的异常的文本字符串说明类。"
  remarks: "应用程序异常因响应内部异常引发，并且可以使用来自内部异常的信息更恰当处理错误。"
  syntax:
    content: public WorkflowApplicationException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "应用程序异常的说明。"
    - id: instanceId
      type: System.Guid
      description: "全局唯一标识符。"
    - id: innerException
      type: System.Exception
      description: "异常有因果关系的应用程序异常。"
  overload: System.Activities.WorkflowApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "设置指定<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;></xref>包含有关异常的信息的对象。"
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "序列化或反序列化中止异常对象所需的信息。"
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "源和目标的给定序列化的流中和其他调用方定义的上下文。"
  overload: System.Activities.WorkflowApplicationException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationException.InstanceId
  id: InstanceId
  parent: System.Activities.WorkflowApplicationException
  langs:
  - csharp
  name: InstanceId
  nameWithType: WorkflowApplicationException.InstanceId
  fullName: System.Activities.WorkflowApplicationException.InstanceId
  type: Property
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "获取当前异常的唯一标识符。"
  syntax:
    content: public Guid InstanceId { get; }
    return:
      type: System.Guid
      description: "唯一的标识符。"
  overload: System.Activities.WorkflowApplicationException.InstanceId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.Activities.WorkflowApplicationException.#ctor
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException()
  nameWithType: WorkflowApplicationException.WorkflowApplicationException()
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException()
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Exception)
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Guid)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException(String,Guid,Exception)
  nameWithType: WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationException.WorkflowApplicationException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Activities.WorkflowApplicationException.InstanceId
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationException.InstanceId
  fullName: System.Activities.WorkflowApplicationException.InstanceId
- uid: System.Activities.WorkflowApplicationException.#ctor*
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: WorkflowApplicationException
  nameWithType: WorkflowApplicationException.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationException.GetObjectData*
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: GetObjectData
  nameWithType: WorkflowApplicationException.GetObjectData
- uid: System.Activities.WorkflowApplicationException.InstanceId*
  parent: System.Activities.WorkflowApplicationException
  isExternal: false
  name: InstanceId
  nameWithType: WorkflowApplicationException.InstanceId
