### YamlMime:ManagedReference
items:
- uid: System.Configuration.DpapiProtectedConfigurationProvider
  id: DpapiProtectedConfigurationProvider
  children:
  - System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  - System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  - System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider
  fullName: System.Configuration.DpapiProtectedConfigurationProvider
  type: Class
  summary: "提供<xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;></xref>使用 Windows 数据保护 API (DPAPI) 进行加密和解密配置数据的对象。"
  remarks: "DpapiProtectedConfigurationProvider，可防止未经授权的访问配置文件中存储的敏感信息。       声明提供程序和配置文件中的相应设置，而不是创建此类的实例通过使用标准 DpapiProtectedConfigurationProvider。 请参阅下一个示例。       有关受保护的配置的详细信息，请参阅[加密配置信息使用受保护的配置](~/add/includes/ajax-current-ext-md.md)。       DpapiProtectedConfigurationProvider 使用 Windows 内置加密服务，并可以为特定于计算机或用户帐户特定保护配置。 计算机特定保护的匿名服务很有用，但提供的安全性。 用户帐户特定保护可用于使用特定的用户标识运行的服务。"
  example:
  - "The following example shows how to use the standard DpapiProtectedConfigurationProvider to protect or unprotect a configuration section.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n  \n The following configuration excerpts show the configuration section before and after the protection has been applied.  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\" ?>  \n<configuration>  \n  <connectionStrings>  \n    <add name=\"NorthwindConnectionString\"   \n      connectionString=\"Data Source=webnetue2;Initial Catalog=Northwind;User ID=aspnet_test;Password=test\"  \n      providerName=\"System.Data.SqlClient\" />  \n  </connectionStrings>  \n</configuration>  \n```  \n  \n```  \n<?xml version=\"1.0\" encoding=\"utf-8\"?>  \n<configuration>  \n  <connectionStrings>  \n    <EncryptedData>  \n      <CipherData>                <CipherValue>AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAcAMh0jIC1kigyFfd9AUZfQQAAAACAAAAAAADZgAAqAAAABAAAADQwbQ2DgIgIlqskE1RI9UpAAAAAASAAACgAAAAEAAAAAXlYBxi3jhM6wv4sxLhugsQAgAAgoReHZS2406dc/AyRDd6WuNr4ihHn6fbipd4tzHEmeuyS4o4fS4CmT3jMt/WjsP/kR7TF4ygwr2GG47podK79ECpVCZHAgctCauCYjE2Ls3iphKXy/pHic2o6aaClt/xPm+fb4OfODv6XjrJhJzGK2lqUPXkyJN1w2zwh6OVpDQF9N8vTyxL4eitp35/M5zYbW7e6VVAgYUOxlNxgCV5+jXpUKh/rPovopTD392u8KavqQFW1iu+gBPSPq/xeZNz+qYMKbUl+r4VTzBQg3fPlRxp1lNZmM2yRgUbkYPNaFb9ihS7GAg5/wZn8lLmThvq39eA0Vlp6hDE92iop885umELt0/NBKf5umQCqqz9EXXLbmmGc7qoLqTaYVuOmqx0LsvrJL0wSL1dSySCjmB/dNAtVUYgg02eWQNKyaLqnpMdCbTLLQ/oCKuNkL5OQ7t1yl5wQGjQhieIRzLtrMgpTSyaHbqDsRurp9Bc5mM078IAg1hXquQNKlJC/wiJ9kbHerFCbtuLGy/7nXVrFH91ud4U4ExCJEuhoTdmuql5kbqYd6Ye/bu2CftPni19nDkSJ8w4NoqMNKbK3Mi/Cd0o113HsVYlETMv1vlJWZWYP91PK9trixiY4E0G81c6IKITjHDrOJ9evdw2T1/TrvY6pzre3UXSJbFMDQVX6JoAxFk02SRZDKOZdRojeoX19lgrFAAAABzjlz3Qg2as3vn7MRQVxDfZucgE</CipherValue>  \n      </CipherData>  \n    </EncryptedData>  \n  </connectionStrings>  \n  <configProtectedData defaultProvider=\"RsaProtectedConfigurationProvider\">  \n    <providers>  \n      <clear />  \n      <add keyContainerName=\"NetFrameworkConfigurationKey\" cspProviderName=\"\"  \n        useMachineContainer=\"true\" useOAEP=\"false\" description=\"Uses RsaCryptoServiceProvider to encrypt and decrypt\"  \n        name=\"RsaProtectedConfigurationProvider\" type=\"System.Configuration.RsaProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n      <add useMachineProtection=\"true\" description=\"Uses CryptProtectData and CryptUnProtectData Windows APIs to encrypt and decrypt\"  \n        keyEntropy=\"\" name=\"DataProtectionConfigurationProvider\" type=\"System.Configuration.DpapiProtectedConfigurationProvider,System.Configuration, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\" />  \n    </providers>  \n  </configProtectedData>  \n</configuration>  \n```"
  syntax:
    content: 'public sealed class DpapiProtectedConfigurationProvider : System.Configuration.ProtectedConfigurationProvider'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  - System.Configuration.ProtectedConfigurationProvider
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;></xref>类使用默认设置。"
  remarks: "DpapiProtectedConfigurationProvider 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。"
  syntax:
    content: public DpapiProtectedConfigurationProvider ();
    parameters: []
  overload: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  id: Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "解密传递<xref href=&quot;System.Xml.XmlNode&quot;></xref>对象。"
  syntax:
    content: public override System.Xml.XmlNode Decrypt (System.Xml.XmlNode encryptedNode);
    parameters:
    - id: encryptedNode
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref>对象进行解密。"
    return:
      type: System.Xml.XmlNode
      description: "解密<xref href=&quot;System.Xml.XmlNode&quot;></xref>对象。"
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "<code>encryptedNode</code> does not have <xref:System.Xml.XmlNode.Name*> set to \"EncryptedData\" and <xref:System.Xml.XmlNodeType> set to <xref:System.Xml.XmlNodeType>.  \n  \n \\- or -  \n  \n <code>encryptedNode</code> does not have a child node named \"CipherData\" with a child node named \"CipherValue\".  \n  \n \\- or -  \n  \n The child node named \"CipherData\" is an empty node."
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  id: Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "加密传递<xref href=&quot;System.Xml.XmlNode&quot;></xref>对象。"
  syntax:
    content: public override System.Xml.XmlNode Encrypt (System.Xml.XmlNode node);
    parameters:
    - id: node
      type: System.Xml.XmlNode
      description: "<xref href=&quot;System.Xml.XmlNode&quot;> </xref>对象进行加密。"
    return:
      type: System.Xml.XmlNode
      description: "加密<xref href=&quot;System.Xml.XmlNode&quot;></xref>对象。"
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化使用默认设置提供程序。"
  syntax:
    content: public override void Initialize (string name, System.Collections.Specialized.NameValueCollection configurationValues);
    parameters:
    - id: name
      type: System.String
      description: "要对对象使用的提供程序名称。"
    - id: configurationValues
      type: System.Collections.Specialized.NameValueCollection
      description: "A <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref>初始化对象时要使用的值的集合。"
  overload: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "<code>configurationValues</code>包含无法识别的配置设置。"
  platform:
  - net462
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  id: UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  langs:
  - csharp
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取一个值，该值指示是否<xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;></xref>对象正在使用计算机特定或用户帐户特定保护。"
  remarks: "计算机特定保护的匿名服务很有用，但提供的安全性。 用户帐户特定保护可用于使用特定的用户标识运行的服务。"
  syntax:
    content: public bool UseMachineProtection { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<xref href=&quot;System.Configuration.DpapiProtectedConfigurationProvider&quot;></xref>使用计算机特定保护;<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>如果正在使用用户帐户特定保护。"
  overload: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ProtectedConfigurationProvider
  isExternal: false
  name: System.Configuration.ProtectedConfigurationProvider
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider()
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider()
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt(XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(System.Xml.XmlNode)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt(XmlNode)
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt(XmlNode)
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.Initialize(String,NameValueCollection)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
  fullName: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.DpapiProtectedConfigurationProvider.#ctor*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: DpapiProtectedConfigurationProvider
  nameWithType: DpapiProtectedConfigurationProvider.DpapiProtectedConfigurationProvider
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Decrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Decrypt
  nameWithType: DpapiProtectedConfigurationProvider.Decrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Encrypt*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Encrypt
  nameWithType: DpapiProtectedConfigurationProvider.Encrypt
- uid: System.Configuration.DpapiProtectedConfigurationProvider.Initialize*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: Initialize
  nameWithType: DpapiProtectedConfigurationProvider.Initialize
- uid: System.Configuration.DpapiProtectedConfigurationProvider.UseMachineProtection*
  parent: System.Configuration.DpapiProtectedConfigurationProvider
  isExternal: false
  name: UseMachineProtection
  nameWithType: DpapiProtectedConfigurationProvider.UseMachineProtection
