### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs
  id: SelectingProviderEventArgs
  children:
  - System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  - System.Web.ApplicationServices.SelectingProviderEventArgs.User
  langs:
  - csharp
  name: SelectingProviderEventArgs
  nameWithType: SelectingProviderEventArgs
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs
  type: Class
  summary: "提供有关数据<xref href=&quot;System.Web.ApplicationServices.RoleService.SelectingProvider&quot;></xref>事件。"
  remarks: "SelectingProviderEventArgs 类提供了值<xref:System.Web.ApplicationServices.RoleService.SelectingProvider>事件处理程序。</xref:System.Web.ApplicationServices.RoleService.SelectingProvider> 你创建<xref:System.Web.ApplicationServices.RoleService.SelectingProvider>事件处理程序以在运行时选择的角色提供程序。</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>       <xref:System.Web.ApplicationServices.RoleService>类所引发<xref:System.Web.ApplicationServices.RoleService.SelectingProvider>事件时或者<xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A>方法或<xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A>方法<xref:System.Web.ApplicationServices.RoleService>类称为。</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.RoleService.GetRolesForCurrentUser%2A> </xref:System.Web.ApplicationServices.RoleService.IsCurrentUserInRole%2A> </xref:System.Web.ApplicationServices.RoleService.SelectingProvider> </xref:System.Web.ApplicationServices.RoleService>       你使用<xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A>属性来检索有关登录的用户的信息。</xref:System.Web.ApplicationServices.SelectingProviderEventArgs.User%2A> 若要检索其角色信息通过非默认角色提供程序，将设置<xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>为所需的角色提供程序名称属性<xref:System.Web.ApplicationServices.RoleService>要使用对象。</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the SelectingProviderEventArgs object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/t-system.web.application_0_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/t-system.web.application_0_1.asax)]"
  syntax:
    content: 'public class SelectingProviderEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  id: ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置要用于检索用户的角色的角色提供程序。"
  remarks: "ProviderName 属性用于设置期间的角色提供程序<xref:System.Web.ApplicationServices.RoleService.SelectingProvider>事件。</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and to set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_3_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_3_1.asax)]"
  syntax:
    content: public string ProviderName { get; set; }
    return:
      type: System.String
      description: "用于获取用户的角色的角色提供程序名称。"
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  id: User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  langs:
  - csharp
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取经过身份验证的用户。"
  remarks: "使用用户属性来检索有关在用户的信息<xref:System.Web.ApplicationServices.RoleService.SelectingProvider>事件。</xref:System.Web.ApplicationServices.RoleService.SelectingProvider>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event. The event handler uses the <xref:System.Web.ApplicationServices.SelectingProviderEventArgs> object to check the user name and set the role provider to use. The event handler is bound to the <xref:System.Web.ApplicationServices.RoleService.SelectingProvider> event in the `Application_Start` method of the Global.asax file.  \n  \n [!code-vb[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/visualbasic/p-system.web.application_9_1.asax)]\n [!code-cs[System.Web.Security.SelectingProviderEventHandler#1](~/add/codesnippet/csharp/p-system.web.application_9_1.asax)]"
  syntax:
    content: public System.Security.Principal.IPrincipal User { get; }
    return:
      type: System.Security.Principal.IPrincipal
      description: "一个包含身份验证的用户的对象。"
  overload: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
  fullName: System.Web.ApplicationServices.SelectingProviderEventArgs.User
- uid: System.Security.Principal.IPrincipal
  parent: System.Security.Principal
  isExternal: true
  name: IPrincipal
  nameWithType: IPrincipal
  fullName: System.Security.Principal.IPrincipal
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.ProviderName*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: ProviderName
  nameWithType: SelectingProviderEventArgs.ProviderName
- uid: System.Web.ApplicationServices.SelectingProviderEventArgs.User*
  parent: System.Web.ApplicationServices.SelectingProviderEventArgs
  isExternal: false
  name: User
  nameWithType: SelectingProviderEventArgs.User
