### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.IWebApplication
  id: IWebApplication
  children:
  - System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  - System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  - System.Web.UI.Design.IWebApplication.RootProjectItem
  langs:
  - csharp
  name: IWebApplication
  nameWithType: IWebApplication
  fullName: System.Web.UI.Design.IWebApplication
  type: Interface
  summary: "提供用于访问 Web 应用程序在设计宿主中，如接口[!INCLUDE[vsprvsext](~/add/includes/ajax-current-ext-md.md)]，在设计时。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("cff39fa8-5607-4b6d-86f3-cc80b3cfe2dd")]

      public interface IWebApplication : IServiceProvider
  implements:
  - System.IServiceProvider
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  id: GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "从设计宿主中基于其 URL 返回的项目项。"
  syntax:
    content: public System.Web.UI.Design.IProjectItem GetProjectItemFromUrl (string appRelativeUrl);
    parameters:
    - id: appRelativeUrl
      type: System.String
      description: "要检索的项目项相对路径。"
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "基于其 URL 设计宿主中的项目项。"
  overload: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  id: OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "返回<xref href=&quot;System.Configuration.Configuration&quot;></xref>表示当前的 Web 应用程序设计宿主中的对象。"
  syntax:
    content: public System.Configuration.Configuration OpenWebConfiguration (bool isReadOnly);
    parameters:
    - id: isReadOnly
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要指示返回<xref href=&quot;System.Configuration.Configuration&quot;></xref>可编辑; 否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
    return:
      type: System.Configuration.Configuration
      description: "表示当前的 Web 应用程序设计宿主中的对象。"
  overload: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  id: RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  langs:
  - csharp
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
  type: Property
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "从设计宿主中获取根项目项。"
  syntax:
    content: public System.Web.UI.Design.IProjectItem RootProjectItem { get; }
    return:
      type: System.Web.UI.Design.IProjectItem
      description: "设计宿主中的根项目项。"
  overload: System.Web.UI.Design.IWebApplication.RootProjectItem*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(System.String)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl(String)
  nameWithType: IWebApplication.GetProjectItemFromUrl(String)
  fullName: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl(String)
- uid: System.Web.UI.Design.IProjectItem
  parent: System.Web.UI.Design
  isExternal: false
  name: IProjectItem
  nameWithType: IProjectItem
  fullName: System.Web.UI.Design.IProjectItem
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(System.Boolean)
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration(Boolean)
  nameWithType: IWebApplication.OpenWebConfiguration(Boolean)
  fullName: System.Web.UI.Design.IWebApplication.OpenWebConfiguration(Boolean)
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
  fullName: System.Web.UI.Design.IWebApplication.RootProjectItem
- uid: System.Web.UI.Design.IWebApplication.GetProjectItemFromUrl*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: GetProjectItemFromUrl
  nameWithType: IWebApplication.GetProjectItemFromUrl
- uid: System.Web.UI.Design.IWebApplication.OpenWebConfiguration*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: OpenWebConfiguration
  nameWithType: IWebApplication.OpenWebConfiguration
- uid: System.Web.UI.Design.IWebApplication.RootProjectItem*
  parent: System.Web.UI.Design.IWebApplication
  isExternal: false
  name: RootProjectItem
  nameWithType: IWebApplication.RootProjectItem
