### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.MetadataElement
  id: MetadataElement
  children:
  - System.ServiceModel.Configuration.MetadataElement.#ctor
  - System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions
  - System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions
  - System.ServiceModel.Configuration.MetadataElement.PolicyImporters
  - System.ServiceModel.Configuration.MetadataElement.Properties
  - System.ServiceModel.Configuration.MetadataElement.WsdlImporters
  langs:
  - csharp
  name: MetadataElement
  nameWithType: MetadataElement
  fullName: System.ServiceModel.Configuration.MetadataElement
  type: Class
  summary: "表示一个配置元素，指定可以处理服务元数据的方式。 此类不能被继承。"
  syntax:
    content: 'public sealed class MetadataElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: MetadataElement()
  nameWithType: MetadataElement.MetadataElement()
  fullName: System.ServiceModel.Configuration.MetadataElement.MetadataElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.MetadataElement&quot;></xref>类。"
  syntax:
    content: public MetadataElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.MetadataElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions
  id: LoadPolicyImportExtensions
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: LoadPolicyImportExtensions()
  nameWithType: MetadataElement.LoadPolicyImportExtensions()
  fullName: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "加载的集合<xref href=&quot;System.ServiceModel.Description.IPolicyImportExtension&quot;></xref>用于导入有关绑定的自定义策略断言的对象。"
  syntax:
    content: public System.Collections.ObjectModel.Collection<System.ServiceModel.Description.IPolicyImportExtension> LoadPolicyImportExtensions ();
    parameters: []
    return:
      type: System.Collections.ObjectModel.Collection{System.ServiceModel.Description.IPolicyImportExtension}
      description: "集合<xref href=&quot;System.ServiceModel.Description.IPolicyImportExtension&quot;></xref>用于导入有关绑定的自定义策略断言的对象。"
  overload: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions
  id: LoadWsdlImportExtensions
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: LoadWsdlImportExtensions()
  nameWithType: MetadataElement.LoadWsdlImportExtensions()
  fullName: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "加载的集合<xref href=&quot;System.ServiceModel.Description.IWsdlImportExtension&quot;></xref>对象用于导入自定义 WSDL 信息。"
  syntax:
    content: public System.Collections.ObjectModel.Collection<System.ServiceModel.Description.IWsdlImportExtension> LoadWsdlImportExtensions ();
    parameters: []
    return:
      type: System.Collections.ObjectModel.Collection{System.ServiceModel.Description.IWsdlImportExtension}
      description: "集合<xref href=&quot;System.ServiceModel.Description.IWsdlImportExtension&quot;></xref>对象用于导入自定义 WSDL 信息。"
  overload: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.PolicyImporters
  id: PolicyImporters
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: PolicyImporters
  nameWithType: MetadataElement.PolicyImporters
  fullName: System.ServiceModel.Configuration.MetadataElement.PolicyImporters
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取指定有关绑定的自定义策略断言的导入的策略导入集合。"
  remarks: "策略导入程序用于搜索有关绑定功能，自定义策略断言，以及附加一个实现断言所需的功能的自定义绑定元素。"
  syntax:
    content: public System.ServiceModel.Configuration.PolicyImporterElementCollection PolicyImporters { get; }
    return:
      type: System.ServiceModel.Configuration.PolicyImporterElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.PolicyImporterElementCollection&quot;> </xref> ，它指定有关绑定的自定义策略断言的导入。"
  overload: System.ServiceModel.Configuration.MetadataElement.PolicyImporters*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: Properties
  nameWithType: MetadataElement.Properties
  fullName: System.ServiceModel.Configuration.MetadataElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.MetadataElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.MetadataElement.WsdlImporters
  id: WsdlImporters
  parent: System.ServiceModel.Configuration.MetadataElement
  langs:
  - csharp
  name: WsdlImporters
  nameWithType: MetadataElement.WsdlImporters
  fullName: System.ServiceModel.Configuration.MetadataElement.WsdlImporters
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取导入带有 Ws-policy 附件的 Web 服务描述语言 (WSDL) 1.1 元数据的 WSDL 导入程序集合。"
  remarks: "A<xref:System.ServiceModel.Description.WsdlImporter>用于导入元数据，以及将该信息转换为各种表示协定和终结点信息的类。</xref:System.ServiceModel.Description.WsdlImporter>       它可以有选择地将导入协定和终结点信息以及公开任何导入错误并接受与导入和转换过程相关的类型信息的属性。 它还支持导入某些绑定信息和提供对任何策略文档、 WSDL 文档、 WSDL 扩展和 XML 架构文档的访问的属性。"
  syntax:
    content: public System.ServiceModel.Configuration.WsdlImporterElementCollection WsdlImporters { get; }
    return:
      type: System.ServiceModel.Configuration.WsdlImporterElementCollection
      description: "将带有 WS Policy 附件的 Web 服务描述语言 (WSDL) 1.1 元数据导入的 WSDL 导入程序集合。"
  overload: System.ServiceModel.Configuration.MetadataElement.WsdlImporters*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.MetadataElement.#ctor
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: MetadataElement()
  nameWithType: MetadataElement.MetadataElement()
  fullName: System.ServiceModel.Configuration.MetadataElement.MetadataElement()
- uid: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: LoadPolicyImportExtensions()
  nameWithType: MetadataElement.LoadPolicyImportExtensions()
  fullName: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions()
- uid: System.Collections.ObjectModel.Collection{System.ServiceModel.Description.IPolicyImportExtension}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: Collection<IPolicyImportExtension>
  nameWithType: Collection<IPolicyImportExtension>
  fullName: System.Collections.ObjectModel.Collection<System.ServiceModel.Description.IPolicyImportExtension>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: Collection<System.ServiceModel.Description.IPolicyImportExtension>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.IPolicyImportExtension
    name: IPolicyImportExtension
    nameWithType: IPolicyImportExtension
    fullName: IPolicyImportExtension
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: LoadWsdlImportExtensions()
  nameWithType: MetadataElement.LoadWsdlImportExtensions()
  fullName: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions()
- uid: System.Collections.ObjectModel.Collection{System.ServiceModel.Description.IWsdlImportExtension}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: Collection<IWsdlImportExtension>
  nameWithType: Collection<IWsdlImportExtension>
  fullName: System.Collections.ObjectModel.Collection<System.ServiceModel.Description.IWsdlImportExtension>
  spec.csharp:
  - uid: System.Collections.ObjectModel.Collection`1
    name: Collection
    nameWithType: Collection
    fullName: Collection<System.ServiceModel.Description.IWsdlImportExtension>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.IWsdlImportExtension
    name: IWsdlImportExtension
    nameWithType: IWsdlImportExtension
    fullName: IWsdlImportExtension
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Configuration.MetadataElement.PolicyImporters
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: PolicyImporters
  nameWithType: MetadataElement.PolicyImporters
  fullName: System.ServiceModel.Configuration.MetadataElement.PolicyImporters
- uid: System.ServiceModel.Configuration.PolicyImporterElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: PolicyImporterElementCollection
  nameWithType: PolicyImporterElementCollection
  fullName: System.ServiceModel.Configuration.PolicyImporterElementCollection
- uid: System.ServiceModel.Configuration.MetadataElement.Properties
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: Properties
  nameWithType: MetadataElement.Properties
  fullName: System.ServiceModel.Configuration.MetadataElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.MetadataElement.WsdlImporters
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: WsdlImporters
  nameWithType: MetadataElement.WsdlImporters
  fullName: System.ServiceModel.Configuration.MetadataElement.WsdlImporters
- uid: System.ServiceModel.Configuration.WsdlImporterElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WsdlImporterElementCollection
  nameWithType: WsdlImporterElementCollection
  fullName: System.ServiceModel.Configuration.WsdlImporterElementCollection
- uid: System.ServiceModel.Configuration.MetadataElement.#ctor*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: MetadataElement
  nameWithType: MetadataElement.MetadataElement
- uid: System.ServiceModel.Configuration.MetadataElement.LoadPolicyImportExtensions*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: LoadPolicyImportExtensions
  nameWithType: MetadataElement.LoadPolicyImportExtensions
- uid: System.ServiceModel.Configuration.MetadataElement.LoadWsdlImportExtensions*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: LoadWsdlImportExtensions
  nameWithType: MetadataElement.LoadWsdlImportExtensions
- uid: System.ServiceModel.Configuration.MetadataElement.PolicyImporters*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: PolicyImporters
  nameWithType: MetadataElement.PolicyImporters
- uid: System.ServiceModel.Configuration.MetadataElement.Properties*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: Properties
  nameWithType: MetadataElement.Properties
- uid: System.ServiceModel.Configuration.MetadataElement.WsdlImporters*
  parent: System.ServiceModel.Configuration.MetadataElement
  isExternal: false
  name: WsdlImporters
  nameWithType: MetadataElement.WsdlImporters
