### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMapping
  id: UrlMapping
  children:
  - System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  - System.Web.Configuration.UrlMapping.MappedUrl
  - System.Web.Configuration.UrlMapping.Properties
  - System.Web.Configuration.UrlMapping.Url
  langs:
  - csharp
  name: UrlMapping
  nameWithType: UrlMapping
  fullName: System.Web.Configuration.UrlMapping
  type: Class
  summary: "将映射到 Web 应用程序中的页的 url 的用户显示的 URL。 此类不能被继承。"
  remarks: "UrlMapping 类允许你映射用户到你的 Web 应用程序中存在的 URL 显示的 URL。 添加到 UrlMapping 对象<xref:System.Web.Configuration.UrlMappingCollection>编程等效于包括`add`中的元素`urlMappings`配置文件节。</xref:System.Web.Configuration.UrlMappingCollection>       每个 UrlMapping 对象包含两个属性标识 URL。 一个属性指定向用户显示的 URL其他 Web 应用程序中指定的 URL。 尾随空白字符将忽略在<xref:System.Web.Configuration.UrlMapping.Url%2A>和<xref:System.Web.Configuration.UrlMapping.MappedUrl%2A>属性。</xref:System.Web.Configuration.UrlMapping.MappedUrl%2A> </xref:System.Web.Configuration.UrlMapping.Url%2A>      1> [!NOTE]&1;> UrlMapping 属性可将信息写入到根据定义的部分属性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值为<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>的限制的配置文件的相关部分 在层次结构不允许层次结构中的配置文件中写入任何尝试会对由分析器生成的错误消息中。 但是，此类可用于读取层次结构中的任何级别的配置信息。"
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/t-system.web.configurati_10_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/t-system.web.configurati_10_2.aspx)]"
  syntax:
    content: 'public sealed class UrlMapping : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.UrlMapping&quot;></xref>类。"
  remarks: "UrlMapping 构造函数仅供主要供内部使用 ASP.NET。 你不需要派生自此类，并且因为它可以用于修改 Web.config 文件，你可能从不需要在代码中使用它。"
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/m-system.web.configurati_60_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/m-system.web.configurati_60_2.aspx)]"
  syntax:
    content: public UrlMapping (string url, string mappedUrl);
    parameters:
    - id: url
      type: System.String
      description: "要向用户显示的 URL。"
    - id: mappedUrl
      type: System.String
      description: "Web 应用程序中存在一个 URL。"
  overload: System.Web.Configuration.UrlMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  id: MappedUrl
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Web 应用程序中的 URL。"
  remarks: "MappedUrl 属性是编程等效形式`mappedUrl`属性`add`中的元素`urlMappings`配置文件节。      1> [!NOTE] 1> 当使用 IIS 5.0，如果你使用 MappedUrl 属性来从受支持的页类型 （如.aspx 文件） 映射到不受支持的页类型 （如.asp 页），将会出错。 IIS 6.0 版支持这种类型的映射。"
  example:
  - "The following code example shows how to obtain the MappedUrl property. This example is from a larger example for the <xref:System.Web.Configuration.UrlMapping> class.  \n  \n [!code-cs[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/csharp/p-system.web.configurati_113_1.aspx)]\n [!code-vb[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/visualbasic/p-system.web.configurati_113_1.aspx)]"
  syntax:
    content: public string MappedUrl { get; }
    return:
      type: System.String
      description: "Web 应用程序已映射到指定的值中的 URL<xref:System.Web.Configuration.UrlMapping.Url*>属性。</xref:System.Web.Configuration.UrlMapping.Url*>"
  overload: System.Web.Configuration.UrlMapping.MappedUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.UrlMapping.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Url
  id: Url
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取向用户显示的 URL。"
  remarks: "Url 属性是编程等效形式`Url`属性`add`中的元素`urlMappings`配置文件节。"
  example:
  - For an example, see the <xref:System.Web.Configuration.UrlMapping> class overview.
  syntax:
    content: public string Url { get; }
    return:
      type: System.String
      description: "向用户显示的 URL。"
  overload: System.Web.Configuration.UrlMapping.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMapping.Url
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
- uid: System.Web.Configuration.UrlMapping.#ctor*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping
  nameWithType: UrlMapping.UrlMapping
- uid: System.Web.Configuration.UrlMapping.MappedUrl*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
- uid: System.Web.Configuration.UrlMapping.Url*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
