### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  id: ProfileGuidedOptimizationsFlags
  children:
  - System.Web.Configuration.ProfileGuidedOptimizationsFlags.All
  - System.Web.Configuration.ProfileGuidedOptimizationsFlags.None
  langs:
  - csharp
  name: ProfileGuidedOptimizationsFlags
  nameWithType: ProfileGuidedOptimizationsFlags
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  type: Enum
  summary: "指定应用程序部署环境优化模式。"
  syntax:
    content: >-
      [System.Flags]

      public enum ProfileGuidedOptimizationsFlags
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags.All
  id: All
  parent: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  langs:
  - csharp
  name: All
  nameWithType: ProfileGuidedOptimizationsFlags.All
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "基于应用程序的部署环境执行所有优化。"
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProfileGuidedOptimizationsFlags
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags.None
  id: None
  parent: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  langs:
  - csharp
  name: None
  nameWithType: ProfileGuidedOptimizationsFlags.None
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "不执行任何优化根据应用程序的部署环境。"
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProfileGuidedOptimizationsFlags
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags.All
  parent: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  isExternal: false
  name: All
  nameWithType: ProfileGuidedOptimizationsFlags.All
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags.All
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  parent: System.Web.Configuration
  isExternal: false
  name: ProfileGuidedOptimizationsFlags
  nameWithType: ProfileGuidedOptimizationsFlags
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags
- uid: System.Web.Configuration.ProfileGuidedOptimizationsFlags.None
  parent: System.Web.Configuration.ProfileGuidedOptimizationsFlags
  isExternal: false
  name: None
  nameWithType: ProfileGuidedOptimizationsFlags.None
  fullName: System.Web.Configuration.ProfileGuidedOptimizationsFlags.None
