### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  id: PeerApplicationRegistrationType
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  - System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  langs:
  - csharp
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  type: Enum
  summary: "指定要进行注册的类型<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;></xref>或<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;></xref>注册。"
  remarks: "注册<xref:System.Net.PeerToPeer.Collaboration.PeerApplication>使它能够接收<xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>邀请请求。</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration> </xref:System.Net.PeerToPeer.Collaboration.PeerApplication> 服务或执行注册的应用程序必须有权这样做，因为它需要访问<xref:System.Net.PeerToPeer.Collaboration.ContactManager>和其他资源，如用户、 应用程序和远程计算机上的服务。</xref:System.Net.PeerToPeer.Collaboration.ContactManager>"
  syntax:
    content: public enum PeerApplicationRegistrationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  id: AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>或<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerObject&quot;></xref>要注册的应用程序主机的所有对等节点"
  syntax:
    content: AllUsers
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  id: CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  langs:
  - csharp
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  type: Field
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "仅为与调用的对等方关联的用户注册的应用程序或对象"
  syntax:
    content: CurrentUser
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: AllUsers
  nameWithType: PeerApplicationRegistrationType.AllUsers
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.AllUsers
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplicationRegistrationType
  nameWithType: PeerApplicationRegistrationType
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType
  isExternal: false
  name: CurrentUser
  nameWithType: PeerApplicationRegistrationType.CurrentUser
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationRegistrationType.CurrentUser
