### YamlMime:ManagedReference
items:
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  id: SettingsSavedEventArgs
  children:
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  - System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  langs:
  - csharp
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  type: Class
  summary: "提供有关数据<xref href=&quot;System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved&quot;></xref>事件。"
  remarks: "<xref:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved?displayProperty=fullName>事件发生在设置提供程序访问设置服务之后，即使未成功保存设置。</xref:System.Web.ClientServices.Providers.ClientSettingsProvider.SettingsSaved?displayProperty=fullName> 提供程序可能无法保存设置，其中一个原因是当前用户如果已注销。 你可以使用<xref:System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList%2A>属性来确定是否已成功未保存任何设置。</xref:System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList%2A>       如果设置提供程序无法访问设置服务，而是导致要引发一种<xref:System.Net.WebException>。</xref:System.Net.WebException>的提供程序不会发生此事件       有关处理事件的详细信息，请参阅[NIB︰ 使用事件](http://msdn.microsoft.com/en-us/01e4f1bc-e55e-413f-98c7-6588493e5f67)。"
  example:
  - "The following example code demonstrates how to use this class to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/visualbasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/csharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: 'public class SettingsSavedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  id: '#ctor(System.Collections.Generic.IEnumerable{System.String})'
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "初始化的新实例<xref href=&quot;System.Web.ClientServices.Providers.SettingsSavedEventArgs&quot;></xref>类。"
  syntax:
    content: public SettingsSavedEventArgs (System.Collections.Generic.IEnumerable<string> failedSettingsList);
    parameters:
    - id: failedSettingsList
      type: System.Collections.Generic.IEnumerable{System.String}
      description: "设置提供程序无法保存设置。"
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  id: FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  langs:
  - csharp
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ClientServices.Providers
  summary: "获取设置<xref href=&quot;System.Web.ClientServices.Providers.ClientSettingsProvider&quot;></xref>无法保存到服务器。"
  remarks: "提供程序可能无法保存设置，其中一个原因是当前用户如果已注销。 FailedSettingsList 属性可用于确定是否已成功未保存任何设置。"
  example:
  - "The following example code demonstrates how to use this property to display a list of settings that were not successfully saved.  \n  \n [!code-vb[ClientApplicationServices#304](~/add/codesnippet/visualbasic/ClientAppServicesDemo/Class1.vb#304)]\n [!code-cs[ClientApplicationServices#304](~/add/codesnippet/csharp/ClientAppServicesDemo/Class1.cs#304)]"
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> FailedSettingsList { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "未保存的设置。"
  overload: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor(System.Collections.Generic.IEnumerable{System.String})
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs(IEnumerable<String>)
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.SettingsSavedEventArgs(IEnumerable<String>)
- uid: System.Collections.Generic.IEnumerable{System.String}
  parent: System.Collections.Generic
  isExternal: true
  name: IEnumerable<String>
  nameWithType: IEnumerable<String>
  fullName: System.Collections.Generic.IEnumerable<System.String>
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
  fullName: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.#ctor*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: SettingsSavedEventArgs
  nameWithType: SettingsSavedEventArgs.SettingsSavedEventArgs
- uid: System.Web.ClientServices.Providers.SettingsSavedEventArgs.FailedSettingsList*
  parent: System.Web.ClientServices.Providers.SettingsSavedEventArgs
  isExternal: false
  name: FailedSettingsList
  nameWithType: SettingsSavedEventArgs.FailedSettingsList
