### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  id: ByteStreamMessageEncodingElement
  children:
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.#ctor
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties
  - System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas
  langs:
  - csharp
  name: ByteStreamMessageEncodingElement
  nameWithType: ByteStreamMessageEncodingElement
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  type: Class
  summary: "启用配置元素定义字节流消息编码元素的设置的构造。"
  syntax:
    content: 'public sealed class ByteStreamMessageEncodingElement : System.ServiceModel.Configuration.BindingElementExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BindingElementExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: ByteStreamMessageEncodingElement()
  nameWithType: ByteStreamMessageEncodingElement.ByteStreamMessageEncodingElement()
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ByteStreamMessageEncodingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.ByteStreamMessageEncodingElement&quot;></xref>类。"
  syntax:
    content: public ByteStreamMessageEncodingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  id: ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: ApplyConfiguration(BindingElement)
  nameWithType: ByteStreamMessageEncodingElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "将指定的绑定元素的内容应用到当前<xref href=&quot;System.ServiceModel.Configuration.ByteStreamMessageEncodingElement&quot;></xref>对象。"
  syntax:
    content: public override void ApplyConfiguration (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "绑定元素的设置是要应用到此配置元素。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType
  id: BindingElementType
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: BindingElementType
  nameWithType: ByteStreamMessageEncodingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "获取的类型<xref href=&quot;System.ServiceModel.Channels.ByteStreamMessageEncodingBindingElement&quot;> </xref>。"
  syntax:
    content: public override Type BindingElementType { get; }
    return:
      type: System.Type
      description: "配置元素类型。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ByteStreamMessageEncodingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "将指定的配置节的内容复制到当前<xref href=&quot;System.ServiceModel.Configuration.ByteStreamMessageEncodingElement&quot;></xref>对象。"
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "所复制的内容。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement
  id: CreateBindingElement
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: CreateBindingElement()
  nameWithType: ByteStreamMessageEncodingElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement()
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.ServiceModel.Channels.BindingElement CreateBindingElement ();
    parameters: []
    return:
      type: System.ServiceModel.Channels.BindingElement
      description: "要添加。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  id: InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: InitializeFrom(BindingElement)
  nameWithType: ByteStreamMessageEncodingElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom(BindingElement)
  type: Method
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override void InitializeFrom (System.ServiceModel.Channels.BindingElement bindingElement);
    parameters:
    - id: bindingElement
      type: System.ServiceModel.Channels.BindingElement
      description: "要添加。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: Properties
  nameWithType: ByteStreamMessageEncodingElement.Properties
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas
  id: ReaderQuotas
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  langs:
  - csharp
  name: ReaderQuotas
  nameWithType: ByteStreamMessageEncodingElement.ReaderQuotas
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas
  type: Property
  assemblies:
  - System.ServiceModel.Channels
  namespace: System.ServiceModel.Configuration
  summary: "获取<xref href=&quot;System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement&quot;></xref>定义可由配置了此编码的终结点处理的 SOAP 消息的复杂性约束的配置元素。"
  syntax:
    content: public System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement ReaderQuotas { get; }
    return:
      type: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
      description: "一个配置元素。"
  overload: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BindingElementExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BindingElementExtensionElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.#ctor
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ByteStreamMessageEncodingElement()
  nameWithType: ByteStreamMessageEncodingElement.ByteStreamMessageEncodingElement()
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ByteStreamMessageEncodingElement()
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ApplyConfiguration(BindingElement)
  nameWithType: ByteStreamMessageEncodingElement.ApplyConfiguration(BindingElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration(BindingElement)
- uid: System.ServiceModel.Channels.BindingElement
  parent: System.ServiceModel.Channels
  isExternal: true
  name: BindingElement
  nameWithType: BindingElement
  fullName: System.ServiceModel.Channels.BindingElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: BindingElementType
  nameWithType: ByteStreamMessageEncodingElement.BindingElementType
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: ByteStreamMessageEncodingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: CreateBindingElement()
  nameWithType: ByteStreamMessageEncodingElement.CreateBindingElement()
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement()
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom(System.ServiceModel.Channels.BindingElement)
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: InitializeFrom(BindingElement)
  nameWithType: ByteStreamMessageEncodingElement.InitializeFrom(BindingElement)
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom(BindingElement)
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: Properties
  nameWithType: ByteStreamMessageEncodingElement.Properties
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ReaderQuotas
  nameWithType: ByteStreamMessageEncodingElement.ReaderQuotas
  fullName: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas
- uid: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: XmlDictionaryReaderQuotasElement
  nameWithType: XmlDictionaryReaderQuotasElement
  fullName: System.ServiceModel.Configuration.XmlDictionaryReaderQuotasElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.#ctor*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ByteStreamMessageEncodingElement
  nameWithType: ByteStreamMessageEncodingElement.ByteStreamMessageEncodingElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: ByteStreamMessageEncodingElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.BindingElementType*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: BindingElementType
  nameWithType: ByteStreamMessageEncodingElement.BindingElementType
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CopyFrom*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: CopyFrom
  nameWithType: ByteStreamMessageEncodingElement.CopyFrom
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.CreateBindingElement*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: CreateBindingElement
  nameWithType: ByteStreamMessageEncodingElement.CreateBindingElement
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: InitializeFrom
  nameWithType: ByteStreamMessageEncodingElement.InitializeFrom
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.Properties*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: Properties
  nameWithType: ByteStreamMessageEncodingElement.Properties
- uid: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement.ReaderQuotas*
  parent: System.ServiceModel.Configuration.ByteStreamMessageEncodingElement
  isExternal: false
  name: ReaderQuotas
  nameWithType: ByteStreamMessageEncodingElement.ReaderQuotas
