### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpHandlerAction
  id: HttpHandlerAction
  children:
  - System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String)
  - System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String,System.Boolean)
  - System.Web.Configuration.HttpHandlerAction.Path
  - System.Web.Configuration.HttpHandlerAction.Properties
  - System.Web.Configuration.HttpHandlerAction.Type
  - System.Web.Configuration.HttpHandlerAction.Validate
  - System.Web.Configuration.HttpHandlerAction.Verb
  langs:
  - csharp
  name: HttpHandlerAction
  nameWithType: HttpHandlerAction
  fullName: System.Web.Configuration.HttpHandlerAction
  type: Class
  summary: "配置<xref href=&quot;System.Web.Configuration.HttpHandlersSection&quot;></xref>配置节。 此类不能被继承。"
  remarks: "The HttpHandlerAction class provides a way to programmatically access and modify the `add` element of the `httpHandlers` configuration section.  \n  \n This type is part of a group that includes the <xref:System.Web.Configuration.HttpHandlerActionCollection> and the <xref:System.Web.Configuration.HttpHandlersSection> types.  \n  \n> [!NOTE]\n>  The HttpHandlerAction can read and write information from and to the related section of the configuration file according to the section property <xref:System.Configuration.SectionInformation.AllowDefinition%2A> whose value is <xref:System.Configuration.ConfigurationAllowDefinition>.  \n  \n ASP.NET searches for the handler assembly DLL in the application's private \\bin directory first, and then it searches in the system assembly cache."
  example:
  - "The following code example shows how to use the <xref:System.Web.Configuration.HttpModuleAction> type.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#2](~/add/codesnippet/csharp/t-system.web.configurati_22_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#2](~/add/codesnippet/visualbasic/t-system.web.configurati_22_1.vb)]  \n  \n The following configuration excerpt shows how to specify values declaratively for the `httpHandlers` section.  \n  \n```  \n<httpHandlers>  \n  <add path=\"Calculator.custom\"  \n    type=\"Samples.Aspnet.SystemWebConfiguration.Calculator, CalculatorHandler\"  \n    verb=\"GET\" validate=\"false\" />  \n</httpHandlers>   \n```"
  syntax:
    content: 'public sealed class HttpHandlerAction : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String)
  id: '#ctor(System.String,System.String,System.String)'
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: HttpHandlerAction(String,String,String)
  nameWithType: HttpHandlerAction.HttpHandlerAction(String,String,String)
  fullName: System.Web.Configuration.HttpHandlerAction.HttpHandlerAction(String,String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>类使用传递的参数。"
  remarks: "HttpHandlerAction 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.HttpHandlerAction>类通过<xref:System.Web.Configuration.HttpHandlersSection.Handlers%2A>属性。</xref:System.Web.Configuration.HttpHandlersSection.Handlers%2A> </xref:System.Web.Configuration.HttpHandlerAction>"
  syntax:
    content: public HttpHandlerAction (string path, string type, string verb);
    parameters:
    - id: path
      type: System.String
      description: "<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;> </xref> URL 路径。"
    - id: type
      type: System.String
      description: "以逗号分隔的类/程序集组合组成版本、 区域性和公钥标记。"
    - id: verb
      type: System.String
      description: "以逗号分隔 （例如，&quot;GET、 PUT、 POST&quot;） 的 HTTP 谓词的列表。"
  overload: System.Web.Configuration.HttpHandlerAction.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String,System.Boolean)
  id: '#ctor(System.String,System.String,System.String,System.Boolean)'
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: HttpHandlerAction(String,String,String,Boolean)
  nameWithType: HttpHandlerAction.HttpHandlerAction(String,String,String,Boolean)
  fullName: System.Web.Configuration.HttpHandlerAction.HttpHandlerAction(String,String,String,Boolean)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>类使用传递的参数。"
  remarks: "HttpHandlerAction 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.HttpHandlerAction>类通过<xref:System.Web.Configuration.HttpHandlersSection.Handlers%2A>属性。</xref:System.Web.Configuration.HttpHandlersSection.Handlers%2A> </xref:System.Web.Configuration.HttpHandlerAction>"
  example:
  - "The following code example shows how to create an <xref:System.Web.Configuration.HttpHandlerAction> object.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#3](~/add/codesnippet/csharp/94056c28-bc95-494d-84db-_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#3](~/add/codesnippet/visualbasic/94056c28-bc95-494d-84db-_1.vb)]"
  syntax:
    content: public HttpHandlerAction (string path, string type, string verb, bool validate);
    parameters:
    - id: path
      type: System.String
      description: "<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;> </xref> URL 路径。"
    - id: type
      type: System.String
      description: "以逗号分隔的类/程序集组合组成版本、 区域性和公钥标记。"
    - id: verb
      type: System.String
      description: "以逗号分隔 （例如，&quot;GET、 PUT、 POST&quot;） 的 HTTP 谓词的列表。"
    - id: validate
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要允许验证，则为否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 如果<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>，ASP.NET 将不尝试加载类，直到实际匹配的请求，可能会延迟错误但改进了启动时间。"
  overload: System.Web.Configuration.HttpHandlerAction.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.Path
  id: Path
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: Path
  nameWithType: HttpHandlerAction.Path
  fullName: System.Web.Configuration.HttpHandlerAction.Path
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>路径。"
  remarks: "路径属性可以包含单一 URL 或通配符字符串。"
  example:
  - "The following code example shows how to access the Path property.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#5](~/add/codesnippet/csharp/p-system.web.configurati_236_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#5](~/add/codesnippet/visualbasic/p-system.web.configurati_236_1.vb)]"
  syntax:
    content: public string Path { get; set; }
    return:
      type: System.String
      description: "<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;> </xref> URL 路径。"
  overload: System.Web.Configuration.HttpHandlerAction.Path*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.Properties
  id: Properties
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: Properties
  nameWithType: HttpHandlerAction.Properties
  fullName: System.Web.Configuration.HttpHandlerAction.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.HttpHandlerAction.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.Type
  id: Type
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: Type
  nameWithType: HttpHandlerAction.Type
  fullName: System.Web.Configuration.HttpHandlerAction.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>类型。"
  remarks: "The Type property is a comma-separated class/assembly combination consisting of version, culture, and public-key tokens.  \n  \n> [!NOTE]\n>  ASP.NET searches for the handler assembly DLL in the application's private \\bin directory first, and then it searches in the system assembly cache."
  example:
  - "The following code example shows how to access the Type property.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#6](~/add/codesnippet/csharp/p-system.web.configurati_281_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#6](~/add/codesnippet/visualbasic/p-system.web.configurati_281_1.vb)]"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "The <xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref> type."
  overload: System.Web.Configuration.HttpHandlerAction.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.Validate
  id: Validate
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: Validate
  nameWithType: HttpHandlerAction.Validate
  fullName: System.Web.Configuration.HttpHandlerAction.Validate
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>验证。"
  remarks: "如果验证属性为`false`，ASP.NET 将不尝试加载类，直到实际匹配的请求，可能会延迟错误但改进了启动时间。"
  example:
  - "The following code example shows how to access the Validate property.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#8](~/add/codesnippet/csharp/p-system.web.configurati_128_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#8](~/add/codesnippet/visualbasic/p-system.web.configurati_128_1.vb)]"
  syntax:
    content: public bool Validate { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果允许验证;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.HttpHandlerAction.Validate*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpHandlerAction.Verb
  id: Verb
  parent: System.Web.Configuration.HttpHandlerAction
  langs:
  - csharp
  name: Verb
  nameWithType: HttpHandlerAction.Verb
  fullName: System.Web.Configuration.HttpHandlerAction.Verb
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置所允许的谓词<xref href=&quot;System.Web.Configuration.HttpHandlerAction&quot;></xref>对象。"
  remarks: "此谓词属性可以是 HTTP 谓词 （例如，&quot;GET、 PUT、 POST&quot;） 的逗号分隔列表。"
  example:
  - "The following code example shows how to access the Verb property.  \n  \n [!code-cs[System.Web.Configuration.HttpHandlers#7](~/add/codesnippet/csharp/p-system.web.configurati_301_1.cs)]\n [!code-vb[System.Web.Configuration.HttpHandlers#7](~/add/codesnippet/visualbasic/p-system.web.configurati_301_1.vb)]"
  syntax:
    content: public string Verb { get; set; }
    return:
      type: System.String
      description: "所允许的对象的谓词。"
  overload: System.Web.Configuration.HttpHandlerAction.Verb*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String)
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: HttpHandlerAction(String,String,String)
  nameWithType: HttpHandlerAction.HttpHandlerAction(String,String,String)
  fullName: System.Web.Configuration.HttpHandlerAction.HttpHandlerAction(String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.HttpHandlerAction.#ctor(System.String,System.String,System.String,System.Boolean)
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: HttpHandlerAction(String,String,String,Boolean)
  nameWithType: HttpHandlerAction.HttpHandlerAction(String,String,String,Boolean)
  fullName: System.Web.Configuration.HttpHandlerAction.HttpHandlerAction(String,String,String,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.HttpHandlerAction.Path
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Path
  nameWithType: HttpHandlerAction.Path
  fullName: System.Web.Configuration.HttpHandlerAction.Path
- uid: System.Web.Configuration.HttpHandlerAction.Properties
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Properties
  nameWithType: HttpHandlerAction.Properties
  fullName: System.Web.Configuration.HttpHandlerAction.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.HttpHandlerAction.Type
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Type
  nameWithType: HttpHandlerAction.Type
  fullName: System.Web.Configuration.HttpHandlerAction.Type
- uid: System.Web.Configuration.HttpHandlerAction.Validate
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Validate
  nameWithType: HttpHandlerAction.Validate
  fullName: System.Web.Configuration.HttpHandlerAction.Validate
- uid: System.Web.Configuration.HttpHandlerAction.Verb
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Verb
  nameWithType: HttpHandlerAction.Verb
  fullName: System.Web.Configuration.HttpHandlerAction.Verb
- uid: System.Web.Configuration.HttpHandlerAction.#ctor*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: HttpHandlerAction
  nameWithType: HttpHandlerAction.HttpHandlerAction
- uid: System.Web.Configuration.HttpHandlerAction.Path*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Path
  nameWithType: HttpHandlerAction.Path
- uid: System.Web.Configuration.HttpHandlerAction.Properties*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Properties
  nameWithType: HttpHandlerAction.Properties
- uid: System.Web.Configuration.HttpHandlerAction.Type*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Type
  nameWithType: HttpHandlerAction.Type
- uid: System.Web.Configuration.HttpHandlerAction.Validate*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Validate
  nameWithType: HttpHandlerAction.Validate
- uid: System.Web.Configuration.HttpHandlerAction.Verb*
  parent: System.Web.Configuration.HttpHandlerAction
  isExternal: false
  name: Verb
  nameWithType: HttpHandlerAction.Verb
