### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  id: FormsAuthPasswordFormat
  children:
  - System.Web.Configuration.FormsAuthPasswordFormat.Clear
  - System.Web.Configuration.FormsAuthPasswordFormat.MD5
  - System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  langs:
  - csharp
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
  type: Enum
  summary: "定义的加密格式存储密码。"
  remarks: "若要以编程方式配置用于 Web 应用程序中存储密码的加密类型，请使用<xref:System.Web.Configuration.AuthenticationSection>类。</xref:System.Web.Configuration.AuthenticationSection> 此类还内部使用<xref:System.Web.Security.FormsAuthentication>在处理身份验证票证。</xref:System.Web.Security.FormsAuthentication>"
  example:
  - "The following code example shows how to use the FormsAuthPasswordFormat enumeration. Refer to the code example in the <xref:System.Web.Configuration.FormsAuthenticationUserCollection> class topic to learn how to get the collection.  \n  \n [!code-vb[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/visualbasic/t-system.web.configurati_88_1.vb)]\n [!code-cs[System.Web.Configuration.FormsAuthenticationCredentials#3](~/add/codesnippet/csharp/t-system.web.configurati_88_1.cs)]"
  syntax:
    content: public enum FormsAuthPasswordFormat
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  id: Clear
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: Clear
  nameWithType: FormsAuthPasswordFormat.Clear
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定密码未加密。 此字段为常数。"
  syntax:
    content: Clear
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  id: MD5
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: MD5
  nameWithType: FormsAuthPasswordFormat.MD5
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定的使用 MD5 哈希算法对密码进行加密。 此字段为常数。"
  syntax:
    content: MD5
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  id: SHA1
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  langs:
  - csharp
  name: SHA1
  nameWithType: FormsAuthPasswordFormat.SHA1
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定的使用 SHA1 哈希算法对密码进行加密。 此字段为常数。"
  syntax:
    content: SHA1
    return:
      type: System.Web.Configuration.FormsAuthPasswordFormat
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FormsAuthPasswordFormat.Clear
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: Clear
  nameWithType: FormsAuthPasswordFormat.Clear
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.Clear
- uid: System.Web.Configuration.FormsAuthPasswordFormat
  parent: System.Web.Configuration
  isExternal: false
  name: FormsAuthPasswordFormat
  nameWithType: FormsAuthPasswordFormat
  fullName: System.Web.Configuration.FormsAuthPasswordFormat
- uid: System.Web.Configuration.FormsAuthPasswordFormat.MD5
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: MD5
  nameWithType: FormsAuthPasswordFormat.MD5
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.MD5
- uid: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
  parent: System.Web.Configuration.FormsAuthPasswordFormat
  isExternal: false
  name: SHA1
  nameWithType: FormsAuthPasswordFormat.SHA1
  fullName: System.Web.Configuration.FormsAuthPasswordFormat.SHA1
