### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TicketCompatibilityMode
  id: TicketCompatibilityMode
  children:
  - System.Web.Configuration.TicketCompatibilityMode.Framework20
  - System.Web.Configuration.TicketCompatibilityMode.Framework40
  langs:
  - csharp
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
  type: Enum
  summary: "定义是否对窗体身份验证的票证到期日期使用协调世界时 (UTC) 还是本地时间。"
  remarks: "可以通过使用协调世界时 (UTC) 或本地时间存储 ASP.NET 窗体身份验证的票证到期日期。 有关应用程序之间的兼容性和.NET Framework 的不同版本之间的兼容性，可以通过使用指定的票证过期时间`ticketCompatilityMode`元素的特性。 默认值为`ticketCompatibilityMode`属性是 Framework20。"
  example:
  - "The following example configures the forms authentication ticket expiration date as UTC time.  \n  \n```  \n<system.web>  \n  <authentication mode=\"Forms\">   \n    <forms ticketCompatilityMode=\"Framework40\">  \n    </forms>  \n  </authentication>  \n</system.web>  \n```"
  syntax:
    content: public enum TicketCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定为本地时间存储票证到期日期。 此为默认值。"
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "指定为 UTC 存储票证到期日期。"
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
- uid: System.Web.Configuration.TicketCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
