### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  id: ProfileElement
  children:
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  - System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  langs:
  - csharp
  name: ProfileElement
  nameWithType: ProfileElement
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  type: Class
  summary: "表示一个配置元素<xref href=&quot;System.Activities.Tracking.TrackingProfile&quot;></xref>和用于添加通过行为元素的配置文件。"
  syntax:
    content: 'public class ProfileElement : System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement.GetStringPairKey(System.String,System.String)
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;></xref>类。"
  syntax:
    content: public ProfileElement ();
    parameters: []
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  id: ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "获取一个用于唯一标识配置文件键。"
  syntax:
    content: public override object ElementKey { get; }
    return:
      type: System.Object
      description: "元素键。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  id: ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "获取或设置跟踪配置文件的可见性模式。"
  remarks: "构成活动实现的活动跟踪记录可以筛选使用<xref:System.Activities.Tracking.ImplementationVisibility>.</xref:System.Activities.Tracking.ImplementationVisibility>所描述的可见性模式 此标志用于订阅跟踪记录的所有活动还是仅为可见的根工作流中的活动。       如果将标志设置为<xref:System.Activities.Tracking.ImplementationVisibility>，跟踪仅根活动及其实现。</xref:System.Activities.Tracking.ImplementationVisibility> 如果该实现包含活动是复合活动，而不是其实现跟踪复合活动。       有关详细信息，请参阅<xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>。</xref:System.Activities.Tracking.TrackingProfile.ImplementationVisibility%2A>"
  syntax:
    content: public System.Activities.Tracking.ImplementationVisibility ImplementationVisibility { get; set; }
    return:
      type: System.Activities.Tracking.ImplementationVisibility
      description: "跟踪配置文件的可见性模式"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  id: Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "获取或设置跟踪配置文件的名称。"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "跟踪配置文件的名称。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  id: Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "获取<xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;></xref>包含与此元素关联的属性。"
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "属性集合中。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  id: Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  langs:
  - csharp
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities.Tracking.Configuration
  summary: "获取的集合<xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement&quot;></xref>与此关联的元素<xref href=&quot;System.ServiceModel.Activities.Tracking.Configuration.ProfileElement&quot;> </xref>。"
  remarks: "还有一个<xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>每个工作流配置文件中。</xref:System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElement>"
  syntax:
    content: public System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection Workflows { get; }
    return:
      type: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
      description: "配置文件工作流查询元素的集合。"
  overload: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
  isExternal: false
  name: System.ServiceModel.Activities.Tracking.Configuration.TrackingConfigurationElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement()
  nameWithType: ProfileElement.ProfileElement()
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ProfileElement()
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility
- uid: System.Activities.Tracking.ImplementationVisibility
  parent: System.Activities.Tracking
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ImplementationVisibility
  fullName: System.Activities.Tracking.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
  parent: System.ServiceModel.Activities.Tracking.Configuration
  isExternal: false
  name: ProfileWorkflowElementCollection
  nameWithType: ProfileWorkflowElementCollection
  fullName: System.ServiceModel.Activities.Tracking.Configuration.ProfileWorkflowElementCollection
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.#ctor*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ProfileElement
  nameWithType: ProfileElement.ProfileElement
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ElementKey*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ElementKey
  nameWithType: ProfileElement.ElementKey
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.ImplementationVisibility*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: ImplementationVisibility
  nameWithType: ProfileElement.ImplementationVisibility
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Name*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Name
  nameWithType: ProfileElement.Name
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Properties*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Properties
  nameWithType: ProfileElement.Properties
- uid: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement.Workflows*
  parent: System.ServiceModel.Activities.Tracking.Configuration.ProfileElement
  isExternal: false
  name: Workflows
  nameWithType: ProfileElement.Workflows
