### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata
  id: ProfilePropertyMetadata
  children:
  - System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  - System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  - System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  - System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  - System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  - System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  - System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  - System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  langs:
  - csharp
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata
  type: Class
  summary: "提供的值，用于描述配置文件属性的集合。"
  remarks: "ProfilePropertyMetadata 类用于检索有关配置文件属性的信息，当<xref:System.Web.ApplicationServices.ProfileService>类</xref:System.Web.ApplicationServices.ProfileService>通过访问配置文件 你可以检索的名称和类型的属性，无论它是只读的无论它可由尚未验证，用户和默认值。 应用程序可以采取相应的措施基于这些值，例如不会尝试设置只读属性。       若要从使用 Windows Communication Framework (WCF) 兼容的应用程序访问 ProfilePropertyMetadata 对象，请使用<xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A>方法的<xref:System.Web.ApplicationServices.ProfileService>类。</xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.ProfileService.GetPropertiesMetadata%2A> 用户不必登录才能检索 ProfilePropertyMetadata 对象，因为配置文件属性的元数据并不特定于用户的配置文件属性值。       ProfilePropertyMetadata 类中的将值设置的部分元素中的 Web.config 文件中定义的属性时。"
  syntax:
    content: >-
      [System.Runtime.Serialization.DataContract]

      public class ProfilePropertyMetadata : System.Runtime.Serialization.IExtensibleDataObject
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.IExtensibleDataObject
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "初始化的新实例<xref href=&quot;System.Web.ApplicationServices.ProfilePropertyMetadata&quot;></xref>类。"
  syntax:
    content: public ProfilePropertyMetadata ();
    parameters: []
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  id: AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置一个值，该值指示属性是否可供未经身份验证的用户。"
  remarks: "启用匿名标识，与在元素中的设置时，可以设置哪些配置文件属性可供匿名用户。 定义的属性时，可以在 Web.config 文件的部分元素中设置 AllowAnonymousAccess 属性。 从客户端应用程序，使用 AllowAnonymousAccess 属性以确定是否可以为匿名用户设置的配置文件属性。"
  syntax:
    content: public bool AllowAnonymousAccess { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果属性是可供未经身份验证的用户;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  id: DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置该属性的默认值。"
  remarks: "DefaultValue 属性的序列化的格式确定<xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>属性的<xref:System.Web.ApplicationServices.ProfilePropertyMetadata>类。</xref:System.Web.ApplicationServices.ProfilePropertyMetadata> </xref:System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs%2A>"
  syntax:
    content: public string DefaultValue { get; set; }
    return:
      type: System.String
      description: "如果在 Web.config 文件中; 中定义默认值，则属性的默认值序列化表示形式否则为字符串&quot;(null)&quot;。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  id: ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置一个引用， <xref href=&quot;System.Runtime.Serialization.ExtensionDataObject&quot;> </xref>实例。"
  syntax:
    content: public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
    return:
      type: System.Runtime.Serialization.ExtensionDataObject
      description: "对将扩展的数据存储在反序列化操作期间的对象的引用。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  id: IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置一个值，指示配置文件属性是只读的。"
  remarks: "定义的属性时，可以在 Web.config 文件的部分元素中设置的 IsReadOnly 属性。"
  syntax:
    content: public bool IsReadOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果配置文件属性是只读的;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  id: PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置配置文件属性的名称。"
  remarks: "定义的属性时，可以在 Web.config 文件的部分元素中设置 PropertyName 属性。"
  syntax:
    content: public string PropertyName { get; set; }
    return:
      type: System.String
      description: "在 Web.config 文件中定义的配置文件属性名称。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  id: SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置一个值，指示如何序列化的属性值。"
  remarks: "定义的属性时，可以在 Web.config 文件的部分元素中设置 SerializeAs 属性。"
  syntax:
    content: public int SerializeAs { get; set; }
    return:
      type: System.Int32
      description: "枚举值。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  id: TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  langs:
  - csharp
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "获取或设置配置文件属性类型的程序集限定名称。"
  remarks: "定义的属性时，可以在 Web.config 文件的部分元素中设置此 TypeName 属性。"
  syntax:
    content: public string TypeName { get; set; }
    return:
      type: System.String
      description: "配置文件属性类型的程序集限定名称。"
  overload: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata()
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata()
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ProfilePropertyMetadata()
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData
- uid: System.Runtime.Serialization.ExtensionDataObject
  parent: System.Runtime.Serialization
  isExternal: false
  name: ExtensionDataObject
  nameWithType: ExtensionDataObject
  fullName: System.Runtime.Serialization.ExtensionDataObject
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
  fullName: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.#ctor*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ProfilePropertyMetadata
  nameWithType: ProfilePropertyMetadata.ProfilePropertyMetadata
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.AllowAnonymousAccess*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: AllowAnonymousAccess
  nameWithType: ProfilePropertyMetadata.AllowAnonymousAccess
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.DefaultValue*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: DefaultValue
  nameWithType: ProfilePropertyMetadata.DefaultValue
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.ExtensionData*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: ExtensionData
  nameWithType: ProfilePropertyMetadata.ExtensionData
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.IsReadOnly*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: IsReadOnly
  nameWithType: ProfilePropertyMetadata.IsReadOnly
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.PropertyName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: PropertyName
  nameWithType: ProfilePropertyMetadata.PropertyName
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.SerializeAs*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: SerializeAs
  nameWithType: ProfilePropertyMetadata.SerializeAs
- uid: System.Web.ApplicationServices.ProfilePropertyMetadata.TypeName*
  parent: System.Web.ApplicationServices.ProfilePropertyMetadata
  isExternal: false
  name: TypeName
  nameWithType: ProfilePropertyMetadata.TypeName
