### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement
  id: TcpTransportSecurityElement
  children:
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  - System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  langs:
  - csharp
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement
  type: Class
  summary: "一个 XML 元素定义 TcpTransport 绑定的安全设置。 此类不能被继承。"
  syntax:
    content: 'public sealed class TcpTransportSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.TcpTransportSecurityElement&quot;></xref>类。"
  syntax:
    content: public TcpTransportSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  id: ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取和设置的用于身份验证的客户端凭据类型。"
  syntax:
    content: public System.ServiceModel.TcpClientCredentialType ClientCredentialType { get; set; }
    return:
      type: System.ServiceModel.TcpClientCredentialType
      description: "A <xref:System.ServiceModel.TcpClientCredentialType>，指定的用于身份验证的客户端凭据类型。</xref:System.ServiceModel.TcpClientCredentialType>"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  id: ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取<xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></xref>实例，其中包含的配置设置要用于扩展用于会话的保护。"
  syntax:
    content: public System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement ExtendedProtectionPolicy { get; }
    return:
      type: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
      description: "Returns <xref href=&quot;System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement&quot;></xref>."
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置一个值，定义命名管道级别的消息级别安全。"
  remarks: "对消息进行签名可以降低第三方时正在被传输消息篡改的风险。 加密可以在传输过程中提供数据级保密。"
  syntax:
    content: public System.Net.Security.ProtectionLevel ProtectionLevel { get; set; }
    return:
      type: System.Net.Security.ProtectionLevel
      description: "A<xref:System.ServiceModel.TcpTransportSecurity.ProtectionLevel*>值，该值定义消息级别安全保护级别的命名管道。</xref:System.ServiceModel.TcpTransportSecurity.ProtectionLevel*>"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  id: SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  langs:
  - csharp
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: '获取使用 TcpClientCredentialType.Certificate 的客户端凭据类型时要协商的 SSL/TLS 协议的列表。 该值可以为一个或多个下列枚举成员的组合︰ Ssl3、 Tls、 Tls11、 Tls12。'
  remarks: "默认值是 Ssl3 |Tls |Tls11 |Tls12。 4.6 之前的 framework 版本仅支持 Ssl3 和 Tls。 如果它们不包括在内，将不可能与早期版本的 framework 的通信。 指定 Tls11 和/或 Tls12 将禁用 Ssl3 的使用情况，即使它已包含。"
  syntax:
    content: public System.Security.Authentication.SslProtocols SslProtocols { get; }
    return:
      type: System.Security.Authentication.SslProtocols
      description: "SSL/TLS 协议的列表。"
  overload: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement()
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement()
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.TcpTransportSecurityElement()
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.TcpClientCredentialType
  parent: System.ServiceModel
  isExternal: true
  name: TcpClientCredentialType
  nameWithType: TcpClientCredentialType
  fullName: System.ServiceModel.TcpClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
  parent: System.Security.Authentication.ExtendedProtection.Configuration
  isExternal: false
  name: ExtendedProtectionPolicyElement
  nameWithType: ExtendedProtectionPolicyElement
  fullName: System.Security.Authentication.ExtendedProtection.Configuration.ExtendedProtectionPolicyElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel
- uid: System.Net.Security.ProtectionLevel
  parent: System.Net.Security
  isExternal: false
  name: ProtectionLevel
  nameWithType: ProtectionLevel
  fullName: System.Net.Security.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
  fullName: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols
- uid: System.Security.Authentication.SslProtocols
  parent: System.Security.Authentication
  isExternal: true
  name: SslProtocols
  nameWithType: SslProtocols
  fullName: System.Security.Authentication.SslProtocols
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: TcpTransportSecurityElement
  nameWithType: TcpTransportSecurityElement.TcpTransportSecurityElement
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ClientCredentialType*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ClientCredentialType
  nameWithType: TcpTransportSecurityElement.ClientCredentialType
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ExtendedProtectionPolicy*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ExtendedProtectionPolicy
  nameWithType: TcpTransportSecurityElement.ExtendedProtectionPolicy
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: Properties
  nameWithType: TcpTransportSecurityElement.Properties
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.ProtectionLevel*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: ProtectionLevel
  nameWithType: TcpTransportSecurityElement.ProtectionLevel
- uid: System.ServiceModel.Configuration.TcpTransportSecurityElement.SslProtocols*
  parent: System.ServiceModel.Configuration.TcpTransportSecurityElement
  isExternal: false
  name: SslProtocols
  nameWithType: TcpTransportSecurityElement.SslProtocols
