### YamlMime:ManagedReference
items:
- uid: System.Configuration.CallbackValidatorAttribute
  id: CallbackValidatorAttribute
  children:
  - System.Configuration.CallbackValidatorAttribute.#ctor
  - System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  - System.Configuration.CallbackValidatorAttribute.Type
  - System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute
  fullName: System.Configuration.CallbackValidatorAttribute
  type: Class
  summary: "指定<xref href=&quot;System.Configuration.CallbackValidator&quot;></xref>用于进行代码验证的对象。 此类不能被继承。"
  remarks: "CallbackValidatorAttribute 特性类提供之间的关联<xref:System.Configuration.CallbackValidator>对象和要验证的代码。</xref:System.Configuration.CallbackValidator> CallbackValidatorAttribute 类派生自<xref:System.Configuration.ConfigurationValidatorAttribute>类。</xref:System.Configuration.ConfigurationValidatorAttribute>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class CallbackValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Configuration.CallbackValidatorAttribute&quot;></xref>类。"
  syntax:
    content: public CallbackValidatorAttribute ();
    parameters: []
  overload: System.Configuration.CallbackValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  id: CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取或设置的回调方法的名称。"
  syntax:
    content: public string CallbackMethodName { get; set; }
    return:
      type: System.String
      description: "要调用的方法的名称。"
  overload: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.Type
  id: Type
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取或设置的验证程序类型。"
  syntax:
    content: public Type Type { get; set; }
    return:
      type: System.Type
      description: "<xref:System.Type>当前的验证程序属性实例。</xref:System.Type>"
  overload: System.Configuration.CallbackValidatorAttribute.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取验证程序实例。"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "当前<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;></xref>实例。"
  overload: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "值<xref:System.Configuration.CallbackValidatorAttribute.Type*>属性是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>。</xref:System.Configuration.CallbackValidatorAttribute.Type*>"
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>属性未设置为具有一个对象参数的公共静态 void 方法。</xref:System.Configuration.CallbackValidatorAttribute.CallbackMethodName*>"
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.CallbackValidatorAttribute.#ctor
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute()
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute()
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackValidatorAttribute()
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
  fullName: System.Configuration.CallbackValidatorAttribute.CallbackMethodName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.CallbackValidatorAttribute.Type
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
  fullName: System.Configuration.CallbackValidatorAttribute.Type
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.CallbackValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.CallbackValidatorAttribute.#ctor*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackValidatorAttribute
  nameWithType: CallbackValidatorAttribute.CallbackValidatorAttribute
- uid: System.Configuration.CallbackValidatorAttribute.CallbackMethodName*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: CallbackMethodName
  nameWithType: CallbackValidatorAttribute.CallbackMethodName
- uid: System.Configuration.CallbackValidatorAttribute.Type*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: Type
  nameWithType: CallbackValidatorAttribute.Type
- uid: System.Configuration.CallbackValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.CallbackValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: CallbackValidatorAttribute.ValidatorInstance
