### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.InvalidDeploymentException
  id: InvalidDeploymentException
  children:
  - System.Deployment.Application.InvalidDeploymentException.#ctor
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException
  fullName: System.Deployment.Application.InvalidDeploymentException
  type: Class
  summary: "指示[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]无法读取的部署或应用程序清单。"
  remarks: "InvalidDeploymentException 指示损坏部署或应用程序清单中的是否存在[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]应用程序。 因为清单格式不正确，具有无法识别的元素对于其架构，或者具有不匹配的数字签名，则可能发生该错误。       你会更容易如果使用文本编辑器手动编辑部署或应用程序清单文件已损坏。 你通常可以更正此问题，重新生成你[!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)]部署，将创建新的部署和应用程序清单。 有关更详细的调试步骤，请参阅以下链接。"
  syntax:
    content: 'public class InvalidDeploymentException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新实例<xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;></xref>类。"
  syntax:
    content: public InvalidDeploymentException ();
    parameters: []
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新实例<xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;></xref>与指定的描述异常的消息的类。"
  syntax:
    content: public InvalidDeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: "描述异常的消息。 此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。"
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新实例<xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;></xref>类。"
  syntax:
    content: protected InvalidDeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "承载序列化的对象数据的对象。"
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "有关源或目标的上下文信息。"
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "初始化的新实例<xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;></xref>类。"
  syntax:
    content: public InvalidDeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "描述异常的消息。 此构造函数的调用方需要确保此字符串已针对当前系统区域性进行了本地化。"
    - id: innerException
      type: System.Exception
      description: "导致当前异常的异常。 如果`innerException`参数不是<xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>中, 引发当前异常<xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;></xref>处理内部异常的块。"
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor*
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException.InvalidDeploymentException
