### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  id: ChannelPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  - System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties
  langs:
  - csharp
  name: ChannelPoolSettingsElement
  nameWithType: ChannelPoolSettingsElement
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  type: Class
  summary: "定义自定义绑定的通道池设置。 此类不能被继承。"
  syntax:
    content: 'public sealed class ChannelPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  langs:
  - csharp
  name: ChannelPoolSettingsElement()
  nameWithType: ChannelPoolSettingsElement.ChannelPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.ChannelPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.ChannelPoolSettingsElement&quot;></xref>类。"
  syntax:
    content: public ChannelPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ChannelPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ChannelPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置的最长时间连接可以在断开前空闲。"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "一个值为正<xref:System.TimeSpan>，指定连接在断开前可以保持空闲的最大时间。</xref:System.TimeSpan> 默认值为 00:02:00。"
  overload: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: ChannelPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置之后关闭活动连接的时间。 默认值为 00:05:00。"
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>，指定的时间之后关闭活动连接。</xref:System.TimeSpan> 默认值为 00:05:00。"
  overload: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  id: MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置由服务启动的远程终结点的最大通道数。"
  syntax:
    content: public int MaxOutboundChannelsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "最大到由服务启动的远程终结点的通道数。"
  overload: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: ChannelPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: ChannelPoolSettingsElement()
  nameWithType: ChannelPoolSettingsElement.ChannelPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.ChannelPoolSettingsElement()
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ChannelPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: ChannelPoolSettingsElement
  nameWithType: ChannelPoolSettingsElement.ChannelPoolSettingsElement
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: ChannelPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: ChannelPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint*
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: MaxOutboundChannelsPerEndpoint
  nameWithType: ChannelPoolSettingsElement.MaxOutboundChannelsPerEndpoint
- uid: System.ServiceModel.Configuration.ChannelPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.ChannelPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: ChannelPoolSettingsElement.Properties
