### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceSection
  id: XhtmlConformanceSection
  children:
  - System.Web.Configuration.XhtmlConformanceSection.#ctor
  - System.Web.Configuration.XhtmlConformanceSection.Mode
  - System.Web.Configuration.XhtmlConformanceSection.Properties
  langs:
  - csharp
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection
  fullName: System.Web.Configuration.XhtmlConformanceSection
  type: Class
  summary: "配置<xref uid=&quot;langword_csharp_xhtmlConformance&quot; name=&quot;xhtmlConformance&quot; href=&quot;&quot;></xref>部分。 此类不能被继承。"
  remarks: "XhtmlConformanceSection 类使您能够以编程方式访问和修改`xhtmlConformance`配置文件节。      1> [!NOTE] 1> ASP.NET，可创建符合 XHTML 1.1 标准的网页。 有关 XHTML 1.1 标准的详细信息，请参阅 W3C 站点。 默认情况下，当你使用的浏览器支持 HTML 4.0 或更高版本，ASP.NET 页面和控件呈现兼容 XHTML 1.0 Transitional 标准的标记。 但是，某些情况下，您可能不希望 ASP.NET XHTML 标记呈现。 如果您的现有依赖于标记或特性时，通常将禁止的 XHTML 的页面，也是通常如此。"
  syntax:
    content: 'public sealed class XhtmlConformanceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.XhtmlConformanceSection&quot;></xref>类使用默认参数。"
  remarks: "XhtmlConformanceSection 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.XhtmlConformanceSection>类通过<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.XhtmlConformanceSection>"
  syntax:
    content: public XhtmlConformanceSection ();
    parameters: []
  overload: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  id: Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置模式属性。"
  remarks: "默认情况下，当你使用的浏览器支持 HTML 4.0 或更高版本，ASP.NET 页面和控件呈现兼容 XHTML 1.0 Transitional 标准的标记。 但是，某些情况下，您可能不希望 ASP.NET XHTML 标记呈现。 如果您的现有依赖于标记或特性时，通常将禁止的 XHTML 的页面，也是通常如此。"
  syntax:
    content: public System.Web.Configuration.XhtmlConformanceMode Mode { get; set; }
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "之一<xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;></xref>值。 默认值是<xref href=&quot;System.Web.Configuration.XhtmlConformanceMode&quot;> </xref>。"
  overload: System.Web.Configuration.XhtmlConformanceSection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  id: Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  langs:
  - csharp
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.XhtmlConformanceSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection()
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection()
  fullName: System.Web.Configuration.XhtmlConformanceSection.XhtmlConformanceSection()
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
  fullName: System.Web.Configuration.XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
  fullName: System.Web.Configuration.XhtmlConformanceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.XhtmlConformanceSection.#ctor*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: XhtmlConformanceSection
  nameWithType: XhtmlConformanceSection.XhtmlConformanceSection
- uid: System.Web.Configuration.XhtmlConformanceSection.Mode*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Mode
  nameWithType: XhtmlConformanceSection.Mode
- uid: System.Web.Configuration.XhtmlConformanceSection.Properties*
  parent: System.Web.Configuration.XhtmlConformanceSection
  isExternal: false
  name: Properties
  nameWithType: XhtmlConformanceSection.Properties
