### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.PartialTrustVisibleAssembly
  id: PartialTrustVisibleAssembly
  children:
  - System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  - System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  - System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  - System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  langs:
  - csharp
  name: PartialTrustVisibleAssembly
  nameWithType: PartialTrustVisibleAssembly
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly
  type: Class
  summary: "配置部分信任程序集。 此类不能被继承。"
  remarks: "PartialTrustVisibleAssembly 配置标记程序集与部分受信任调用方属性 (APTCA) 在部分信任 ASP.NET 应用程序中使用。 有关详细信息，请参阅<xref:System.Security.AllowPartiallyTrustedCallersAttribute>。</xref:System.Security.AllowPartiallyTrustedCallersAttribute>"
  syntax:
    content: 'public sealed class PartialTrustVisibleAssembly : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: PartialTrustVisibleAssembly(String,String)
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.PartialTrustVisibleAssembly&quot;></xref>类。"
  syntax:
    content: public PartialTrustVisibleAssembly (string assemblyName, string publicKey);
    parameters:
    - id: assemblyName
      type: System.String
      description: "程序集名称。"
    - id: publicKey
      type: System.String
      description: "十六进制字符串表示形式与程序集关联的公钥。"
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  id: AssemblyName
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置程序集名称。"
  syntax:
    content: public string AssemblyName { get; set; }
    return:
      type: System.String
      description: "程序集名称。"
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  id: Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  id: PublicKey
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  langs:
  - csharp
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取或设置程序集的公钥。"
  syntax:
    content: public string PublicKey { get; set; }
    return:
      type: System.String
      description: "十六进制字符串表示形式与程序集关联的公钥。"
  overload: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor(System.String,System.String)
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PartialTrustVisibleAssembly(String,String)
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PartialTrustVisibleAssembly(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
  fullName: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.#ctor*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PartialTrustVisibleAssembly
  nameWithType: PartialTrustVisibleAssembly.PartialTrustVisibleAssembly
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.AssemblyName*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: AssemblyName
  nameWithType: PartialTrustVisibleAssembly.AssemblyName
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.Properties*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: Properties
  nameWithType: PartialTrustVisibleAssembly.Properties
- uid: System.Web.Configuration.PartialTrustVisibleAssembly.PublicKey*
  parent: System.Web.Configuration.PartialTrustVisibleAssembly
  isExternal: false
  name: PublicKey
  nameWithType: PartialTrustVisibleAssembly.PublicKey
