### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  id: TransportConfigurationTypeElement
  children:
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String)
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String,System.String)
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties
  - System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType
  langs:
  - csharp
  name: TransportConfigurationTypeElement
  nameWithType: TransportConfigurationTypeElement
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  type: Class
  summary: "一个标识特定传输的类型的 XML 元素。"
  syntax:
    content: 'public sealed class TransportConfigurationTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: TransportConfigurationTypeElement()
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement()
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.TransportConfigurationTypeElement&quot;></xref>类。"
  syntax:
    content: public TransportConfigurationTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: TransportConfigurationTypeElement(String)
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement(String)
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.TransportConfigurationTypeElement&quot;></xref>具有唯一名称的类。"
  syntax:
    content: public TransportConfigurationTypeElement (string name);
    parameters:
    - id: name
      type: System.String
      description: "一个字符串，唯一标识传输类型。"
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>name</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: TransportConfigurationTypeElement(String,String)
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement(String,String)
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement(String,String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.TransportConfigurationTypeElement&quot;></xref>与唯一的名称和实现特定传输的类型的类。"
  syntax:
    content: public TransportConfigurationTypeElement (string name, string transportConfigurationTypeName);
    parameters:
    - id: name
      type: System.String
      description: "一个字符串，唯一标识传输类型。"
    - id: transportConfigurationTypeName
      type: System.String
      description: "实现特定传输的类型。"
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>name</code>or <code>transportConfigurationTypeName</code> is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: Name
  nameWithType: TransportConfigurationTypeElement.Name
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置用于唯一标识传输类型的名称。"
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "唯一标识传输类型的名称。"
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: TransportConfigurationTypeElement.Properties
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType
  id: TransportConfigurationType
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  langs:
  - csharp
  name: TransportConfigurationType
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationType
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置一个字符串，包含实现特定传输的类型。"
  syntax:
    content: public string TransportConfigurationType { get; set; }
    return:
      type: System.String
      description: "实现特定传输的类型。"
  overload: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationTypeElement()
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement()
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement()
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationTypeElement(String)
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement(String)
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor(System.String,System.String)
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationTypeElement(String,String)
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement(String,String)
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationTypeElement(String,String)
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: Name
  nameWithType: TransportConfigurationTypeElement.Name
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: Properties
  nameWithType: TransportConfigurationTypeElement.Properties
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationType
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationType
  fullName: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationTypeElement
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationTypeElement
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Name*
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: Name
  nameWithType: TransportConfigurationTypeElement.Name
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.Properties*
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: Properties
  nameWithType: TransportConfigurationTypeElement.Properties
- uid: System.ServiceModel.Configuration.TransportConfigurationTypeElement.TransportConfigurationType*
  parent: System.ServiceModel.Configuration.TransportConfigurationTypeElement
  isExternal: false
  name: TransportConfigurationType
  nameWithType: TransportConfigurationTypeElement.TransportConfigurationType
