### YamlMime:ManagedReference
items:
- uid: System.Xml.Schema.XmlSchemaCompilationSettings
  id: XmlSchemaCompilationSettings
  children:
  - System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  - System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  langs:
  - csharp
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings
  type: Class
  summary: "提供有关的架构编译选项<xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;></xref>此类不能被继承的类。"
  remarks: "XmlSchemaCompilationSettings 类提供<xref:System.Xml.Schema.XmlSchemaSet>类</xref:System.Xml.Schema.XmlSchemaSet>的架构编译选项 例如，<xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>属性指定<xref:System.Xml.Schema.XmlSchemaSet>应检查唯一粒子归属 (UPA) 冲突时中的架构<xref:System.Xml.Schema.XmlSchemaSet>进行编译。</xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaSet> </xref:System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck%2A>"
  syntax:
    content: public sealed class XmlSchemaCompilationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  id: '#ctor'
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  type: Constructor
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "初始化的新实例<xref href=&quot;System.Xml.Schema.XmlSchemaCompilationSettings&quot;></xref>类。"
  syntax:
    content: public XmlSchemaCompilationSettings ();
    parameters: []
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  id: EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  langs:
  - csharp
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  type: Property
  assemblies:
  - System.Xml
  namespace: System.Xml.Schema
  summary: "获取或设置一个值，该值指示是否<xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;></xref>应检查唯一粒子归属 (UPA) 冲突。"
  remarks: "当 EnableUpaCheck 属性设置为`false`，将根据下列规则执行验证。      1.  如果没有选择一个强类型和通配符，<xref:System.Xml.Schema.XmlSchemaSet>会选取的强类型的粒子，如下面的架构和 Xml 示例中所示。</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:any namespace=&quot;##any&quot;/>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `</xs:sequence>`在下面的 Xml，`A`元素将与关联`<xs:element name=&quot;A&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`架构中。       `<A>some text</A>`      1.  如果两个强类型化元素之间没有选择<xref:System.Xml.Schema.XmlSchemaSet>会选取第一个。</xref:System.Xml.Schema.XmlSchemaSet>       `<xs:sequence>`       `<xs:element name=&quot;A&quot; type=&quot;xs:string&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`       `<xs:element name=&quot;B&quot; type=&quot;xs:string&quot;/>`       `</xs:sequence>`在下面的 Xml，`B`元素将与关联`<xs:element name=&quot;B&quot; type=&quot;xs:string&quot; minOccurs=&quot;0&quot;/>`架构中。       `<A/>`       `<B/>`"
  syntax:
    content: public bool EnableUpaCheck { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果<xref href=&quot;System.Xml.Schema.XmlSchemaSet&quot;></xref>应检查唯一粒子归属 (UPA) 冲突; 否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings()
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.XmlSchemaCompilationSettings()
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
  fullName: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.#ctor*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: XmlSchemaCompilationSettings
  nameWithType: XmlSchemaCompilationSettings.XmlSchemaCompilationSettings
- uid: System.Xml.Schema.XmlSchemaCompilationSettings.EnableUpaCheck*
  parent: System.Xml.Schema.XmlSchemaCompilationSettings
  isExternal: false
  name: EnableUpaCheck
  nameWithType: XmlSchemaCompilationSettings.EnableUpaCheck
