### YamlMime:ManagedReference
items:
- uid: System.Drawing.Configuration.SystemDrawingSection
  id: SystemDrawingSection
  children:
  - System.Drawing.Configuration.SystemDrawingSection.#ctor
  - System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  - System.Drawing.Configuration.SystemDrawingSection.Properties
  langs:
  - csharp
  name: SystemDrawingSection
  nameWithType: SystemDrawingSection
  fullName: System.Drawing.Configuration.SystemDrawingSection
  type: Class
  summary: "表示一个配置节中的类使用<xref href=&quot;System.Drawing&quot;></xref>命名空间。"
  syntax:
    content: 'public sealed class SystemDrawingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor
  id: '#ctor'
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: SystemDrawingSection()
  nameWithType: SystemDrawingSection.SystemDrawingSection()
  fullName: System.Drawing.Configuration.SystemDrawingSection.SystemDrawingSection()
  type: Constructor
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Drawing.Configuration.SystemDrawingSection&quot;></xref>类。"
  syntax:
    content: public SystemDrawingSection ();
    parameters: []
  overload: System.Drawing.Configuration.SystemDrawingSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  id: BitmapSuffix
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
  fullName: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  summary: "获取或设置要附加到指示的文件名称的后缀<xref href=&quot;System.Drawing.ToolboxBitmapAttribute&quot;></xref>程序集使用的声明时<xref href=&quot;System.Drawing.BitmapSuffixInSameAssemblyAttribute&quot;></xref>或<xref href=&quot;System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute&quot;> </xref>。"
  remarks: "位图后缀将追加到扩展名之前的文件名称。 例如，使用位图后缀&quot;。 test.1.0&quot;即<xref:System.Drawing.ToolboxBitmapAttribute>对&quot;my.bmp&quot;的引用将解释为&quot;my.test.1.0.bmp&quot;。</xref:System.Drawing.ToolboxBitmapAttribute>"
  syntax:
    content: public string BitmapSuffix { get; set; }
    return:
      type: System.String
      description: "位图后缀。"
  overload: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix*
  exceptions: []
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties
  id: Properties
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: Properties
  nameWithType: SystemDrawingSection.Properties
  fullName: System.Drawing.Configuration.SystemDrawingSection.Properties
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Drawing.Configuration.SystemDrawingSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: SystemDrawingSection()
  nameWithType: SystemDrawingSection.SystemDrawingSection()
  fullName: System.Drawing.Configuration.SystemDrawingSection.SystemDrawingSection()
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
  fullName: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: Properties
  nameWithType: SystemDrawingSection.Properties
  fullName: System.Drawing.Configuration.SystemDrawingSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: SystemDrawingSection
  nameWithType: SystemDrawingSection.SystemDrawingSection
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: Properties
  nameWithType: SystemDrawingSection.Properties
