### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocationCollection
  id: ConfigurationLocationCollection
  children:
  - System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  langs:
  - csharp
  name: ConfigurationLocationCollection
  nameWithType: ConfigurationLocationCollection
  fullName: System.Configuration.ConfigurationLocationCollection
  type: Class
  summary: "包含的 ConfigurationLocationCollection 对象的集合。"
  remarks: "ConfigurationLocationCollection 类用于循环访问集合的<xref:System.Configuration.ConfigurationLocation>对象，表示为其定义特定于位置的配置设置的资源。</xref:System.Configuration.ConfigurationLocation> ConfigurationLocationCollection 是返回类型<xref:System.Configuration.Configuration.Locations%2A>属性。</xref:System.Configuration.Configuration.Locations%2A>      1> [!NOTE]&1;> ConfigurationLocationCollection 类可能不引用的集合<xref:System.Configuration.ConfigurationLocation>它们在配置文件中指定的顺序中的对象。</xref:System.Configuration.ConfigurationLocation>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and the locations defined in this configuration are displayed by iterating through the ConfigurationLocationCollection object returned by the <xref:System.Configuration.Configuration.Locations%2A> property.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_1_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_1_1.cs)]"
  syntax:
    content: 'public class ConfigurationLocationCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取<xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;></xref>的指定索引处的对象。"
  remarks: "使用项的访问器<xref:System.Configuration.ConfigurationLocationCollection>类，以获取特定<xref:System.Configuration.ConfigurationLocation>通过指定集合中的其索引的集合中对象。</xref:System.Configuration.ConfigurationLocation> </xref:System.Configuration.ConfigurationLocationCollection>"
  syntax:
    content: public System.Configuration.ConfigurationLocation this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "索引位置<xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;></xref>返回。"
    return:
      type: System.Configuration.ConfigurationLocation
      description: "<xref href=&quot;System.Configuration.ConfigurationLocationCollection&quot;> </xref>的指定索引处。"
  overload: System.Configuration.ConfigurationLocationCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.Configuration.ConfigurationLocationCollection.Item(System.Int32)
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ConfigurationLocationCollection.Item(Int32)
  fullName: System.Configuration.ConfigurationLocationCollection.Item(Int32)
- uid: System.Configuration.ConfigurationLocation
  parent: System.Configuration
  isExternal: false
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.ConfigurationLocationCollection.Item*
  parent: System.Configuration.ConfigurationLocationCollection
  isExternal: false
  name: Item
  nameWithType: ConfigurationLocationCollection.Item
