### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsManageability
  id: SettingsManageability
  children:
  - System.Configuration.SettingsManageability.Roaming
  langs:
  - csharp
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
  type: Enum
  summary: "提供值来指示哪些服务应将提供给应用程序设置。"
  remarks: "Ttribute 用于应用单个应用程序设置属性和属性组，以指示要为其提供特殊的预定义的服务。 SettingsManageability 枚举列出可用的服务。 大多数这些服务将由 Windows 操作系统提供。"
  syntax:
    content: public enum SettingsManageability
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SettingsManageability.Roaming
  id: Roaming
  parent: System.Configuration.SettingsManageability
  langs:
  - csharp
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "使应用程序设置存储在漫游用户配置文件。 有关漫游用户配置文件的详细信息，请参阅[独立存储和漫游](http://msdn.microsoft.com/en-us/d3cca593-4521-408d-b323-ea398d226de3)。"
  syntax:
    content: Roaming
    return:
      type: System.Configuration.SettingsManageability
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SettingsManageability.Roaming
  parent: System.Configuration.SettingsManageability
  isExternal: false
  name: Roaming
  nameWithType: SettingsManageability.Roaming
  fullName: System.Configuration.SettingsManageability.Roaming
- uid: System.Configuration.SettingsManageability
  parent: System.Configuration
  isExternal: false
  name: SettingsManageability
  nameWithType: SettingsManageability
  fullName: System.Configuration.SettingsManageability
