### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  id: XmlFormatExtensionPrefixAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  - System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  type: Class
  summary: "指定的 XML 命名空间和 XML 命名空间前缀，用于在服务说明的服务说明格式扩展。 此类不能被继承。"
  remarks: "服务说明格式扩展扩展如何为使用 ASP.NET 创建的 XML Web 服务生成服务说明。 具体而言，服务说明格式扩展将 XML 元素添加到服务说明。 SOAP 扩展生成的 XML Web 服务的客户端和服务器端运行因为有关 SOAP 扩展的信息将不会置于的服务说明时，这非常有用。 如果你将有关 SOAP 扩展的信息添加到服务说明时，客户端可以解释它必须运行特定的 SOAP 扩展。 必须在客户端和服务器运行的 SOAP 扩展的一个示例是加密 SOAP 扩展。 如果只在服务器上运行加密 SOAP 扩展并将返回值将其发送回客户端之前对其加密时，客户端必须运行才能解密该 SOAP 消息的 SOAP 扩展。 否则，客户端无法处理的返回值。       使用以下步骤生成服务说明格式扩展︰ 1。  生成从<xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>派生的类      2.  应用<xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>到类并指定应从该处运行的服务说明格式扩展的扩展点。</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  根据需要应用<xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>到类并指定的类中作为新的扩展点的成员。</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute>      4.  （可选） 将 XmlFormatExtensionPrefixAttribute 应用于类并指定要使用的生成的服务说明格式扩展的 XML 元素关联的 XML 命名空间前缀。      5.  配置要在中运行的服务说明格式扩展`serviceDescriptionFormatExtensionTypes`配置文件节。"
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_2_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_2_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class, AllowMultiple=true)]

      public sealed class XmlFormatExtensionPrefixAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;></xref>类。"
  syntax:
    content: public XmlFormatExtensionPrefixAttribute ();
    parameters: []
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute&quot;></xref>类，设置的 XML 命名空间和服务说明格式扩展的 XML 命名空间前缀。"
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/31a2fbe2-95e2-473f-8282-_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/31a2fbe2-95e2-473f-8282-_1.vb)]
  syntax:
    content: public XmlFormatExtensionPrefixAttribute (string prefix, string ns);
    parameters:
    - id: prefix
      type: System.String
      description: "与服务说明格式扩展关联的 XML 命名空间前缀。"
    - id: ns
      type: System.String
      description: "服务说明格式扩展关联的 XML 命名空间。"
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  id: Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "获取或设置与服务说明格式扩展关联的 XML 命名空间。"
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_4_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_4_1.vb)]
  syntax:
    content: public string Namespace { get; set; }
    return:
      type: System.String
      description: "服务说明格式扩展关联的 XML 命名空间。"
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  id: Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  langs:
  - csharp
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "获取或设置与服务说明格式扩展关联的 XML 命名空间前缀。"
  remarks: ''
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#2](~/add/codesnippet/csharp/p-system.web.services.co_0_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#2](~/add/codesnippet/visualbasic/p-system.web.services.co_0_1.vb)]
  syntax:
    content: public string Prefix { get; set; }
    return:
      type: System.String
      description: "与服务说明格式扩展关联的 XML 命名空间前缀。"
  overload: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute()
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute()
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor(System.String,System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute(String,String)
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: XmlFormatExtensionPrefixAttribute
  nameWithType: XmlFormatExtensionPrefixAttribute.XmlFormatExtensionPrefixAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Namespace*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Namespace
  nameWithType: XmlFormatExtensionPrefixAttribute.Namespace
- uid: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute.Prefix*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute
  isExternal: false
  name: Prefix
  nameWithType: XmlFormatExtensionPrefixAttribute.Prefix
