### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection
  id: ScriptingAuthenticationServiceSection
  children:
  - System.Web.Configuration.ScriptingAuthenticationServiceSection.#ctor
  - System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled
  - System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties
  - System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL
  langs:
  - csharp
  name: ScriptingAuthenticationServiceSection
  nameWithType: ScriptingAuthenticationServiceSection
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection
  type: Class
  summary: "表示用于身份验证服务设置配置节。 此类不能被继承。"
  remarks: "ScriptingAuthenticationServiceSection 类使你能够以编程方式访问和修改`authenticationService`元素的配置节，用于在 ASP.NET 中使用 AJAX 功能。       启用 AJAX 的应用程序的身份验证服务仅适用于基于窗体的身份验证使用 cookie 来交换用户信息。 有关窗体身份验证的详细信息，请参阅[与 Microsoft Ajax 一起使用 Forms 身份验证](~/add/includes/ajax-current-ext-md.md)。"
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the ScriptingAuthenticationServiceSection class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <authenticationService enabled=\"true\" requireSSL=\"false\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access ScriptingAuthenticationServiceSection programmatically.  \n  \n [!code-cs[System.Web.Configuration#1](~/add/codesnippet/csharp/t-system.web.configurati_20_1.cs)]\n [!code-vb[System.Web.Configuration#1](~/add/codesnippet/visualbasic/t-system.web.configurati_20_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingAuthenticationServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  langs:
  - csharp
  name: ScriptingAuthenticationServiceSection()
  nameWithType: ScriptingAuthenticationServiceSection.ScriptingAuthenticationServiceSection()
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.ScriptingAuthenticationServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.ScriptingAuthenticationServiceSection&quot;></xref>类。"
  syntax:
    content: public ScriptingAuthenticationServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingAuthenticationServiceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingAuthenticationServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值指示是否为使用 ASP.NET AJAX 功能的应用程序启用身份验证服务。"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果启用了身份验证服务;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingAuthenticationServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL
  id: RequireSSL
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  langs:
  - csharp
  name: RequireSSL
  nameWithType: ScriptingAuthenticationServiceSection.RequireSSL
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "获取或设置一个值，该值指示身份验证服务是否需要 SSL 保护的连接。"
  syntax:
    content: public bool RequireSSL { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果身份验证服务需要安全套接字层 (SSL);否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: ScriptingAuthenticationServiceSection()
  nameWithType: ScriptingAuthenticationServiceSection.ScriptingAuthenticationServiceSection()
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.ScriptingAuthenticationServiceSection()
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingAuthenticationServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingAuthenticationServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: RequireSSL
  nameWithType: ScriptingAuthenticationServiceSection.RequireSSL
  fullName: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: ScriptingAuthenticationServiceSection
  nameWithType: ScriptingAuthenticationServiceSection.ScriptingAuthenticationServiceSection
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingAuthenticationServiceSection.Enabled
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingAuthenticationServiceSection.Properties
- uid: System.Web.Configuration.ScriptingAuthenticationServiceSection.RequireSSL*
  parent: System.Web.Configuration.ScriptingAuthenticationServiceSection
  isExternal: false
  name: RequireSSL
  nameWithType: ScriptingAuthenticationServiceSection.RequireSSL
