### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.WsiProfilesElement
  id: WsiProfilesElement
  children:
  - System.Web.Services.Configuration.WsiProfilesElement.#ctor
  - System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  - System.Web.Services.Configuration.WsiProfilesElement.Name
  - System.Web.Services.Configuration.WsiProfilesElement.Properties
  langs:
  - csharp
  name: WsiProfilesElement
  nameWithType: WsiProfilesElement
  fullName: System.Web.Services.Configuration.WsiProfilesElement
  type: Class
  summary: "表示<xref uid=&quot;langword_csharp_WsiProfiles&quot; name=&quot;WsiProfiles&quot; href=&quot;&quot;></xref>配置文件中的元素。"
  remarks: "WsiProfiles 元素描述 Web 服务声明，使其符合所 Web 服务互操作性 (WSI) 规范。"
  syntax:
    content: 'public sealed class WsiProfilesElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor
  id: '#ctor'
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: WsiProfilesElement()
  nameWithType: WsiProfilesElement.WsiProfilesElement()
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement()
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化与类的实例<xref href=&quot;System.Web.Services.Configuration.WsiProfilesElement&quot;></xref>类。"
  syntax:
    content: public WsiProfilesElement ();
    parameters: []
  overload: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  id: '#ctor(System.Web.Services.WsiProfiles)'
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: WsiProfilesElement(WsiProfiles)
  nameWithType: WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "初始化与类的实例<xref href=&quot;System.Web.Services.Configuration.WsiProfilesElement&quot;></xref>类，使用指定<xref href=&quot;System.Web.Services.WsiProfiles&quot;></xref>枚举值。"
  syntax:
    content: public WsiProfilesElement (System.Web.Services.WsiProfiles name);
    parameters:
    - id: name
      type: System.Web.Services.WsiProfiles
      description: "A <xref href=&quot;System.Web.Services.WsiProfiles&quot;> </xref>对象，它指定 Web 服务是否符合 WSI 基本配置文件版本 1.1。"
  overload: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name
  id: Name
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: Name
  nameWithType: WsiProfilesElement.Name
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Name
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "获取或设置是否符合 WSI 基本配置文件版本 1.1 的 Web 服务。"
  syntax:
    content: public System.Web.Services.WsiProfiles Name { get; set; }
    return:
      type: System.Web.Services.WsiProfiles
      description: "A <xref href=&quot;System.Web.Services.WsiProfiles&quot;> </xref>对象，它指定 Web 服务是否符合 WSI 基本配置文件版本 1.1。"
  overload: System.Web.Services.Configuration.WsiProfilesElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties
  id: Properties
  parent: System.Web.Services.Configuration.WsiProfilesElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsiProfilesElement.Properties
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Properties
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Services.Configuration.WsiProfilesElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement()
  nameWithType: WsiProfilesElement.WsiProfilesElement()
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement()
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor(System.Web.Services.WsiProfiles)
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement(WsiProfiles)
  nameWithType: WsiProfilesElement.WsiProfilesElement(WsiProfiles)
  fullName: System.Web.Services.Configuration.WsiProfilesElement.WsiProfilesElement(WsiProfiles)
- uid: System.Web.Services.WsiProfiles
  parent: System.Web.Services
  isExternal: false
  name: WsiProfiles
  nameWithType: WsiProfiles
  fullName: System.Web.Services.WsiProfiles
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Name
  nameWithType: WsiProfilesElement.Name
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Name
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Properties
  nameWithType: WsiProfilesElement.Properties
  fullName: System.Web.Services.Configuration.WsiProfilesElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Services.Configuration.WsiProfilesElement.#ctor*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: WsiProfilesElement
  nameWithType: WsiProfilesElement.WsiProfilesElement
- uid: System.Web.Services.Configuration.WsiProfilesElement.Name*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Name
  nameWithType: WsiProfilesElement.Name
- uid: System.Web.Services.Configuration.WsiProfilesElement.Properties*
  parent: System.Web.Services.Configuration.WsiProfilesElement
  isExternal: false
  name: Properties
  nameWithType: WsiProfilesElement.Properties
