### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute
  id: ApplicationAccessControlAttribute
  children:
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  - System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  - System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  - System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  - System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  langs:
  - csharp
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute
  type: Class
  summary: "指定包含的程序集的访问控制<xref href=&quot;System.EnterpriseServices.ServicedComponent&quot;></xref>类。"
  remarks: "在.NET Framework 1.1 版中，如果此属性不存在在程序集中，默认情况下启用 COM + 安全配置。 这是从.NET Framework 1.0 版的行为发生变化。"
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/t-system.enterpriseservi_25_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/t-system.enterpriseservi_25_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/t-system.enterpriseservi_25_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationAccessControlAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "初始化的新实例<xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;></xref>类，并启用 COM + 安全配置。"
  remarks: ''
  example:
  - "The following code example demonstrates the use of this attribute to control access to an assembly containing <xref:System.EnterpriseServices.ServicedComponent> classes.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/m-system.enterpriseservi_23_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/m-system.enterpriseservi_23_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/m-system.enterpriseservi_23_1.vb)]"
  syntax:
    content: public ApplicationAccessControlAttribute ();
    parameters: []
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "初始化的新实例<xref href=&quot;System.EnterpriseServices.ApplicationAccessControlAttribute&quot;></xref>类并设置<xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>属性，该值指示是否启用 COM 安全配置。</xref:System.EnterpriseServices.ApplicationAccessControlAttribute.Value*>"
  syntax:
    content: public ApplicationAccessControlAttribute (bool val);
    parameters:
    - id: val
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要允许的安全性，则配置否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  id: AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "获取或设置检查级别进程级别或属于组件级别的访问权限。"
  remarks: "仅在 Windows 2000 和更高版本支持此属性。"
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_33_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_33_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_33_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AccessChecksLevelOption AccessChecksLevel { get; set; }
    return:
      type: System.EnterpriseServices.AccessChecksLevelOption
      description: "之一<xref href=&quot;System.EnterpriseServices.AccessChecksLevelOption&quot;></xref>值。"
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  id: Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "获取或设置远程过程调用 (RPC) 身份验证级别。"
  remarks: ''
  example:
  - "The following example illustrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/p-system.enterpriseservi_17_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/p-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/p-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.AuthenticationOption Authentication { get; set; }
    return:
      type: System.EnterpriseServices.AuthenticationOption
      description: "之一<xref href=&quot;System.EnterpriseServices.AuthenticationOption&quot;></xref>值。"
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  id: ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "获取或设置用于调用此应用程序的目标的允许的模拟级别。"
  remarks: "仅在 Windows 2000 和更高版本支持此属性。"
  example:
  - "The following code example demonstrates the use of this property.  \n  \n [!code-cpp[EnterpriseServices_Security#2](~/add/codesnippet/cpp/f57469cf-7d93-405f-ae99-_1.cpp)]\n [!code-cs[EnterpriseServices_Security#2](~/add/codesnippet/csharp/f57469cf-7d93-405f-ae99-_1.cs)]\n [!code-vb[EnterpriseServices_Security#2](~/add/codesnippet/visualbasic/f57469cf-7d93-405f-ae99-_1.vb)]"
  syntax:
    content: public System.EnterpriseServices.ImpersonationLevelOption ImpersonationLevel { get; set; }
    return:
      type: System.EnterpriseServices.ImpersonationLevelOption
      description: "之一<xref href=&quot;System.EnterpriseServices.ImpersonationLevelOption&quot;></xref>值。"
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "获取或设置一个值，该值指示是否启用 COM + 安全配置。"
  syntax:
    content: public bool Value { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果启用了 COM + 安全配置;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute()
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute()
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor(System.Boolean)
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute(Boolean)
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ApplicationAccessControlAttribute(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.AccessChecksLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AccessChecksLevelOption
  nameWithType: AccessChecksLevelOption
  fullName: System.EnterpriseServices.AccessChecksLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.AuthenticationOption
  parent: System.EnterpriseServices
  isExternal: false
  name: AuthenticationOption
  nameWithType: AuthenticationOption
  fullName: System.EnterpriseServices.AuthenticationOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ImpersonationLevelOption
  parent: System.EnterpriseServices
  isExternal: false
  name: ImpersonationLevelOption
  nameWithType: ImpersonationLevelOption
  fullName: System.EnterpriseServices.ImpersonationLevelOption
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
  fullName: System.EnterpriseServices.ApplicationAccessControlAttribute.Value
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ApplicationAccessControlAttribute
  nameWithType: ApplicationAccessControlAttribute.ApplicationAccessControlAttribute
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.AccessChecksLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: AccessChecksLevel
  nameWithType: ApplicationAccessControlAttribute.AccessChecksLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Authentication*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Authentication
  nameWithType: ApplicationAccessControlAttribute.Authentication
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.ImpersonationLevel*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: ImpersonationLevel
  nameWithType: ApplicationAccessControlAttribute.ImpersonationLevel
- uid: System.EnterpriseServices.ApplicationAccessControlAttribute.Value*
  parent: System.EnterpriseServices.ApplicationAccessControlAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationAccessControlAttribute.Value
