### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSetting
  id: SpecialSetting
  children:
  - System.Configuration.SpecialSetting.ConnectionString
  - System.Configuration.SpecialSetting.WebServiceUrl
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
  type: Enum
  summary: "指定应用程序设置属性的特殊设置类别。"
  remarks: "SpecialSetting 枚举定义一组应用于与 ttribute 类应用程序设置属性的特殊类别。      1> [!CAUTION]&1;> 默认设置提供程序， <xref:System.Configuration.LocalFileSettingsProvider>，不会加密或否则保护连接字符串。</xref:System.Configuration.LocalFileSettingsProvider> 简单它将此类型的设置存储在一个单独`<connectionstrings>`相应的配置文件中的部分。"
  syntax:
    content: public enum SpecialSetting
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.ConnectionString
  id: ConnectionString
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "配置属性表示一个连接字符串，通常用于数据存储区或网络资源。"
  syntax:
    content: ConnectionString
    return:
      type: System.Configuration.SpecialSetting
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  id: WebServiceUrl
  parent: System.Configuration.SpecialSetting
  langs:
  - csharp
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
  type: Field
  assemblies:
  - System
  namespace: System.Configuration
  summary: "配置属性表示到 Web 服务的统一资源定位器 (URL)。"
  syntax:
    content: WebServiceUrl
    return:
      type: System.Configuration.SpecialSetting
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.SpecialSetting.ConnectionString
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: ConnectionString
  nameWithType: SpecialSetting.ConnectionString
  fullName: System.Configuration.SpecialSetting.ConnectionString
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSetting.WebServiceUrl
  parent: System.Configuration.SpecialSetting
  isExternal: false
  name: WebServiceUrl
  nameWithType: SpecialSetting.WebServiceUrl
  fullName: System.Configuration.SpecialSetting.WebServiceUrl
