### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFramework
  id: CompatibleFramework
  children:
  - System.Deployment.Application.CompatibleFramework.Profile
  - System.Deployment.Application.CompatibleFramework.SupportedRuntime
  - System.Deployment.Application.CompatibleFramework.TargetVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: System.Deployment.Application.CompatibleFramework
  type: Class
  summary: "表示.NET Framework 应用程序可以在其中安装和运行的版本。"
  syntax:
    content: public class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.Profile
  id: Profile
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "指定应用程序可以在其中安装和运行的.NET Framework 版本的配置文件。"
  remarks: "如果.NET Framework 版本[!INCLUDE[net_client_v40_long](~/add/includes/net-client-v40-long-md.md)]，该配置文件属性返回&quot;客户端&quot;。 如果.NET Framework 版本[!INCLUDE[net_v40_long](~/add/includes/net-v40-long-md.md)]，该配置文件属性返回&quot;Full&quot;。"
  syntax:
    content: public string Profile { get; }
    return:
      type: System.String
      description: "一个字符串，表示配置文件。"
  overload: System.Deployment.Application.CompatibleFramework.Profile*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "指定.NET Framework 应用程序可以在其中安装和运行的运行时版本号。"
  remarks: "新版本的.NET Framework 可以在以前发布的运行时版本上运行。"
  syntax:
    content: public string SupportedRuntime { get; }
    return:
      type: System.String
      description: "一个字符串，表示运行时版本。"
  overload: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  id: TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  langs:
  - csharp
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "指定应用程序可以在其中安装和运行的.NET framework 的版本。"
  syntax:
    content: public string TargetVersion { get; }
    return:
      type: System.String
      description: "一个字符串，表示版本。"
  overload: System.Deployment.Application.CompatibleFramework.TargetVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Deployment.Application.CompatibleFramework.Profile
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: System.Deployment.Application.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: System.Deployment.Application.CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
  fullName: System.Deployment.Application.CompatibleFramework.TargetVersion
- uid: System.Deployment.Application.CompatibleFramework.Profile*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: System.Deployment.Application.CompatibleFramework.SupportedRuntime*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: System.Deployment.Application.CompatibleFramework.TargetVersion*
  parent: System.Deployment.Application.CompatibleFramework
  isExternal: false
  name: TargetVersion
  nameWithType: CompatibleFramework.TargetVersion
