### YamlMime:ManagedReference
items:
- uid: System.Drawing.Printing.QueryPageSettingsEventHandler
  id: QueryPageSettingsEventHandler
  langs:
  - csharp
  name: QueryPageSettingsEventHandler
  nameWithType: QueryPageSettingsEventHandler
  fullName: System.Drawing.Printing.QueryPageSettingsEventHandler
  type: Delegate
  summary: "表示处理的方法<xref href=&quot;System.Drawing.Printing.PrintDocument.QueryPageSettings&quot;></xref>事件<xref href=&quot;System.Drawing.Printing.PrintDocument&quot;> </xref>。"
  remarks: "当创建 QueryPageSettingsEventHandler 委托时，需要标识将处理该事件的方法。 若要将事件与事件处理程序关联，添加到事件的委托的一个实例。 除非移除了该委托，称为每当发生该事件时，事件处理程序。 有关事件处理程序委托的详细信息，请参阅[事件](~/add/includes/ajax-current-ext-md.md)。       有关打印的详细信息，请参阅<xref:System.Drawing.Printing>命名空间概述。</xref:System.Drawing.Printing>"
  syntax:
    content: public delegate void QueryPageSettingsEventHandler(object sender, QueryPageSettingsEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
