### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer
  id: RemoteWebConfigurationHostServer
  children:
  - System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  - System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  - System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  langs:
  - csharp
  name: RemoteWebConfigurationHostServer
  nameWithType: RemoteWebConfigurationHostServer
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer
  type: Class
  summary: "在内部使用运行时以远程支持访问配置数据。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ClassInterface(System.Runtime.InteropServices.ClassInterfaceType.AutoDual)]

      [System.Runtime.InteropServices.ComVisible(true)]

      [System.Runtime.InteropServices.Guid("9FDB6D2C-90EA-4e42-99E6-38B96E28698E")]

      [System.Runtime.InteropServices.ProgId("System.Web.Configuration.RemoteWebConfigurationHostServerV4_32")]

      public class RemoteWebConfigurationHostServer : System.Web.Configuration.IRemoteWebConfigurationHostServer
  inheritance:
  - System.Object
  implements:
  - System.Web.Configuration.IRemoteWebConfigurationHostServer
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: RemoteWebConfigurationHostServer()
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在运行时在内部使用创建的新实例<xref href=&quot;System.Web.Configuration.RemoteWebConfigurationHostServer&quot;> </xref>。"
  syntax:
    content: public RemoteWebConfigurationHostServer ();
    parameters: []
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  id: DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "有条件地加密或对引用的字符串值进行解密<code> xmlString </code>参数。"
  syntax:
    content: public string DoEncryptOrDecrypt (bool doEncrypt, string xmlString, string protectionProviderName, string protectionProviderType, string[] paramKeys, string[] paramValues);
    parameters:
    - id: doEncrypt
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要加密;<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>进行解密。"
    - id: xmlString
      type: System.String
      description: "要加密或解密的 XML。"
    - id: protectionProviderName
      type: System.String
      description: "用于保护的配置数据提供程序。"
    - id: protectionProviderType
      type: System.String
      description: "<xref:System.Type>保护提供程序。</xref:System.Type>"
    - id: paramKeys
      type: System.String[]
      description: "保护提供程序的可选参数的键。"
    - id: paramValues
      type: System.String[]
      description: "保护提供程序的可选参数的值。"
    return:
      type: System.String
      description: "一个字符串，包含的加密或解密值<code> xmlString </code>。"
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>protectionProviderType</code>不是派生自<xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref>。"
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  id: GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetData(String,Boolean,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在内部用于支持对配置数据的远程访问。"
  syntax:
    content: public byte[] GetData (string fileName, bool getReadTimeOnly, out long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "若要访问远程配置文件的路径。"
    - id: getReadTimeOnly
      type: System.Boolean
      description: "一个布尔值，指定是否仅`readTime`返回。"
    - id: readTime
      type: System.Int64
      description: "上次访问文件的时间。"
    return:
      type: System.Byte[]
      description: "<xref uid=&quot;langword_csharp_array&quot; name=&quot;array&quot; href=&quot;&quot;> </xref>的 8 位无符号整数 （字节），其中包含的配置数据。"
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>fileName</code>不指向.config 扩展名的文件。"
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  id: GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取配置文件的详细信息。"
  syntax:
    content: public void GetFileDetails (string name, out bool exists, out long size, out long createDate, out long lastWriteDate);
    parameters:
    - id: name
      type: System.String
      description: "文件的名称。"
    - id: exists
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果该文件存在;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
    - id: size
      type: System.Int64
      description: "文件的大小。"
    - id: createDate
      type: System.Int64
      description: "该文件的创建日期。"
    - id: lastWriteDate
      type: System.Int64
      description: "该文件的上次写入日期。"
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>name</code>不指向.config 扩展名的文件。"
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  id: GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在内部用于支持对配置数据的远程访问。"
  syntax:
    content: public string GetFilePaths (int webLevelAsInt, string path, string site, string locationSubPath);
    parameters:
    - id: webLevelAsInt
      type: System.Int32
      description: "配置文件的级别。"
    - id: path
      type: System.String
      description: "若要访问远程配置文件的路径。"
    - id: site
      type: System.String
      description: "远程计算机的路径。"
    - id: locationSubPath
      type: System.String
      description: "配置文件的位置的子路径。"
    return:
      type: System.String
      description: "表示配置文件的文件路径的串联的字符串。"
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  id: WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  langs:
  - csharp
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "在内部用于支持对配置数据的远程访问。"
  syntax:
    content: public void WriteData (string fileName, string templateFileName, byte[] data, ref long readTime);
    parameters:
    - id: fileName
      type: System.String
      description: "若要访问远程配置文件的路径。"
    - id: templateFileName
      type: System.String
      description: "要从其中复制文件属性的文件。"
    - id: data
      type: System.Byte[]
      description: "要写入的数据。"
    - id: readTime
      type: System.Int64
      description: "上次访问文件的时间。"
  overload: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData*
  exceptions:
  - type: System.Exception
    commentId: T:System.Exception
    description: "<code>fileName</code> does not point to a file with the .config extension.  \n  \n \\- or -  \n  \n The file has changed since it was read.  \n  \n \\- or -  \n  \n The file is hidden or read-only.  \n  \n \\- or -  \n  \n The method fails to generate a temp file.  \n  \n \\- or -  \n  \n The method fails to create a <xref href=\"System.IO.FileStream\"></xref>.  \n  \n \\- or -  \n  \n The temp file fails to overwrite the target file."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Exception
  isExternal: true
  name: System.Exception
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: RemoteWebConfigurationHostServer()
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer()
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(System.Boolean,System.String,System.String,System.String,System.String[],System.String[])
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt(Boolean,String,String,String,String[],String[])
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(System.String,System.Boolean,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetData(String,Boolean,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData(String,Boolean,Int64)
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(System.String,System.Boolean@,System.Int64@,System.Int64@,System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails(String,Boolean,Int64,Int64,Int64)
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails(String,Boolean,Int64,Int64,Int64)
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(System.Int32,System.String,System.String,System.String)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths(Int32,String,String,String)
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths(Int32,String,String,String)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(System.String,System.String,System.Byte[],System.Int64@)
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData(String,String,Byte[],Int64)
  nameWithType: RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
  fullName: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData(String,String,Byte[],Int64)
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.#ctor*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: RemoteWebConfigurationHostServer
  nameWithType: RemoteWebConfigurationHostServer.RemoteWebConfigurationHostServer
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.DoEncryptOrDecrypt*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: DoEncryptOrDecrypt
  nameWithType: RemoteWebConfigurationHostServer.DoEncryptOrDecrypt
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetData*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetData
  nameWithType: RemoteWebConfigurationHostServer.GetData
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFileDetails*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFileDetails
  nameWithType: RemoteWebConfigurationHostServer.GetFileDetails
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.GetFilePaths*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: GetFilePaths
  nameWithType: RemoteWebConfigurationHostServer.GetFilePaths
- uid: System.Web.Configuration.RemoteWebConfigurationHostServer.WriteData*
  parent: System.Web.Configuration.RemoteWebConfigurationHostServer
  isExternal: false
  name: WriteData
  nameWithType: RemoteWebConfigurationHostServer.WriteData
