### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.ApplicationIDAttribute
  id: ApplicationIDAttribute
  children:
  - System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  - System.EnterpriseServices.ApplicationIDAttribute.Value
  langs:
  - csharp
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute
  fullName: System.EnterpriseServices.ApplicationIDAttribute
  type: Class
  summary: "指定此程序集 （作为 GUID) 的应用程序 ID。 此类不能被继承。"
  remarks: "ApplicationIDAttribute 会在其构造函数中的 GUID。 注册时，在程序集中组件安装在具有给定 id 对应的应用程序"
  example:
  - "The following code example demonstrates the use of the ApplicationIDAttribute type.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/t-system.enterpriseservi_14_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/t-system.enterpriseservi_14_1.vb)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, Inherited=true)]

      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIDAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "初始化的新实例<xref href=&quot;System.EnterpriseServices.ApplicationIDAttribute&quot;></xref>类指定表示 COM + 应用程序的应用程序 ID 的 GUID。"
  remarks: ''
  example:
  - "The following code example demonstrates how to create a new <xref:System.EnterpriseServices.ApplicationIDAttribute>.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/csharp/m-system.enterpriseservi_17_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#1](~/add/codesnippet/visualbasic/m-system.enterpriseservi_17_1.vb)]"
  syntax:
    content: public ApplicationIDAttribute (string guid);
    parameters:
    - id: guid
      type: System.String
      description: "与 COM + 应用程序关联的 GUID。"
  overload: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  id: Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  langs:
  - csharp
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
  type: Property
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices
  summary: "获取 COM + 应用程序的 GUID。"
  remarks: "通过使用作为参数传递的 GUID 的构造函数设置值。"
  example:
  - "The following code example demonstrates how to get the value of an `ApplicationID` attribute's Value property.  \n  \n [!code-cs[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/csharp/p-system.enterpriseservi_3_1.cs)]\n [!code-vb[EnterpriseServices.ApplicationIDAttribute#0](~/add/codesnippet/visualbasic/p-system.enterpriseservi_3_1.vb)]"
  syntax:
    content: public Guid Value { get; }
    return:
      type: System.Guid
      description: "表示 COM + 应用程序的 GUID。"
  overload: System.EnterpriseServices.ApplicationIDAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor(System.String)
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute(String)
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute(String)
  fullName: System.EnterpriseServices.ApplicationIDAttribute.ApplicationIDAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
  fullName: System.EnterpriseServices.ApplicationIDAttribute.Value
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.EnterpriseServices.ApplicationIDAttribute.#ctor*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: ApplicationIDAttribute
  nameWithType: ApplicationIDAttribute.ApplicationIDAttribute
- uid: System.EnterpriseServices.ApplicationIDAttribute.Value*
  parent: System.EnterpriseServices.ApplicationIDAttribute
  isExternal: false
  name: Value
  nameWithType: ApplicationIDAttribute.Value
