### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsMode
  id: CustomErrorsMode
  children:
  - System.Web.Configuration.CustomErrorsMode.Off
  - System.Web.Configuration.CustomErrorsMode.On
  - System.Web.Configuration.CustomErrorsMode.RemoteOnly
  langs:
  - csharp
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
  type: Enum
  summary: "指定自定义错误模式的值。"
  remarks: "CustomErrorsMode 枚举的值设置时，可以使用<xref:System.Web.Configuration.CustomErrorsSection.Mode%2A>属性。</xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> 这些值定义自定义错误是启用、 禁用，或仅显示给远程客户端。"
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> property.  \n  \n [!code-vb[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/visualbasic/t-system.web.configurati_54_1.vb)]\n [!code-cs[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/csharp/t-system.web.configurati_54_1.cs)]"
  syntax:
    content: public enum CustomErrorsMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.Off
  id: Off
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "禁用自定义错误，并允许显示标准错误。"
  syntax:
    content: Off
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.On
  id: On
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "启用自定义错误。 如果没有<xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>发出标准错误的指定。</xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>"
  syntax:
    content: On
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  id: RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "启用远程客户端上的自定义错误。 自定义的错误将显示仅与远程客户端和 ASP.NET 错误将显示为本地主机。"
  syntax:
    content: RemoteOnly
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsMode.Off
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
- uid: System.Web.Configuration.CustomErrorsMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
- uid: System.Web.Configuration.CustomErrorsMode.On
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
