### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigSystem
  id: IInternalConfigSystem
  children:
  - System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  - System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  langs:
  - csharp
  name: IInternalConfigSystem
  nameWithType: IInternalConfigSystem
  fullName: System.Configuration.Internal.IInternalConfigSystem
  type: Interface
  summary: "定义一个接口，.NET Framework 用于初始化应用程序配置属性。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigSystem
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: IInternalConfigSystem.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "返回基于指定的键的配置对象。"
  remarks: "此方法调用的<xref:System.Configuration.ConfigurationSettings>类。</xref:System.Configuration.ConfigurationSettings> 配置密钥值的配置组名称和配置节名称组成。"
  syntax:
    content: public object GetSection (string configKey);
    parameters:
    - id: configKey
      type: System.String
      description: "配置密钥值。"
    return:
      type: System.Object
      description: "配置对象。"
  overload: System.Configuration.Internal.IInternalConfigSystem.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  id: RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: RefreshConfig(String)
  nameWithType: IInternalConfigSystem.RefreshConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "刷新配置系统基于指定的节名称。"
  remarks: "此方法调用的<xref:System.Configuration.ConfigurationSettings>类。</xref:System.Configuration.ConfigurationSettings>"
  syntax:
    content: public void RefreshConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "配置节的名称。"
  overload: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  langs:
  - csharp
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "获取一个值，该值指示是否支持用户配置。"
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果用户配置受支持;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: GetSection(String)
  nameWithType: IInternalConfigSystem.GetSection(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.GetSection(String)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(System.String)
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: RefreshConfig(String)
  nameWithType: IInternalConfigSystem.RefreshConfig(String)
  fullName: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig(String)
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
  fullName: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigSystem.GetSection*
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: GetSection
  nameWithType: IInternalConfigSystem.GetSection
- uid: System.Configuration.Internal.IInternalConfigSystem.RefreshConfig*
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: RefreshConfig
  nameWithType: IInternalConfigSystem.RefreshConfig
- uid: System.Configuration.Internal.IInternalConfigSystem.SupportsUserConfig*
  parent: System.Configuration.Internal.IInternalConfigSystem
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IInternalConfigSystem.SupportsUserConfig
