### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement
  id: IssuerNameRegistryElement
  children:
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  langs:
  - csharp
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement
  type: Class
  summary: "表示<xref uid=&quot;langword_csharp_&lt;issuerNameRegistry&gt;&quot; name=&quot;&lt;issuerNameRegistry&gt;&quot; href=&quot;&quot;></xref>配置文件中的元素。 此类不能被继承。"
  remarks: "`<issuerNameRegistry>`元素配置了颁发者名称注册表。 颁发者名称注册表将颁发者令牌映射到一个字符串名称。 <xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A>属性 (它表示`type`元素属性) 可以设置为注册的自定义类型。</xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A> 默认情况下，一种<xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>假定。</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>       `<issuerNameRegistry>`可以在服务级别下指定元素`<identityConfiguration>`元素或上一个安全令牌处理程序集合`<securityTokenHandlerConfiguration>`元素。 `IssuerNameRegistry`属性<xref:System.IdentityModel.Configuration.IdentityConfigurationElement>类和的<xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>类是 IssuerNameRegistryElement 的一个实例。</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement>"
  syntax:
    content: 'public sealed class IssuerNameRegistryElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.IdentityModel.Configuration.IssuerNameRegistryElement&quot;></xref>类。"
  syntax:
    content: public IssuerNameRegistryElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "获取或设置的字符串表示形式<xref:System.Type>的颁发者名称注册表。</xref:System.Type>"
  remarks: "此属性为可选项。 它对应于`type`属性`<issuerNameRegistry>`元素。 如果未指定，该属性是`null`，一种<xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>假定。</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "字符串表示形式<xref:System.Type>的颁发者名称注册表。</xref:System.Type> 该类型必须派生自<xref href=&quot;System.IdentityModel.Tokens.IssuerNameRegistry&quot;></xref>类。"
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
