### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization
  id: WebPartsPersonalizationAuthorization
  children:
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  - System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization
  type: Class
  summary: "提供以编程方式访问<xref uid=&quot;langword_csharp_authorization&quot; name=&quot;authorization&quot; href=&quot;&quot;></xref>中包含的部分<xref uid=&quot;langword_csharp_webParts&quot; name=&quot;webParts&quot; href=&quot;&quot;></xref>的配置节。 此类不能被继承。"
  remarks: "WebPartsPersonalizationAuthorization 类提供配置支持的 Web 部件的个性化设置授权。 此类可以用于允许或拒绝对 Web 部件资源的访问。"
  example:
  - "The following configuration-file example shows how to declaratively specify values for properties of the WebPartsPersonalizationAuthorization class.  \n  \n```  \n<system.web>  \n  <webParts>  \n    <personalization>  \n      <authorization>  \n        <deny users=\"*\" verbs=\"enterSharedScope\" />  \n        <allow users=\"*\" verbs=\"modifyState\" />  \n      </authorization>  \n    </personalization>  \n  </webParts>  \n</system.web>  \n```"
  syntax:
    content: 'public sealed class WebPartsPersonalizationAuthorization : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.WebPartsPersonalizationAuthorization&quot;></xref>类。"
  remarks: "此构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 此类的实例是可从<xref:System.Web.Configuration.WebPartsPersonalizationAuthorization>属性。</xref:System.Web.Configuration.WebPartsPersonalizationAuthorization>"
  syntax:
    content: public WebPartsPersonalizationAuthorization ();
    parameters: []
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  id: Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  id: Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  langs:
  - csharp
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "获取用于与 Web 部件的个性化设置授权规则的集合。"
  remarks: "<xref:System.Web.Configuration.AuthorizationRuleCollection>组成<xref:System.Web.Configuration.AuthorizationRule>对象。</xref:System.Web.Configuration.AuthorizationRule> </xref:System.Web.Configuration.AuthorizationRuleCollection> <xref:System.Web.Configuration.AuthorizationRule>对象包含<xref:System.Web.Configuration.AuthorizationRule.Action%2A>属性，<xref:System.Web.Configuration.AuthorizationRule.Users%2A>属性，和一个<xref:System.Web.Configuration.AuthorizationRule.Verbs%2A>属性。</xref:System.Web.Configuration.AuthorizationRule.Verbs%2A> </xref:System.Web.Configuration.AuthorizationRule.Users%2A> </xref:System.Web.Configuration.AuthorizationRule.Action%2A> </xref:System.Web.Configuration.AuthorizationRule> 这些属性可以设置为允许或拒绝对 Web 部件资源的访问。"
  syntax:
    content: public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: "<xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;> </xref>对象。"
  overload: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization()
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization()
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
  fullName: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.#ctor*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: WebPartsPersonalizationAuthorization
  nameWithType: WebPartsPersonalizationAuthorization.WebPartsPersonalizationAuthorization
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Properties*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Properties
  nameWithType: WebPartsPersonalizationAuthorization.Properties
- uid: System.Web.Configuration.WebPartsPersonalizationAuthorization.Rules*
  parent: System.Web.Configuration.WebPartsPersonalizationAuthorization
  isExternal: false
  name: Rules
  nameWithType: WebPartsPersonalizationAuthorization.Rules
