### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  id: NamedPipeConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  type: Class
  summary: "表示一个配置元素，指定命名管道传输的其他连接池设置。 此类不能被继承。"
  syntax:
    content: 'public sealed class NamedPipeConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement&quot;></xref>类。"
  syntax:
    content: public NamedPipeConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置一个字符串，定义用于传出通道的连接池的名称"
  remarks: "在经过流处理模式下，不共享连接，这意味着禁用连接池。 默认值为字符串&quot;default&quot;。 你可以修改此值，以隔离到不同的组特定的客户端的连接。"
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "一个字符串，定义用于传出通道的连接池的名称"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置连接在断开前可以保持空闲的最长时间。"
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "一个值为正<xref:System.TimeSpan>，指定连接在断开前可以保持空闲的最大时间。</xref:System.TimeSpan> 默认值为 00:02:00。"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置由服务启动的远程终结点的最大连接数。"
  remarks: "超出该限制的连接需要排队，直到下限制的空间中变为可用。 此属性限制在其中连接前保持排队状态引发异常的持续时间。       此属性限制从客户端的特定服务终结点的同时活动的连接数。 如果具有更多活动客户端连接而超出此值，该服务可能表现为客户端。 在这种情况下，应调整此值以超过预期同时进行的客户端连接到特定终结点的最大数目。"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "一个正整数，指定最大到远程终结点由服务启动的连接数。 默认值为 10。"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement()
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: NamedPipeConnectionPoolSettingsElement
  nameWithType: NamedPipeConnectionPoolSettingsElement.NamedPipeConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: NamedPipeConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: NamedPipeConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: NamedPipeConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.NamedPipeConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: NamedPipeConnectionPoolSettingsElement.Properties
