### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TransactedBatchingElement
  id: TransactedBatchingElement
  children:
  - System.ServiceModel.Configuration.TransactedBatchingElement.#ctor
  - System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType
  - System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior
  - System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize
  - System.ServiceModel.Configuration.TransactedBatchingElement.Properties
  langs:
  - csharp
  name: TransactedBatchingElement
  nameWithType: TransactedBatchingElement
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement
  type: Class
  summary: "表示一个配置元素，指定是否为支持事务批处理接收操作。 此类不能被继承。"
  remarks: "使用事务批处理配置的传输将尝试批处理多个接收到一个事务的操作。 通过这样做，相对较高的成本创建事务以及在中提交的每个接收操作，则将避免。"
  syntax:
    content: 'public sealed class TransactedBatchingElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: TransactedBatchingElement()
  nameWithType: TransactedBatchingElement.TransactedBatchingElement()
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.TransactedBatchingElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.TransactedBatchingElement&quot;></xref>类。"
  syntax:
    content: public TransactedBatchingElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: TransactedBatchingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取此行为配置元素的类型。"
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "行为的类型。"
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: TransactedBatchingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "将指定的配置元素的内容复制到此配置元素。"
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "要复制的配置元素。"
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: TransactedBatchingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "要添加。"
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize
  id: MaxBatchSize
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: MaxBatchSize
  nameWithType: TransactedBatchingElement.MaxBatchSize
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置的最大数归入接收操作数可成批归入一个事务中。"
  syntax:
    content: public int MaxBatchSize { get; set; }
    return:
      type: System.Int32
      description: "最大数归入一个事务中接收可成批归入的操作。 默认值为 0。"
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  langs:
  - csharp
  name: Properties
  nameWithType: TransactedBatchingElement.Properties
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.TransactedBatchingElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.#ctor
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: TransactedBatchingElement()
  nameWithType: TransactedBatchingElement.TransactedBatchingElement()
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.TransactedBatchingElement()
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: BehaviorType
  nameWithType: TransactedBatchingElement.BehaviorType
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: TransactedBatchingElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: TransactedBatchingElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: MaxBatchSize
  nameWithType: TransactedBatchingElement.MaxBatchSize
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.Properties
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: Properties
  nameWithType: TransactedBatchingElement.Properties
  fullName: System.ServiceModel.Configuration.TransactedBatchingElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.#ctor*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: TransactedBatchingElement
  nameWithType: TransactedBatchingElement.TransactedBatchingElement
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.BehaviorType*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: BehaviorType
  nameWithType: TransactedBatchingElement.BehaviorType
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CopyFrom*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: CopyFrom
  nameWithType: TransactedBatchingElement.CopyFrom
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: CreateBehavior
  nameWithType: TransactedBatchingElement.CreateBehavior
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.MaxBatchSize*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: MaxBatchSize
  nameWithType: TransactedBatchingElement.MaxBatchSize
- uid: System.ServiceModel.Configuration.TransactedBatchingElement.Properties*
  parent: System.ServiceModel.Configuration.TransactedBatchingElement
  isExternal: false
  name: Properties
  nameWithType: TransactedBatchingElement.Properties
