### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  id: X509InitiatorCertificateClientElement
  children:
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  - System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  type: Class
  summary: "表示一个配置元素，指定客户端用于标识自身的证书。 此类不能被继承。"
  syntax:
    content: 'public sealed class X509InitiatorCertificateClientElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "初始化的新实例<xref href=&quot;System.ServiceModel.Configuration.X509InitiatorCertificateClientElement&quot;></xref>类。"
  syntax:
    content: public X509InitiatorCertificateClientElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  id: Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "将指定的配置元素的内容复制到此配置元素。"
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509InitiatorCertificateClientElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
      description: "要复制的配置元素。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "配置文件是只读的。"
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置一个字符串，指定要在 X.509 证书存储区中搜索的值。"
  remarks: "此属性中包含的类型必须满足的要求指定<xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType%2A>值。</xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType%2A> 默认值为一个空字符串。"
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "要在 X.509 证书存储区中搜索的值。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置一个值，指定可以用于验证服务器的证书客户端的证书存储区位置。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>指定客户端可用于验证服务器的证书的证书存储区位置。 默认值是<xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置要打开的 X.509 证书存储区的名称。"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> ，其中包含要打开的 X.509 证书存储区的名称。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置要执行的 X.509 搜索的类型。"
  remarks: "中包含的类型<xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue%2A>必须满足此属性的要求。</xref:System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> ，指定要执行的 X.509 搜索的类型。"
  overload: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement()
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement()
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(System.ServiceModel.Configuration.X509InitiatorCertificateClientElement)
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy(X509InitiatorCertificateClientElement)
  nameWithType: X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy(X509InitiatorCertificateClientElement)
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.#ctor*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509InitiatorCertificateClientElement
  nameWithType: X509InitiatorCertificateClientElement.X509InitiatorCertificateClientElement
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Copy*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Copy
  nameWithType: X509InitiatorCertificateClientElement.Copy
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.FindValue*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: FindValue
  nameWithType: X509InitiatorCertificateClientElement.FindValue
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.Properties*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: Properties
  nameWithType: X509InitiatorCertificateClientElement.Properties
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509InitiatorCertificateClientElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.StoreName*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: StoreName
  nameWithType: X509InitiatorCertificateClientElement.StoreName
- uid: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509InitiatorCertificateClientElement
  isExternal: false
  name: X509FindType
  nameWithType: X509InitiatorCertificateClientElement.X509FindType
