### YamlMime:ManagedReference
items:
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  id: ConfigErrorGlyph
  children:
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  - System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  langs:
  - csharp
  name: ConfigErrorGlyph
  nameWithType: ConfigErrorGlyph
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  type: Class
  summary: "提供的字形<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;></xref>用户在设计时不执行所需的设计器操作时显示。"
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]活动设计器使用 ConfigErrorGlyph 以显示与设计器图面上的智能标记关联的操作。 例如，如果活动要求用户设置的属性，活动设计器将显示 ConfigErrorGlyph 以通知他们需要设置属性。"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class ConfigErrorGlyph : System.Workflow.ComponentModel.Design.DesignerGlyph
  inheritance:
  - System.Object
  - System.Workflow.ComponentModel.Design.DesignerGlyph
  implements: []
  inheritedMembers:
  - System.Workflow.ComponentModel.Design.DesignerGlyph.HighestPriority
  - System.Workflow.ComponentModel.Design.DesignerGlyph.LowestPriority
  - System.Workflow.ComponentModel.Design.DesignerGlyph.NormalPriority
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  id: '#ctor'
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: ConfigErrorGlyph()
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph()
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.ConfigErrorGlyph()
  type: Constructor
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "初始化的新实例<xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;></xref>类。"
  syntax:
    content: public ConfigErrorGlyph ();
    parameters: []
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  id: CanBeActivated
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  type: Property
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "获取一个值，该值指示是否<xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;></xref>可以上获取焦点<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;></xref>与它关联。"
  syntax:
    content: public override bool CanBeActivated { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果可以激活设计器标志符号;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>。"
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  id: GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: GetBounds(ActivityDesigner,Boolean)
  nameWithType: ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "返回对指定的标志符号的边界<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref>。"
  syntax:
    content: public override System.Drawing.Rectangle GetBounds (System.Workflow.ComponentModel.Design.ActivityDesigner designer, bool activated);
    parameters:
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref>与标志符号关联。"
    - id: activated
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>指示在活动设计器图面; 上是否显示标志符号否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
    return:
      type: System.Drawing.Rectangle
      description: "A <xref href=&quot;System.Drawing.Rectangle&quot;> </xref>表示的标志符号的边界。"
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>designer</code>包含空引用 (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref>在 Visual Basic 中)。"
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  id: OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: OnActivate(ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnActivate(ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(ActivityDesigner)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "通知操作已的标志符号执行其激活。"
  remarks: "当调用 OnActivate 时，活动设计器图面上显示与标志符号关联的设计器谓词。"
  syntax:
    content: protected override void OnActivate (System.Workflow.ComponentModel.Design.ActivityDesigner designer);
    parameters:
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref>上绘制标志符号。"
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  id: OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  type: Method
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "执行呈现活动设计器图面上的标志符号所需的任何任务。"
  syntax:
    content: protected override void OnPaint (System.Drawing.Graphics graphics, bool activated, System.Workflow.ComponentModel.Design.AmbientTheme ambientTheme, System.Workflow.ComponentModel.Design.ActivityDesigner designer);
    parameters:
    - id: graphics
      type: System.Drawing.Graphics
      description: "<xref href=&quot;System.Drawing.Graphics&quot;> </xref>用于执行填充和绘制任务。"
    - id: activated
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>指示在设计图面，则上显示标志符号否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
    - id: ambientTheme
      type: System.Workflow.ComponentModel.Design.AmbientTheme
      description: "<xref href=&quot;System.Workflow.ComponentModel.Design.AmbientTheme&quot;> </xref>要用于访问环境属性设置。"
    - id: designer
      type: System.Workflow.ComponentModel.Design.ActivityDesigner
      description: "<xref href=&quot;System.Workflow.ComponentModel.Design.ActivityDesigner&quot;> </xref>从中获取有关用户操作的信息。"
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  id: Priority
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  langs:
  - csharp
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  type: Property
  assemblies:
  - System.Workflow.ComponentModel
  namespace: System.Workflow.ComponentModel.Design
  summary: "获取活动设计器图面上标志符号的优先级设置。"
  syntax:
    content: public override int Priority { get; }
    return:
      type: System.Int32
      description: "一个整数值，表示的优先级设置<xref href=&quot;System.Workflow.ComponentModel.Design.ConfigErrorGlyph&quot;></xref>活动设计图面上。"
  overload: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.ComponentModel.Design.DesignerGlyph
  isExternal: false
  name: System.Workflow.ComponentModel.Design.DesignerGlyph
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: ConfigErrorGlyph()
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph()
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.ConfigErrorGlyph()
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(System.Workflow.ComponentModel.Design.ActivityDesigner,System.Boolean)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: GetBounds(ActivityDesigner,Boolean)
  nameWithType: ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds(ActivityDesigner,Boolean)
- uid: System.Drawing.Rectangle
  parent: System.Drawing
  isExternal: false
  name: Rectangle
  nameWithType: Rectangle
  fullName: System.Drawing.Rectangle
- uid: System.Workflow.ComponentModel.Design.ActivityDesigner
  parent: System.Workflow.ComponentModel.Design
  isExternal: false
  name: ActivityDesigner
  nameWithType: ActivityDesigner
  fullName: System.Workflow.ComponentModel.Design.ActivityDesigner
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnActivate(ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnActivate(ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate(ActivityDesigner)
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(System.Drawing.Graphics,System.Boolean,System.Workflow.ComponentModel.Design.AmbientTheme,System.Workflow.ComponentModel.Design.ActivityDesigner)
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  nameWithType: ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint(Graphics,Boolean,AmbientTheme,ActivityDesigner)
- uid: System.Drawing.Graphics
  parent: System.Drawing
  isExternal: false
  name: Graphics
  nameWithType: Graphics
  fullName: System.Drawing.Graphics
- uid: System.Workflow.ComponentModel.Design.AmbientTheme
  parent: System.Workflow.ComponentModel.Design
  isExternal: false
  name: AmbientTheme
  nameWithType: AmbientTheme
  fullName: System.Workflow.ComponentModel.Design.AmbientTheme
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
  fullName: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.#ctor*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: ConfigErrorGlyph
  nameWithType: ConfigErrorGlyph.ConfigErrorGlyph
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.CanBeActivated*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: CanBeActivated
  nameWithType: ConfigErrorGlyph.CanBeActivated
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.GetBounds*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: GetBounds
  nameWithType: ConfigErrorGlyph.GetBounds
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnActivate*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnActivate
  nameWithType: ConfigErrorGlyph.OnActivate
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.OnPaint*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: OnPaint
  nameWithType: ConfigErrorGlyph.OnPaint
- uid: System.Workflow.ComponentModel.Design.ConfigErrorGlyph.Priority*
  parent: System.Workflow.ComponentModel.Design.ConfigErrorGlyph
  isExternal: false
  name: Priority
  nameWithType: ConfigErrorGlyph.Priority
