### YamlMime:ManagedReference
items:
- uid: System.Configuration.Assemblies.AssemblyHash
  id: AssemblyHash
  children:
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  - System.Configuration.Assemblies.AssemblyHash.Algorithm
  - System.Configuration.Assemblies.AssemblyHash.Clone
  - System.Configuration.Assemblies.AssemblyHash.Empty
  - System.Configuration.Assemblies.AssemblyHash.GetValue
  - System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  langs:
  - csharp
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
  type: Struct
  summary: "表示程序集清单内容的哈希值。"
  remarks: "整个公共语言运行时使用 AssemblyHash 值以检测程序集内容中的更改。"
  syntax:
    content: >-
      [System.Obsolete("The AssemblyHash class has been deprecated. http://go.microsoft.com/fwlink/?linkid=14202")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public struct AssemblyHash : ICloneable
  inheritance:
  - System.ValueType
  implements:
  - System.ICloneable
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  id: '#ctor(System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: AssemblyHash(Byte[])
  nameWithType: AssemblyHash.AssemblyHash(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(Byte[])
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "初始化的新实例<xref href=&quot;System.Configuration.Assemblies.AssemblyHash&quot;></xref>与指定的哈希值的结构。 哈希算法将默认为<xref href=&quot;System.Configuration.Assemblies.AssemblyHashAlgorithm&quot;> </xref>。"
  syntax:
    content: public AssemblyHash (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: "哈希值中。"
  overload: System.Configuration.Assemblies.AssemblyHash.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  id: '#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])'
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: AssemblyHash(AssemblyHashAlgorithm,Byte[])
  nameWithType: AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "初始化的新实例<xref href=&quot;System.Configuration.Assemblies.AssemblyHash&quot;></xref>结构具有指定的哈希算法和哈希值。"
  syntax:
    content: public AssemblyHash (System.Configuration.Assemblies.AssemblyHashAlgorithm algorithm, byte[] value);
    parameters:
    - id: algorithm
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "用于生成此哈希算法。 此参数的值来自<xref href=&quot;System.Configuration.Assemblies.AssemblyHashAlgorithm&quot;></xref>枚举。"
    - id: value
      type: System.Byte[]
      description: "哈希值中。"
  overload: System.Configuration.Assemblies.AssemblyHash.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  id: Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
  type: Property
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "获取或设置哈希算法。"
  remarks: "哈希组成的字节数组和值从支持的算法类型的类。"
  syntax:
    content: public System.Configuration.Assemblies.AssemblyHashAlgorithm Algorithm { get; set; }
    return:
      type: System.Configuration.Assemblies.AssemblyHashAlgorithm
      description: "程序集哈希算法。"
  overload: System.Configuration.Assemblies.AssemblyHash.Algorithm*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  id: Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Clone()
  nameWithType: AssemblyHash.Clone()
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "克隆此对象。"
  syntax:
    content: public object Clone ();
    parameters: []
    return:
      type: System.Object
      description: "此对象的一个精确副本。"
  overload: System.Configuration.Assemblies.AssemblyHash.Clone*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  id: Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
  type: Field
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "一个空<xref href=&quot;System.Configuration.Assemblies.AssemblyHash&quot;></xref>对象。"
  syntax:
    content: public static readonly System.Configuration.Assemblies.AssemblyHash Empty;
    return:
      type: System.Configuration.Assemblies.AssemblyHash
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  id: GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: GetValue()
  nameWithType: AssemblyHash.GetValue()
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue()
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "获取哈希值。"
  syntax:
    content: public byte[] GetValue ();
    parameters: []
    return:
      type: System.Byte[]
      description: "哈希值中。"
  overload: System.Configuration.Assemblies.AssemblyHash.GetValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  id: SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  langs:
  - csharp
  name: SetValue(Byte[])
  nameWithType: AssemblyHash.SetValue(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue(Byte[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Configuration.Assemblies
  summary: "设置哈希值。"
  syntax:
    content: public void SetValue (byte[] value);
    parameters:
    - id: value
      type: System.Byte[]
      description: "哈希值中。"
  overload: System.Configuration.Assemblies.AssemblyHash.SetValue*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ValueType
  isExternal: false
  name: System.ValueType
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash(Byte[])
  nameWithType: AssemblyHash.AssemblyHash(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(Byte[])
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor(System.Configuration.Assemblies.AssemblyHashAlgorithm,System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash(AssemblyHashAlgorithm,Byte[])
  nameWithType: AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.AssemblyHash(AssemblyHashAlgorithm,Byte[])
- uid: System.Configuration.Assemblies.AssemblyHashAlgorithm
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHashAlgorithm
  nameWithType: AssemblyHashAlgorithm
  fullName: System.Configuration.Assemblies.AssemblyHashAlgorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
  fullName: System.Configuration.Assemblies.AssemblyHash.Algorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Clone
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Clone()
  nameWithType: AssemblyHash.Clone()
  fullName: System.Configuration.Assemblies.AssemblyHash.Clone()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.Assemblies.AssemblyHash.Empty
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Empty
  nameWithType: AssemblyHash.Empty
  fullName: System.Configuration.Assemblies.AssemblyHash.Empty
- uid: System.Configuration.Assemblies.AssemblyHash
  parent: System.Configuration.Assemblies
  isExternal: false
  name: AssemblyHash
  nameWithType: AssemblyHash
  fullName: System.Configuration.Assemblies.AssemblyHash
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: GetValue()
  nameWithType: AssemblyHash.GetValue()
  fullName: System.Configuration.Assemblies.AssemblyHash.GetValue()
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue(System.Byte[])
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: SetValue(Byte[])
  nameWithType: AssemblyHash.SetValue(Byte[])
  fullName: System.Configuration.Assemblies.AssemblyHash.SetValue(Byte[])
- uid: System.Configuration.Assemblies.AssemblyHash.#ctor*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: AssemblyHash
  nameWithType: AssemblyHash.AssemblyHash
- uid: System.Configuration.Assemblies.AssemblyHash.Algorithm*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Algorithm
  nameWithType: AssemblyHash.Algorithm
- uid: System.Configuration.Assemblies.AssemblyHash.Clone*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: Clone
  nameWithType: AssemblyHash.Clone
- uid: System.Configuration.Assemblies.AssemblyHash.GetValue*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: GetValue
  nameWithType: AssemblyHash.GetValue
- uid: System.Configuration.Assemblies.AssemblyHash.SetValue*
  parent: System.Configuration.Assemblies.AssemblyHash
  isExternal: false
  name: SetValue
  nameWithType: AssemblyHash.SetValue
