### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  summary: "提供一个字符串，描述的单独的配置属性。 此类不能被继承。"
  remarks: "SettingsDescriptionAttribute 旨在帮助进行标识和关联的配置属性描述的设计时工具和管理运行的时工具。       此属性是可选的只能在单独的配置属性级别应用。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的实例<xref href=&quot;System.Configuration.SettingsDescriptionAttribute&quot;></xref>类。"
  remarks: "尽管说明具有理论最大长度为<xref:System.String>类，其长度由<xref:System.Int32>，以下两个实际的考量将限制的大小`description`参数:-较大的文本说明很难显示在用户界面 (UI) 和用户阅读困难。</xref:System.Int32> </xref:System.String>      设置提供程序可能会强制实施的总体使用配额和所需强制用户配置配额的限制。"
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "<xref:System.String>用作描述性文本。</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "获取关联的配置属性的说明性文本。"
  remarks: "Description 属性将由<xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>构造函数。</xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "A<xref:System.String>包含关联的配置属性的说明性文本。</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
