### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidatorAttribute
  id: TimeSpanValidatorAttribute
  children:
  - System.Configuration.TimeSpanValidatorAttribute.#ctor
  - System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  - System.Configuration.TimeSpanValidatorAttribute.MaxValue
  - System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  - System.Configuration.TimeSpanValidatorAttribute.MinValue
  - System.Configuration.TimeSpanValidatorAttribute.MinValueString
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  - System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  - System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute
  fullName: System.Configuration.TimeSpanValidatorAttribute
  type: Class
  summary: "以声明方式指示.NET Framework 上的配置属性执行时验证。 此类不能被继承。"
  remarks: "使用 TimeSpanValidatorAttribute 特性修饰的配置属性。 这是为了指示要验证属性使用的.NET Framework<xref:System.Configuration.TimeSpanValidator>类并将装饰参数的值传递给它。</xref:System.Configuration.TimeSpanValidator>       你可以向属性类型才应用 TimeSpanValidatorAttribute 对象。"
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the TimeSpanValidatorAttribute attribute.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/t-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/t-system.configuration.t_1_1.cs)]  \n  \n The following example is an excerpt of the configuration file that contains the custom section used by the previous sample.  \n  \n```  \n<configuration xmlns=\"http://schemas.microsoft.com/.NetConfiguration/v2.0\">  \n  <configSections>  \n    <section name=\"custom\" type=\"Microsoft.Samples.AspNet.Configuration.SampleSection, ConfigurationValidatorAttribute\" />  \n  </configSections>  \n  <custom fileName=\"NewFile.txt\" maxSize=\"1000\" maxAttempts=\"101\" maxUsers=\"2500\" maxIdleTime=\"00:15:00\" />  \n</configuration>  \n```"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class TimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Configuration.TimeSpanValidatorAttribute&quot;></xref>类。"
  remarks: "使用此构造函数在特性化模型中以确保分配给相关属性的值的类型是<xref:System.TimeSpan>对象。</xref:System.TimeSpan>"
  example:
  - "The following example shows how to use the <xref:System.Configuration.StringValidatorAttribute.%23ctor%2A> constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/visualbasic/m-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#12](~/add/codesnippet/csharp/m-system.configuration.t_0_1.cs)]"
  syntax:
    content: public TimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  id: ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取或设置一个值，该值指示是否要包含或排除范围内的整数，由定义<> *1> 和<> *1>。"
  remarks: "范围是包括<xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A>和<xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A>属性。</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValueString%2A> </xref:System.Configuration.TimeSpanValidatorAttribute.MinValueString%2A> 当 ExcludeRange 属性是`false`，允许的值为超出范围。"
  example:
  - "The following example shows how to use the ExcludeRange property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_0_1.cs)]"
  syntax:
    content: public bool ExcludeRange { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果必须排除值;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。 默认值是<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  id: MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取绝对最大<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  remarks: "这是由.NET Framework 允许绝对最大值。 其值由定义<xref:System.TimeSpan>字段。</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MaxValue { get; }
    return:
      type: System.TimeSpan
      description: "允许的最大<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  id: MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取或设置相对大<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  remarks: "这是由用户设置的相关的最大值。"
  example:
  - "The following example shows how to use the MaxValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_1_1.cs)]"
  syntax:
    content: public string MaxValueString { get; set; }
    return:
      type: System.String
      description: "允许的最大<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "所选的值表示小于<xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MinValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  id: MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取绝对最小<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  remarks: "这是由.NET Framework 允许绝对最小值。 其值由定义<xref:System.TimeSpan>字段。</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpan MinValue { get; }
    return:
      type: System.TimeSpan
      description: "允许的最小<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  id: MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取或设置相对小<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  remarks: "这是由用户设置的相关的最小值。"
  example:
  - "The following example shows how to use the MinValueString property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/visualbasic/p-system.configuration.t_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#8](~/add/codesnippet/csharp/p-system.configuration.t_2_1.cs)]"
  syntax:
    content: public string MinValueString { get; set; }
    return:
      type: System.String
      description: "允许的最小<xref:System.TimeSpan>值。</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "所选的值表示多个<xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>.</xref:System.Configuration.TimeSpanValidatorAttribute.MaxValue*>"
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  id: TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取绝对允许的最大值。"
  remarks: "在时间间隔内包含的最大允许的值的字符串。"
  example:
  - "The following example shows how to use the TimeSpanMaxValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/visualbasic/f-system.configuration.t_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#10](~/add/codesnippet/csharp/f-system.configuration.t_0_1.cs)]"
  syntax:
    content: public const string TimeSpanMaxValue;
    return:
      type: System.String
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  id: TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取允许绝对最小值。"
  remarks: "包含时间间隔的最小允许的值的字符串。"
  example:
  - "The following example shows how to use the TimeSpanMinValue field.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/visualbasic/f-system.configuration.t_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#11](~/add/codesnippet/csharp/f-system.configuration.t_1_1.cs)]"
  syntax:
    content: public const string TimeSpanMinValue;
    return:
      type: System.String
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "获取实例<xref href=&quot;System.Configuration.TimeSpanValidator&quot;></xref>类。"
  remarks: "ValidatorInstance 属性用于通过调用执行字符串验证其<xref:System.Configuration.TimeSpanValidator.Validate%2A>方法。</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "<xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref>验证程序实例。"
  overload: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute()
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanValidatorAttribute()
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
  fullName: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValue
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MaxValueString
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
  fullName: System.Configuration.TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMaxValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMaxValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanMinValue
  nameWithType: TimeSpanValidatorAttribute.TimeSpanMinValue
  fullName: System.Configuration.TimeSpanValidatorAttribute.TimeSpanMinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.TimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: TimeSpanValidatorAttribute
  nameWithType: TimeSpanValidatorAttribute.TimeSpanValidatorAttribute
- uid: System.Configuration.TimeSpanValidatorAttribute.ExcludeRange*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ExcludeRange
  nameWithType: TimeSpanValidatorAttribute.ExcludeRange
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValue
  nameWithType: TimeSpanValidatorAttribute.MaxValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MaxValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MaxValueString
  nameWithType: TimeSpanValidatorAttribute.MaxValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValue*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValue
  nameWithType: TimeSpanValidatorAttribute.MinValue
- uid: System.Configuration.TimeSpanValidatorAttribute.MinValueString*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: MinValueString
  nameWithType: TimeSpanValidatorAttribute.MinValueString
- uid: System.Configuration.TimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.TimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: TimeSpanValidatorAttribute.ValidatorInstance
