### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  id: MachineKeyCompatibilityMode
  children:
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  - System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  langs:
  - csharp
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
  type: Enum
  summary: "指定可以使用的加密方法。"
  remarks: "设置时使用的 MachineKeyCompatibilityMode 值<xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>属性。</xref:System.Web.Configuration.MachineKeySection.CompatibilityMode%2A>"
  syntax:
    content: public enum MachineKeyCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  id: Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "使用加密方法实现在.NET Framework 版本早于 2.0 版 Service Pack 2。 初始化向量 (Iv) 适用于除 ASP.NET 成员资格数据库中存储加密的密码的所有加密操作。"
  syntax:
    content: Framework20SP1
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  id: Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "使用.NET Framework 2.0 SP2 和更高版本中可用的更强的加密方法。 初始化向量 (Iv) 用于所有加密操作。"
  syntax:
    content: Framework20SP2
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  id: Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  langs:
  - csharp
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "使用.NET Framework 版本 4.5 和更高版本中可用的加密方法。 与用于 Framework20SP1 和 Framework20SP2 的加密方法相比，生成的默认加密例程已加密文本略小并更灵活处理针对特定类别的理论上的攻击。 他们还与集成[!INCLUDE[win8](~/add/includes/ajax-current-ext-md.md)]目录以获取所需的加密密钥的密钥管理。 此选项还可以通过编写派生自的类来指定自定义加密例程<xref href=&quot;System.Security.Cryptography.DataProtector&quot;></xref>并指定中的类名称&lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt;属性。       以下的配置要求适用于此选项︰ 1。 如果&lt;xref:System.Web.Configuration.MachineKeySection.DataProtectorType%2A?displayProperty=fullName&gt;属性具有值， &lt;xref:System.Web.Configuration.MachineKeySection.ApplicationName%2A?displayProperty=fullName&gt;属性还必须具有一个值。       2. &lt;Xref:System.Web.Configuration.MachineKeySection.Validation%2A?displayProperty=fullName&gt;特性必须派生自的类中指定的系统定义的验证算法 （如 MD5、 SHA1、 HMACSHA256、 HMACSHA384 或 HMACSHA512） 或自定义的验证算法<xref href=&quot;System.Security.Cryptography.KeyedHashAlgorithm&quot;></xref>类。 AES 和 3DES 的值不是验证算法。       当指定此选项时，窗体身份验证票证进行始终同时加密和签名，而不考虑为指定的值&lt;xref:System.Web.Configuration.FormsAuthenticationConfiguration.Protection%2A?displayProperty=fullName&gt;属性。 视图状态还都加密和签名如果页面的<> *1> 属性是<code> true </code>或<> *1> 属性是<xref:System.Web.UI.ViewStateEncryptionMode.Always>.</xref:System.Web.UI.ViewStateEncryptionMode.Always>"
  syntax:
    content: Framework45
    return:
      type: System.Web.Configuration.MachineKeyCompatibilityMode
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP1
  nameWithType: MachineKeyCompatibilityMode.Framework20SP1
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP1
- uid: System.Web.Configuration.MachineKeyCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MachineKeyCompatibilityMode
  nameWithType: MachineKeyCompatibilityMode
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework20SP2
  nameWithType: MachineKeyCompatibilityMode.Framework20SP2
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework20SP2
- uid: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
  parent: System.Web.Configuration.MachineKeyCompatibilityMode
  isExternal: false
  name: Framework45
  nameWithType: MachineKeyCompatibilityMode.Framework45
  fullName: System.Web.Configuration.MachineKeyCompatibilityMode.Framework45
