### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanSecondsConverter
  id: TimeSpanSecondsConverter
  children:
  - System.Configuration.TimeSpanSecondsConverter.#ctor
  - System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  langs:
  - csharp
  name: TimeSpanSecondsConverter
  nameWithType: TimeSpanSecondsConverter
  fullName: System.Configuration.TimeSpanSecondsConverter
  type: Class
  summary: "将转换以秒为单位表示的时间跨度。"
  remarks: "这种类型，如所有其他配置转换器类型，将在配置文件与相关的强类型属性中找到的字符串转换。       具体而言，将转换 TimeSpanSecondsConverter<xref:System.String>秒，为分配给配置属性，<xref:System.TimeSpan>秒，反之亦然。</xref:System.TimeSpan> </xref:System.String>       <xref:System.Configuration.TimeSpanMinutesConverter>仍然存在类型的值`long`，可表示的秒数。</xref:System.Configuration.TimeSpanMinutesConverter>"
  example:
  - Refer to the code examples in <xref:System.Configuration.InfiniteTimeSpanConverter> and <xref:System.Configuration.TimeSpanMinutesConverter>.
  syntax:
    content: 'public class TimeSpanSecondsConverter : System.Configuration.ConfigurationConverterBase'
  inheritance:
  - System.Object
  - System.ComponentModel.TypeConverter
  - System.Configuration.ConfigurationConverterBase
  implements: []
  inheritedMembers:
  - System.ComponentModel.TypeConverter.CanConvertFrom(System.Type)
  - System.ComponentModel.TypeConverter.CanConvertTo(System.Type)
  - System.ComponentModel.TypeConverter.ConvertFrom(System.Object)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromInvariantString(System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.ComponentModel.ITypeDescriptorContext,System.String)
  - System.ComponentModel.TypeConverter.ConvertFromString(System.String)
  - System.ComponentModel.TypeConverter.ConvertTo(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToInvariantString(System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.ConvertToString(System.Object)
  - System.ComponentModel.TypeConverter.CreateInstance(System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.CreateInstance(System.ComponentModel.ITypeDescriptorContext,System.Collections.IDictionary)
  - System.ComponentModel.TypeConverter.GetConvertFromException(System.Object)
  - System.ComponentModel.TypeConverter.GetConvertToException(System.Object,System.Type)
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported
  - System.ComponentModel.TypeConverter.GetCreateInstanceSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.GetProperties(System.ComponentModel.ITypeDescriptorContext,System.Object,System.Attribute[])
  - System.ComponentModel.TypeConverter.GetProperties(System.Object)
  - System.ComponentModel.TypeConverter.GetPropertiesSupported
  - System.ComponentModel.TypeConverter.GetPropertiesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValues
  - System.ComponentModel.TypeConverter.GetStandardValues(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive
  - System.ComponentModel.TypeConverter.GetStandardValuesExclusive(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported
  - System.ComponentModel.TypeConverter.GetStandardValuesSupported(System.ComponentModel.ITypeDescriptorContext)
  - System.ComponentModel.TypeConverter.IsValid(System.ComponentModel.ITypeDescriptorContext,System.Object)
  - System.ComponentModel.TypeConverter.IsValid(System.Object)
  - System.ComponentModel.TypeConverter.SortProperties(System.ComponentModel.PropertyDescriptorCollection,System.String[])
  - System.Configuration.ConfigurationConverterBase.CanConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Type)
  - System.Configuration.ConfigurationConverterBase.CanConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Type)
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  id: '#ctor'
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Configuration.TimeSpanSecondsConverter&quot;></xref>类。"
  remarks: "通常情况下，你使用由系统提供的转换器类型。 创建你自己的转换类型时需要使用 TimeSpanSecondsConverter 构造函数的唯一时间。"
  syntax:
    content: public TimeSpanSecondsConverter ();
    parameters: []
  overload: System.Configuration.TimeSpanSecondsConverter.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  id: ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "将转换<xref:System.String>到一种<xref:System.TimeSpan>。</xref:System.TimeSpan> </xref:System.String>"
  remarks: "它从要转换<xref:System.String>到<xref:System.TimeSpan>。</xref:System.TimeSpan>的值</xref:System.String>的配置文件中读取时，系统将使用 ConvertFrom 方法"
  syntax:
    content: public override object ConvertFrom (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object data);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref>用于类型转换的对象。"
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>在转换过程中使用的对象。</xref:System.Globalization.CultureInfo>"
    - id: data
      type: System.Object
      description: "<xref:System.String>要转换的对象。</xref:System.String>"
    return:
      type: System.Object
      description: "<xref:System.TimeSpan>表示<code> data </code>参数以秒为单位。</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanSecondsConverter.ConvertFrom*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>data</code>无法分析为整数值。"
  platform:
  - net462
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  id: ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  langs:
  - csharp
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "将转换<xref:System.TimeSpan>到一种<xref:System.String>。</xref:System.String> </xref:System.TimeSpan>"
  remarks: "当写入配置文件将转换<xref:System.TimeSpan>到一种<xref:System.String>。</xref:System.String> </xref:System.TimeSpan> ，系统将使用 ConvertTo 方法"
  syntax:
    content: public override object ConvertTo (System.ComponentModel.ITypeDescriptorContext ctx, System.Globalization.CultureInfo ci, object value, Type type);
    parameters:
    - id: ctx
      type: System.ComponentModel.ITypeDescriptorContext
      description: "<xref href=&quot;System.ComponentModel.ITypeDescriptorContext&quot;> </xref>用于类型转换的对象。"
    - id: ci
      type: System.Globalization.CultureInfo
      description: "<xref:System.Globalization.CultureInfo>在转换过程中使用的对象。</xref:System.Globalization.CultureInfo>"
    - id: value
      type: System.Object
      description: "要转换的值。"
    - id: type
      type: System.Type
      description: "要转换的类型。"
    return:
      type: System.Object
      description: "<xref:System.String>表示<code> value </code>以分钟为单位的参数。</xref:System.String>"
  overload: System.Configuration.TimeSpanSecondsConverter.ConvertTo*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationConverterBase
  isExternal: false
  name: System.Configuration.ConfigurationConverterBase
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: TimeSpanSecondsConverter()
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter()
  fullName: System.Configuration.TimeSpanSecondsConverter.TimeSpanSecondsConverter()
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  nameWithType: TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertFrom(ITypeDescriptorContext,CultureInfo,Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ComponentModel.ITypeDescriptorContext
  parent: System.ComponentModel
  isExternal: false
  name: ITypeDescriptorContext
  nameWithType: ITypeDescriptorContext
  fullName: System.ComponentModel.ITypeDescriptorContext
- uid: System.Globalization.CultureInfo
  parent: System.Globalization
  isExternal: true
  name: CultureInfo
  nameWithType: CultureInfo
  fullName: System.Globalization.CultureInfo
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo(System.ComponentModel.ITypeDescriptorContext,System.Globalization.CultureInfo,System.Object,System.Type)
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  nameWithType: TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
  fullName: System.Configuration.TimeSpanSecondsConverter.ConvertTo(ITypeDescriptorContext,CultureInfo,Object,Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanSecondsConverter.#ctor*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: TimeSpanSecondsConverter
  nameWithType: TimeSpanSecondsConverter.TimeSpanSecondsConverter
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertFrom*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertFrom
  nameWithType: TimeSpanSecondsConverter.ConvertFrom
- uid: System.Configuration.TimeSpanSecondsConverter.ConvertTo*
  parent: System.Configuration.TimeSpanSecondsConverter
  isExternal: false
  name: ConvertTo
  nameWithType: TimeSpanSecondsConverter.ConvertTo
