### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "指定设置提供程序，应禁用时检测到应用程序升级获得调用的任何逻辑。 此类不能被继承。"
  remarks: "若要创建的功能完整的应用程序设置提供程序支持应用程序版本控制，该提供程序必须实现<xref:System.Configuration.IApplicationSettingsProvider>接口。</xref:System.Configuration.IApplicationSettingsProvider> 此接口中的成员之一<xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>调用方法，以通知提供程序已安装应用程序的新版本。</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> 在响应中，此提供程序应执行适当的操作，通常迁移过去的应用程序设置。       NoSettingsVersionUpgradeAttribute 通知要取消升级逻辑与当前的设置类相关联的提供程序。 因此，此属性组的以前版本的值不应迁移到新安装。      1> [!NOTE]&1;> 此特性仅应用于单个应用程序设置属性。"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;></xref>类。"
  remarks: "这是<xref:System.Configuration.NoSettingsVersionUpgradeAttribute>类</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>的编译器提供的默认构造函数"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
