### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationShutdownReason
  id: ApplicationShutdownReason
  children:
  - System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.BuildManagerChange
  - System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  - System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  - System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.ConfigurationChange
  - System.Web.ApplicationShutdownReason.HostingEnvironment
  - System.Web.ApplicationShutdownReason.HttpRuntimeClose
  - System.Web.ApplicationShutdownReason.IdleTimeout
  - System.Web.ApplicationShutdownReason.InitializationError
  - System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  - System.Web.ApplicationShutdownReason.None
  - System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  - System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  - System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  langs:
  - csharp
  name: ApplicationShutdownReason
  nameWithType: ApplicationShutdownReason
  fullName: System.Web.ApplicationShutdownReason
  type: Enum
  summary: "指定原因<xref href=&quot;System.AppDomain&quot;></xref>类关闭。"
  remarks: "ApplicationShutdownReason 表示<xref:System.Web.Hosting.HostingEnvironment.ShutdownReason%2A>的<xref:System.Web.Hosting.HostingEnvironment>类</xref:System.Web.Hosting.HostingEnvironment>的属性</xref:System.Web.Hosting.HostingEnvironment.ShutdownReason%2A>的可能值"
  syntax:
    content: public enum ApplicationShutdownReason
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  id: BinDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BinDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "到 Bin 文件夹或文件进行了更改。"
  syntax:
    content: BinDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  id: BrowsersDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BrowsersDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "到 App_Browsers 文件夹或文件进行了更改。"
  syntax:
    content: BrowsersDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.BuildManagerChange
  id: BuildManagerChange
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: BuildManagerChange
  nameWithType: ApplicationShutdownReason.BuildManagerChange
  fullName: System.Web.ApplicationShutdownReason.BuildManagerChange
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "编译系统关闭应用程序域。 BuildManagerChange 成员是在.NET Framework 版本 3.5 中引入的。  有关详细信息，请参阅[.NET Framework 版本和依赖关系](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: BuildManagerChange
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  id: ChangeInGlobalAsax
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ChangeInGlobalAsax
  nameWithType: ApplicationShutdownReason.ChangeInGlobalAsax
  fullName: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Global.asax 文件已更改。"
  syntax:
    content: ChangeInGlobalAsax
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  id: ChangeInSecurityPolicyFile
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ChangeInSecurityPolicyFile
  nameWithType: ApplicationShutdownReason.ChangeInSecurityPolicyFile
  fullName: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "代码访问安全性策略文件中进行更改。"
  syntax:
    content: ChangeInSecurityPolicyFile
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  id: CodeDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: CodeDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "通过向 App_Code 文件夹或文件进行了更改。"
  syntax:
    content: CodeDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ConfigurationChange
  id: ConfigurationChange
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ConfigurationChange
  nameWithType: ApplicationShutdownReason.ConfigurationChange
  fullName: System.Web.ApplicationShutdownReason.ConfigurationChange
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "应用程序级配置文件已更改。"
  syntax:
    content: ConfigurationChange
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.HostingEnvironment
  id: HostingEnvironment
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: HostingEnvironment
  nameWithType: ApplicationShutdownReason.HostingEnvironment
  fullName: System.Web.ApplicationShutdownReason.HostingEnvironment
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "宿主环境关闭应用程序域。"
  syntax:
    content: HostingEnvironment
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  id: HttpRuntimeClose
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: HttpRuntimeClose
  nameWithType: ApplicationShutdownReason.HttpRuntimeClose
  fullName: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "到<xref:System.Web.HttpRuntime.Close*>。</xref:System.Web.HttpRuntime.Close*>进行了调用"
  syntax:
    content: HttpRuntimeClose
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.IdleTimeout
  id: IdleTimeout
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: ApplicationShutdownReason.IdleTimeout
  fullName: System.Web.ApplicationShutdownReason.IdleTimeout
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "已达到最大空闲时间限制。"
  syntax:
    content: IdleTimeout
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.InitializationError
  id: InitializationError
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: InitializationError
  nameWithType: ApplicationShutdownReason.InitializationError
  fullName: System.Web.ApplicationShutdownReason.InitializationError
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "<xref href=&quot;System.AppDomain&quot;> </xref>出现初始化错误。"
  syntax:
    content: InitializationError
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  id: MaxRecompilationsReached
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: MaxRecompilationsReached
  nameWithType: ApplicationShutdownReason.MaxRecompilationsReached
  fullName: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "已达到动态重新编译的资源的最大数。"
  syntax:
    content: MaxRecompilationsReached
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.None
  id: None
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: None
  nameWithType: ApplicationShutdownReason.None
  fullName: System.Web.ApplicationShutdownReason.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "不提供的任何关闭原因。"
  syntax:
    content: None
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  id: PhysicalApplicationPathChanged
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: PhysicalApplicationPathChanged
  nameWithType: ApplicationShutdownReason.PhysicalApplicationPathChanged
  fullName: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "应用程序的物理路径已更改。"
  syntax:
    content: PhysicalApplicationPathChanged
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  id: ResourcesDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: ResourcesDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "到 App_GlobalResources 文件夹或文件进行了更改。"
  syntax:
    content: ResourcesDirChangeOrDirectoryRename
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  id: UnloadAppDomainCalled
  parent: System.Web.ApplicationShutdownReason
  langs:
  - csharp
  name: UnloadAppDomainCalled
  nameWithType: ApplicationShutdownReason.UnloadAppDomainCalled
  fullName: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "到<xref:System.Web.HttpRuntime.UnloadAppDomain*>。</xref:System.Web.HttpRuntime.UnloadAppDomain*>进行了调用"
  syntax:
    content: UnloadAppDomainCalled
    return:
      type: System.Web.ApplicationShutdownReason
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BinDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BinDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BinDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason
  parent: System.Web
  isExternal: false
  name: ApplicationShutdownReason
  nameWithType: ApplicationShutdownReason
  fullName: System.Web.ApplicationShutdownReason
- uid: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BrowsersDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.BrowsersDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.BuildManagerChange
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: BuildManagerChange
  nameWithType: ApplicationShutdownReason.BuildManagerChange
  fullName: System.Web.ApplicationShutdownReason.BuildManagerChange
- uid: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ChangeInGlobalAsax
  nameWithType: ApplicationShutdownReason.ChangeInGlobalAsax
  fullName: System.Web.ApplicationShutdownReason.ChangeInGlobalAsax
- uid: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ChangeInSecurityPolicyFile
  nameWithType: ApplicationShutdownReason.ChangeInSecurityPolicyFile
  fullName: System.Web.ApplicationShutdownReason.ChangeInSecurityPolicyFile
- uid: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: CodeDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.CodeDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.ConfigurationChange
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ConfigurationChange
  nameWithType: ApplicationShutdownReason.ConfigurationChange
  fullName: System.Web.ApplicationShutdownReason.ConfigurationChange
- uid: System.Web.ApplicationShutdownReason.HostingEnvironment
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: HostingEnvironment
  nameWithType: ApplicationShutdownReason.HostingEnvironment
  fullName: System.Web.ApplicationShutdownReason.HostingEnvironment
- uid: System.Web.ApplicationShutdownReason.HttpRuntimeClose
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: HttpRuntimeClose
  nameWithType: ApplicationShutdownReason.HttpRuntimeClose
  fullName: System.Web.ApplicationShutdownReason.HttpRuntimeClose
- uid: System.Web.ApplicationShutdownReason.IdleTimeout
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: IdleTimeout
  nameWithType: ApplicationShutdownReason.IdleTimeout
  fullName: System.Web.ApplicationShutdownReason.IdleTimeout
- uid: System.Web.ApplicationShutdownReason.InitializationError
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: InitializationError
  nameWithType: ApplicationShutdownReason.InitializationError
  fullName: System.Web.ApplicationShutdownReason.InitializationError
- uid: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: MaxRecompilationsReached
  nameWithType: ApplicationShutdownReason.MaxRecompilationsReached
  fullName: System.Web.ApplicationShutdownReason.MaxRecompilationsReached
- uid: System.Web.ApplicationShutdownReason.None
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: None
  nameWithType: ApplicationShutdownReason.None
  fullName: System.Web.ApplicationShutdownReason.None
- uid: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: PhysicalApplicationPathChanged
  nameWithType: ApplicationShutdownReason.PhysicalApplicationPathChanged
  fullName: System.Web.ApplicationShutdownReason.PhysicalApplicationPathChanged
- uid: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: ResourcesDirChangeOrDirectoryRename
  nameWithType: ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
  fullName: System.Web.ApplicationShutdownReason.ResourcesDirChangeOrDirectoryRename
- uid: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
  parent: System.Web.ApplicationShutdownReason
  isExternal: false
  name: UnloadAppDomainCalled
  nameWithType: ApplicationShutdownReason.UnloadAppDomainCalled
  fullName: System.Web.ApplicationShutdownReason.UnloadAppDomainCalled
