### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  id: DispatcherSynchronizationElement
  children:
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.#ctor
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives
  - System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties
  langs:
  - csharp
  name: DispatcherSynchronizationElement
  nameWithType: DispatcherSynchronizationElement
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  type: Class
  summary: "将调度程序同步行为添加到调度程序配置元素，以便 WCF 服务程序可以异步发送到客户端应用程序的消息答复。"
  syntax:
    content: 'public sealed class DispatcherSynchronizationElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: DispatcherSynchronizationElement()
  nameWithType: DispatcherSynchronizationElement.DispatcherSynchronizationElement()
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.DispatcherSynchronizationElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "创建的新实例<xref href=&quot;System.ServiceModel.Configuration.DispatcherSynchronizationElement&quot;></xref>类。"
  syntax:
    content: public DispatcherSynchronizationElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled
  id: AsynchronousSendEnabled
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: AsynchronousSendEnabled
  nameWithType: DispatcherSynchronizationElement.AsynchronousSendEnabled
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置是否启用异步消息发送。"
  syntax:
    content: public bool AsynchronousSendEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果启用了异步发送;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: DispatcherSynchronizationElement.BehaviorType
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取的类型<xref href=&quot;System.ServiceModel.Configuration.DispatcherSynchronizationElement&quot;></xref>行为扩展。"
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "一个类型对象。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: DispatcherSynchronizationElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "将复制一个定义调度程序行为扩展从指定的配置的子元素<xref href=&quot;System.ServiceModel.Configuration.ServiceModelExtensionElement&quot;></xref>到当前<xref href=&quot;System.ServiceModel.Configuration.DispatcherSynchronizationElement&quot;> </xref>。"
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "A <xref href=&quot;System.ServiceModel.Configuration.ServiceModelExtensionElement&quot;> </xref>提供同步子元素的对象。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: DispatcherSynchronizationElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "要添加。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives
  id: MaxPendingReceives
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: MaxPendingReceives
  nameWithType: DispatcherSynchronizationElement.MaxPendingReceives
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "获取或设置可由调度程序缓存的已接收消息的最大数目。"
  syntax:
    content: public int MaxPendingReceives { get; set; }
    return:
      type: System.Int32
      description: "表示消息数量的一个数字。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  langs:
  - csharp
  name: Properties
  nameWithType: DispatcherSynchronizationElement.Properties
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.#ctor
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: DispatcherSynchronizationElement()
  nameWithType: DispatcherSynchronizationElement.DispatcherSynchronizationElement()
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.DispatcherSynchronizationElement()
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: AsynchronousSendEnabled
  nameWithType: DispatcherSynchronizationElement.AsynchronousSendEnabled
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: BehaviorType
  nameWithType: DispatcherSynchronizationElement.BehaviorType
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: DispatcherSynchronizationElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: DispatcherSynchronizationElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: MaxPendingReceives
  nameWithType: DispatcherSynchronizationElement.MaxPendingReceives
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: Properties
  nameWithType: DispatcherSynchronizationElement.Properties
  fullName: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.#ctor*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: DispatcherSynchronizationElement
  nameWithType: DispatcherSynchronizationElement.DispatcherSynchronizationElement
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.AsynchronousSendEnabled*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: AsynchronousSendEnabled
  nameWithType: DispatcherSynchronizationElement.AsynchronousSendEnabled
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.BehaviorType*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: BehaviorType
  nameWithType: DispatcherSynchronizationElement.BehaviorType
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CopyFrom*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: CopyFrom
  nameWithType: DispatcherSynchronizationElement.CopyFrom
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: CreateBehavior
  nameWithType: DispatcherSynchronizationElement.CreateBehavior
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.MaxPendingReceives*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: MaxPendingReceives
  nameWithType: DispatcherSynchronizationElement.MaxPendingReceives
- uid: System.ServiceModel.Configuration.DispatcherSynchronizationElement.Properties*
  parent: System.ServiceModel.Configuration.DispatcherSynchronizationElement
  isExternal: false
  name: Properties
  nameWithType: DispatcherSynchronizationElement.Properties
