### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  id: CheckForUpdateCompletedEventArgs
  children:
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  - System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  langs:
  - csharp
  name: CheckForUpdateCompletedEventArgs
  nameWithType: CheckForUpdateCompletedEventArgs
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  type: Class
  summary: "表示通过调用<xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync*>获取详细的更新信息"
  remarks: "与 CheckForUpdateCompletedEventArgs，你可以决定是否升级 ClickOnce 应用程序基于最新版本的相关信息。 <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A>将返回一个布尔值，该值指示是否有新的更新根本。</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A>属性提供的新版本的版本号时<xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A>提供用户应已安装在计算机的最低版本。</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion%2A> <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A>表示是否需要用户的最新的可用更新。</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> 最后，<xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>表示更新的总大小。</xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes%2A>"
  example:
  - "The following code example uses <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/t-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: 'public class CheckForUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "获取已卸载的最新版本的版本号。"
  remarks: "AvailableVersion 可用于决定是否要安装此更新根据更新的严重性。 例如，如果唯一<xref:System.Version.Build%2A>或<xref:System.Version.Revision%2A>版本属性已更改，你的应用程序可能不需要更新之前<xref:System.Version.Minor%2A>或<xref:System.Version.Major%2A>属性更改。</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "<xref:System.Version>表达主要，次要版本号和修订号的最新版本。</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "获取一个值，该值指示是否必须安装此更新。"
  remarks: "当你将更新部署到 ClickOnce 应用程序时，，您可以将其标记为必需的更新，信号传输到你的应用程序，它应立即升级。 你想标记更新，如果最新版本包含的关键更新，或如果它与文件格式或使用的以前版本的后端数据源不兼容。"
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/2aa4f4df-e487-4c83-87b0-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果更新是必需的;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "获取用户必须在计算机已安装的最低版本。"
  remarks: "当用户在特殊分配上采用或周或月为不在计算机旁，应用程序可以丢失所需的更新。 使用 MinimumRequiredVersion 来确定用户是否具有不升级应用程序在一段时间，并已丢失一个或多个所需的更新。"
  example:
  - "The following code example calls <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateAsync%2A>, and forces an application update if MinimumRequiredVersion is greater than <xref:System.Deployment.Application.ApplicationDeployment.CurrentVersion%2A>.  \n  \n [!code-cs[ClickOnceAPI#10](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#10)]\n [!code-vb[ClickOnceAPI#10](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#10)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "A<xref:System.Version>对象，表示所有用户必须都安装的最早版本。</xref:System.Version>"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "获取是否有可用的已卸载的更新。"
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether or not there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#1](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#1)]\n [!code-cpp[ClickOnceAPI#1](~/add/codesnippet/cpp/847038a4-fd95-4e16-a133-_1.cpp)]\n [!code-vb[ClickOnceAPI#1](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#1)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果应用程序的新版本可用;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "获取可用的更新的大小。"
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "<xref:System.Int64>描述的大小，以字节为单位的可用的更新。</xref:System.Int64> 如果没有更新可用，则返回 0。"
  overload: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.AvailableVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: AvailableVersion
  nameWithType: CheckForUpdateCompletedEventArgs.AvailableVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.IsUpdateRequired*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: IsUpdateRequired
  nameWithType: CheckForUpdateCompletedEventArgs.IsUpdateRequired
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.MinimumRequiredVersion*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: CheckForUpdateCompletedEventArgs.MinimumRequiredVersion
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateAvailable*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateAvailable
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateAvailable
- uid: System.Deployment.Application.CheckForUpdateCompletedEventArgs.UpdateSizeBytes*
  parent: System.Deployment.Application.CheckForUpdateCompletedEventArgs
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: CheckForUpdateCompletedEventArgs.UpdateSizeBytes
