### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthorizationSection
  id: AuthorizationSection
  children:
  - System.Web.Configuration.AuthorizationSection.#ctor
  - System.Web.Configuration.AuthorizationSection.PostDeserialize
  - System.Web.Configuration.AuthorizationSection.Properties
  - System.Web.Configuration.AuthorizationSection.Rules
  langs:
  - csharp
  name: AuthorizationSection
  nameWithType: AuthorizationSection
  fullName: System.Web.Configuration.AuthorizationSection
  type: Class
  summary: "配置 Web 应用程序授权。 此类不能被继承。"
  remarks: "AuthorizationSection 类使您能够以编程方式访问和修改`authorization`配置文件节。       此类型是包括的组的一部分<xref:System.Web.Configuration.AuthorizationRule>、 <xref:System.Web.Configuration.AuthorizationRuleCollection>，和<xref:System.Web.Configuration.AuthorizationRuleAction>类型。</xref:System.Web.Configuration.AuthorizationRuleAction> </xref:System.Web.Configuration.AuthorizationRuleCollection> </xref:System.Web.Configuration.AuthorizationRule>      1> [!NOTE]&1;> AuthorizationSection 可以读取和写入信息 from 和 to 部分属性，<xref:System.Configuration.SectionInformation.AllowDefinition%2A>其值为<xref:System.Configuration.ConfigurationAllowDefinition>。</xref:System.Configuration.ConfigurationAllowDefinition></xref:System.Configuration.SectionInformation.AllowDefinition%2A>根据配置文件的相关部分"
  example:
  - "The following code example shows how to obtain the AuthorizationSection object from the configuration file of an existing Web application. You can use this object to access its members. The configuration file will contain a setup similar to the following.  \n  \n> [!NOTE]\n>  If you use the `credentials` section, be sure to follow the guidelines explained at [ASP.NET Authentication](~/add/includes/ajax-current-ext-md.md). For scalability and better security capability, it is recommended that you use an external database to store the users' credentials. For more information about building secure ASP.NET applications, search the Microsoft MSDN Web site (msdn.microsoft.com) for \"Securing Your ASP.NET Application\" and \"Building Secure ASP.NET Applications: Authentication, Authorization, and Secure Communication.\"  \n  \n```  \n<authorization>  \n  <allow users=\"userName\" roles=\"admin\" verbs=\"post\" />  \n  <deny users=\"*\" verbs=\"post\"/>  \n</authorization>  \n```  \n  \n [!code-cs[System.Web.Configuration.Authorization#1](~/add/codesnippet/csharp/t-system.web.configurati_65_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#1](~/add/codesnippet/visualbasic/t-system.web.configurati_65_1.vb)]  \n  \n [!code-cs[System.Web.Configuration.Authorization#2](~/add/codesnippet/csharp/t-system.web.configurati_65_2.cs)]\n [!code-vb[System.Web.Configuration.Authorization#2](~/add/codesnippet/visualbasic/t-system.web.configurati_65_2.vb)]"
  syntax:
    content: 'public sealed class AuthorizationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: System.Web.Configuration.AuthorizationSection.AuthorizationSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "初始化的新实例<xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;></xref>类使用默认设置。"
  remarks: "AuthorizationSection 构造函数不应在代码中直接使用。 它是由 ASP.NET 配置系统调用的。 获取实例<xref:System.Web.Configuration.AuthorizationSection>类通过<xref:System.Configuration.Configuration.GetSection%2A>方法。</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.AuthorizationSection>"
  syntax:
    content: public AuthorizationSection ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  id: PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: System.Web.Configuration.AuthorizationSection.PostDeserialize()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override void PostDeserialize ();
    parameters: []
  overload: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.Properties
  id: Properties
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: System.Web.Configuration.AuthorizationSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "要添加。"
  overload: System.Web.Configuration.AuthorizationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationSection.Rules
  id: Rules
  parent: System.Web.Configuration.AuthorizationSection
  langs:
  - csharp
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: System.Web.Configuration.AuthorizationSection.Rules
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Gets the <xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;></xref> of <xref href=&quot;System.Web.Configuration.AuthorizationRule&quot;></xref> rules."
  remarks: "此方法返回的规则集合不是基础的配置文件中任何实际元素指。 它是一个构造，它包含的规则的方便访问。 这是一种常见模式，用于处理配置文件的元素。"
  example:
  - "The following code example shows how to use the Rules.  \n  \n [!code-cs[System.Web.Configuration.Authorization#6](~/add/codesnippet/csharp/p-system.web.configurati_248_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#6](~/add/codesnippet/visualbasic/p-system.web.configurati_248_1.vb)]"
  syntax:
    content: public System.Web.Configuration.AuthorizationRuleCollection Rules { get; }
    return:
      type: System.Web.Configuration.AuthorizationRuleCollection
      description: "获取<xref href=&quot;System.Web.Configuration.AuthorizationRuleCollection&quot;></xref>的<xref href=&quot;System.Web.Configuration.AuthorizationRule&quot;></xref>定义的规则<xref href=&quot;System.Web.Configuration.AuthorizationSection&quot;> </xref>。"
  overload: System.Web.Configuration.AuthorizationSection.Rules*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.AuthorizationSection.#ctor
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection()
  nameWithType: AuthorizationSection.AuthorizationSection()
  fullName: System.Web.Configuration.AuthorizationSection.AuthorizationSection()
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize()
  nameWithType: AuthorizationSection.PostDeserialize()
  fullName: System.Web.Configuration.AuthorizationSection.PostDeserialize()
- uid: System.Web.Configuration.AuthorizationSection.Properties
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
  fullName: System.Web.Configuration.AuthorizationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.AuthorizationSection.Rules
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
  fullName: System.Web.Configuration.AuthorizationSection.Rules
- uid: System.Web.Configuration.AuthorizationRuleCollection
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleCollection
  nameWithType: AuthorizationRuleCollection
  fullName: System.Web.Configuration.AuthorizationRuleCollection
- uid: System.Web.Configuration.AuthorizationSection.#ctor*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: AuthorizationSection
  nameWithType: AuthorizationSection.AuthorizationSection
- uid: System.Web.Configuration.AuthorizationSection.PostDeserialize*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: PostDeserialize
  nameWithType: AuthorizationSection.PostDeserialize
- uid: System.Web.Configuration.AuthorizationSection.Properties*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Properties
  nameWithType: AuthorizationSection.Properties
- uid: System.Web.Configuration.AuthorizationSection.Rules*
  parent: System.Web.Configuration.AuthorizationSection
  isExternal: false
  name: Rules
  nameWithType: AuthorizationSection.Rules
