### YamlMime:ManagedReference
items:
- uid: System.Management.Instrumentation.ManagementConfigurationType
  id: ManagementConfigurationType
  children:
  - System.Management.Instrumentation.ManagementConfigurationType.Apply
  - System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  langs:
  - csharp
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
  type: Enum
  summary: "表示读/写属性的可能的提交行为。 使用的参数的值作为<xref href=&quot;System.Management.Instrumentation.ManagementConfigurationAttribute&quot;></xref>属性。       注意︰ WMI.NET 库都被视为在最终状态，不进一步开发、 增强功能，或更新将可供影响这些库的非安全相关问题。 [MI Api](https://msdn.microsoft.com/en-us/library/jj152383%28v=vs.80%29.aspx)应将用于所有新的开发。"
  remarks: "此属性使用作为参数值为<xref:System.Management.Instrumentation.ManagementConfigurationAttribute>属性仅当<xref:System.Management.Instrumentation.ManagementCommitAttribute>属性用于标识要运行以提交值的方法。</xref:System.Management.Instrumentation.ManagementCommitAttribute> </xref:System.Management.Instrumentation.ManagementConfigurationAttribute> 否则，将自动应用读/写属性值。"
  syntax:
    content: public enum ManagementConfigurationType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  id: Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "仅当调用提交时，设置值将会生效。"
  syntax:
    content: Apply
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  id: OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  langs:
  - csharp
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  type: Field
  assemblies:
  - System.Core
  namespace: System.Management.Instrumentation
  summary: "设置值会立即应用。"
  syntax:
    content: OnCommit
    return:
      type: System.Management.Instrumentation.ManagementConfigurationType
      description: "要添加。"
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Management.Instrumentation.ManagementConfigurationType.Apply
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: Apply
  nameWithType: ManagementConfigurationType.Apply
  fullName: System.Management.Instrumentation.ManagementConfigurationType.Apply
- uid: System.Management.Instrumentation.ManagementConfigurationType
  parent: System.Management.Instrumentation
  isExternal: false
  name: ManagementConfigurationType
  nameWithType: ManagementConfigurationType
  fullName: System.Management.Instrumentation.ManagementConfigurationType
- uid: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
  parent: System.Management.Instrumentation.ManagementConfigurationType
  isExternal: false
  name: OnCommit
  nameWithType: ManagementConfigurationType.OnCommit
  fullName: System.Management.Instrumentation.ManagementConfigurationType.OnCommit
