### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerTransportSecuritySettings
  id: PeerTransportSecuritySettings
  children:
  - System.ServiceModel.PeerTransportSecuritySettings.#ctor
  - System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  langs:
  - csharp
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings
  fullName: System.ServiceModel.PeerTransportSecuritySettings
  type: Class
  summary: "包含对等通道传输的安全设置。"
  syntax:
    content: public sealed class PeerTransportSecuritySettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerTransportSecuritySettings
  langs:
  - csharp
  name: PeerTransportSecuritySettings()
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  fullName: System.ServiceModel.PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "创建的实例<xref href=&quot;System.ServiceModel.PeerTransportSecuritySettings&quot;></xref>类型。"
  syntax:
    content: public PeerTransportSecuritySettings ();
    parameters: []
  overload: System.ServiceModel.PeerTransportSecuritySettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  id: CredentialType
  parent: System.ServiceModel.PeerTransportSecuritySettings
  langs:
  - csharp
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
  fullName: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "获取和设置的一种凭据用于进行身份验证对等通道传输。"
  syntax:
    content: public System.ServiceModel.PeerTransportCredentialType CredentialType { get; set; }
    return:
      type: System.ServiceModel.PeerTransportCredentialType
      description: "A <xref href=&quot;System.ServiceModel.PeerTransportCredentialType&quot;> </xref>枚举值，指定要为身份验证提供的凭据类型。"
  overload: System.ServiceModel.PeerTransportSecuritySettings.CredentialType*
  exceptions:
  - type: System.ComponentModel.InvalidEnumArgumentException
    commentId: T:System.ComponentModel.InvalidEnumArgumentException
    description: "凭据类型不是有效<xref href=&quot;System.ServiceModel.PeerTransportCredentialType&quot;></xref>枚举值。"
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ComponentModel.InvalidEnumArgumentException
  parent: System.ComponentModel
  isExternal: false
  name: InvalidEnumArgumentException
  nameWithType: InvalidEnumArgumentException
  fullName: System.ComponentModel.InvalidEnumArgumentException
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: PeerTransportSecuritySettings()
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings()
  fullName: System.ServiceModel.PeerTransportSecuritySettings.PeerTransportSecuritySettings()
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
  fullName: System.ServiceModel.PeerTransportSecuritySettings.CredentialType
- uid: System.ServiceModel.PeerTransportCredentialType
  parent: System.ServiceModel
  isExternal: false
  name: PeerTransportCredentialType
  nameWithType: PeerTransportCredentialType
  fullName: System.ServiceModel.PeerTransportCredentialType
- uid: System.ServiceModel.PeerTransportSecuritySettings.#ctor*
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: PeerTransportSecuritySettings
  nameWithType: PeerTransportSecuritySettings.PeerTransportSecuritySettings
- uid: System.ServiceModel.PeerTransportSecuritySettings.CredentialType*
  parent: System.ServiceModel.PeerTransportSecuritySettings
  isExternal: false
  name: CredentialType
  nameWithType: PeerTransportSecuritySettings.CredentialType
