### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.IApplicationPreloadManager
  id: IApplicationPreloadManager
  children:
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  - System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  langs:
  - csharp
  name: IApplicationPreloadManager
  nameWithType: IApplicationPreloadManager
  fullName: System.Web.Hosting.IApplicationPreloadManager
  type: Interface
  summary: "提供 ASP.NET 使用来调用中的应用程序预加载功能的方法[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.Guid("AE54F424-71BC-4da5-AA2F-8C0CD53496FC")]

      [System.Runtime.InteropServices.InterfaceType(System.Runtime.InteropServices.ComInterfaceType.InterfaceIsIUnknown)]

      public interface IApplicationPreloadManager
  implements: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  id: SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "由调用[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]通知 ASP.NET 是否应预加载应用程序。"
  syntax:
    content: public void SetApplicationPreloadState (string context, string appId, bool enabled);
    parameters:
    - id: context
      type: System.String
      description: "应用程序上下文中。"
    - id: appId
      type: System.String
      description: "应用程序的唯一 ID。"
    - id: enabled
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要指示，应用程序应预加载;否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  id: SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  langs:
  - csharp
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "调用[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]获取预加载应用程序所需的信息。"
  remarks: "IIS 会调用 ASP.NET 通过此接口，提供对实现的对象的引用<xref:System.Web.Hosting.IApplicationPreloadUtil>接口。</xref:System.Web.Hosting.IApplicationPreloadUtil> ASP.NET 使用该接口更高版本执行回调到 IIS 以获取为单个应用程序的预加载信息。"
  syntax:
    content: public void SetApplicationPreloadUtil (System.Web.Hosting.IApplicationPreloadUtil preloadUtil);
    parameters:
    - id: preloadUtil
      type: System.Web.Hosting.IApplicationPreloadUtil
      description: "中的非托管接口的句柄[!INCLUDE[iisver](~/add/includes/ajax-current-ext-md.md)]该 ASP.NET 调用以获取信息。"
  overload: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(System.String,System.String,System.Boolean)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState(String,String,Boolean)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState(String,String,Boolean)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(System.Web.Hosting.IApplicationPreloadUtil)
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil(IApplicationPreloadUtil)
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
  fullName: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil(IApplicationPreloadUtil)
- uid: System.Web.Hosting.IApplicationPreloadUtil
  parent: System.Web.Hosting
  isExternal: false
  name: IApplicationPreloadUtil
  nameWithType: IApplicationPreloadUtil
  fullName: System.Web.Hosting.IApplicationPreloadUtil
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadState*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadState
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadState
- uid: System.Web.Hosting.IApplicationPreloadManager.SetApplicationPreloadUtil*
  parent: System.Web.Hosting.IApplicationPreloadManager
  isExternal: false
  name: SetApplicationPreloadUtil
  nameWithType: IApplicationPreloadManager.SetApplicationPreloadUtil
