### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  id: UpdateManifestForBrowserApplication
  children:
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  - Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  type: Class
  summary: "实现`UpdateManifestForBrowserApplication`任务。 使用`UpdateManifestForBrowserApplication`项目文件以创建和执行此任务中的元素。 有关用法和参数信息，请参阅[UpdateManifestForBrowserApplication](~/add/includes/ajax-current-ext-md.md)。"
  syntax:
    content: 'public sealed class UpdateManifestForBrowserApplication : Microsoft.Build.Utilities.Task'
  inheritance:
  - System.Object
  - Microsoft.Build.Utilities.Task
  implements: []
  inheritedMembers:
  - Microsoft.Build.Utilities.Task.BuildEngine
  - Microsoft.Build.Utilities.Task.BuildEngine2
  - Microsoft.Build.Utilities.Task.BuildEngine3
  - Microsoft.Build.Utilities.Task.BuildEngine4
  - Microsoft.Build.Utilities.Task.HelpKeywordPrefix
  - Microsoft.Build.Utilities.Task.HostObject
  - Microsoft.Build.Utilities.Task.Log
  - Microsoft.Build.Utilities.Task.TaskResources
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  type: Constructor
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "初始化的新实例<xref href=&quot;Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication&quot;></xref>类。"
  syntax:
    content: public UpdateManifestForBrowserApplication ();
    parameters: []
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  id: ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "获取或设置路径和你想要添加应用程序清单文件的名称`<hostInBrowser></hostInBrowser>`到的元素。"
  syntax:
    content: public Microsoft.Build.Framework.ITaskItem[] ApplicationManifest { get; set; }
    return:
      type: Microsoft.Build.Framework.ITaskItem[]
      description: "路径和名称的应用程序清单文件，你想要添加`<hostInBrowser></hostInBrowser>`到的元素。"
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  id: Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
  type: Method
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "执行任务。"
  syntax:
    content: public override bool Execute ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>如果成功，则执行任务否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  id: HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  langs:
  - csharp
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  type: Property
  assemblies:
  - PresentationBuildTasks
  namespace: Microsoft.Build.Tasks.Windows
  summary: "获取一个值，该值指示是否修改应用程序清单，以包括** &lt;hostInBrowser /&gt; **元素。"
  syntax:
    content: public bool HostInBrowser { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>若要修改应用程序清单，以包括** &lt;hostInBrowser /&gt; **元素; 否则为<xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>。"
  overload: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  exceptions: []
  platform:
  - net462
references:
- uid: Microsoft.Build.Utilities.Task
  isExternal: false
  name: Microsoft.Build.Utilities.Task
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication()
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication()
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest
- uid: Microsoft.Build.Framework.ITaskItem[]
  parent: Microsoft.Build.Framework
  isExternal: false
  name: ITaskItem
  nameWithType: ITaskItem
  fullName: Microsoft.Build.Framework.ITaskItem[]
  spec.csharp:
  - uid: Microsoft.Build.Framework.ITaskItem
    name: ITaskItem
    nameWithType: ITaskItem
    fullName: ITaskItem[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute()
  nameWithType: UpdateManifestForBrowserApplication.Execute()
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
  fullName: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.#ctor*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: UpdateManifestForBrowserApplication
  nameWithType: UpdateManifestForBrowserApplication.UpdateManifestForBrowserApplication
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.ApplicationManifest*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: ApplicationManifest
  nameWithType: UpdateManifestForBrowserApplication.ApplicationManifest
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.Execute*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: Execute
  nameWithType: UpdateManifestForBrowserApplication.Execute
- uid: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication.HostInBrowser*
  parent: Microsoft.Build.Tasks.Windows.UpdateManifestForBrowserApplication
  isExternal: false
  name: HostInBrowser
  nameWithType: UpdateManifestForBrowserApplication.HostInBrowser
