### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  id: SecurityUtilities
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet(System.String,System.Security.PermissionSet,System.String[])
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet(System.String[])
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList(System.Security.PermissionSet)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Uri,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Uri,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Security.SecureString,System.Uri,System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet(System.Xml.XmlElement)
  langs:
  - csharp
  name: SecurityUtilities
  nameWithType: SecurityUtilities
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  type: Class
  summary: "用于操作安全权限集和签名，提供了一套实用工具函数。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public static class SecurityUtilities
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet(System.String,System.Security.PermissionSet,System.String[])
  id: ComputeZonePermissionSet(System.String,System.Security.PermissionSet,System.String[])
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: ComputeZonePermissionSet(String,PermissionSet,String[])
  nameWithType: SecurityUtilities.ComputeZonePermissionSet(String,PermissionSet,String[])
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet(String,PermissionSet,String[])
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "生成的权限通过计算区域默认权限集中、 删除任何已排除的权限，以及添加任何包括的权限集。"
  syntax:
    content: public static System.Security.PermissionSet ComputeZonePermissionSet (string targetZone, System.Security.PermissionSet includedPermissionSet, string[] excludedPermissions);
    parameters:
    - id: targetZone
      type: System.String
      description: "指定区域默认权限集中，可从计算机策略中获得。 Valid values are <xref uid=&quot;langword_csharp_Internet&quot; name=&quot;Internet&quot; href=&quot;&quot;></xref>, <xref uid=&quot;langword_csharp_LocalIntranet&quot; name=&quot;LocalIntranet&quot; href=&quot;&quot;></xref>, or <xref uid=&quot;langword_csharp_Custom&quot; name=&quot;Custom&quot; href=&quot;&quot;></xref>. 如果<xref uid=&quot;langword_csharp_Custom&quot; name=&quot;Custom&quot; href=&quot;&quot;></xref>指定，则生成的权限集仅基于`includedPermissionSet`参数。"
    - id: includedPermissionSet
      type: System.Security.PermissionSet
      description: "A<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.TrustInfo.PermissionSet*>对象，其中包含组的权限来显式包含在生成的权限集。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.TrustInfo.PermissionSet*> 此参数中指定的权限将逐字包含在生成的权限集，而不考虑`targetZone`或`excludedPermissions`参数。"
    - id: excludedPermissions
      type: System.String[]
      description: "设置要从区域默认权限排除的权限标识字符串数组。 可以使用计算权限标识字符串<xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList*>方法。</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList*> 如果忽略此参数`targetZone`不<xref uid=&quot;langword_csharp_Internet&quot; name=&quot;Internet&quot; href=&quot;&quot;></xref>或<xref uid=&quot;langword_csharp_LocalIntranet&quot; name=&quot;LocalIntranet&quot; href=&quot;&quot;> </xref>。"
    return:
      type: System.Security.PermissionSet
      description: "返回生成的权限集。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet(System.String[])
  id: IdentityListToPermissionSet(System.String[])
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: IdentityListToPermissionSet(String[])
  nameWithType: SecurityUtilities.IdentityListToPermissionSet(String[])
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet(String[])
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "将为权限的权限标识字符串数组集对象。"
  syntax:
    content: public static System.Security.PermissionSet IdentityListToPermissionSet (string[] ids);
    parameters:
    - id: ids
      type: System.String[]
      description: "权限标识字符串数组。"
    return:
      type: System.Security.PermissionSet
      description: "返回转换后的权限集。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList(System.Security.PermissionSet)
  id: PermissionSetToIdentityList(System.Security.PermissionSet)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: PermissionSetToIdentityList(PermissionSet)
  nameWithType: SecurityUtilities.PermissionSetToIdentityList(PermissionSet)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList(PermissionSet)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "将权限集对象到数组的权限标识字符串。"
  syntax:
    content: public static string[] PermissionSetToIdentityList (System.Security.PermissionSet permissionSet);
    parameters:
    - id: permissionSet
      type: System.Security.PermissionSet
      description: "设置要转换的输入的权限。"
    return:
      type: System.String[]
      description: "返回数组的权限标识字符串。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Uri,System.String)
  id: SignFile(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: SignFile(X509Certificate2,Uri,String)
  nameWithType: SecurityUtilities.SignFile(X509Certificate2,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(X509Certificate2,Uri,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "对 ClickOnce 清单或 PE 文件进行签名。"
  remarks: "如果 X509Certificate2 参数表示当前用户的个人证书存储中的证书，则此函数可以仅对签名的 PE 文件。       此重载的方法调用 SignTool.exe，因此需要[!INCLUDE[dnprdnlong](~/add/includes/dnprdnlong-md.md)]安装。"
  syntax:
    content: public static void SignFile (System.Security.Cryptography.X509Certificates.X509Certificate2 cert, Uri timestampUrl, string path);
    parameters:
    - id: cert
      type: System.Security.Cryptography.X509Certificates.X509Certificate2
      description: "要用于对文件进行签名的证书。"
    - id: timestampUrl
      type: System.Uri
      description: "指示该文件将由位于指定 HTTP 地址的时间戳服务器加盖时间戳。 如果您不希望时间戳，则此参数可以为 NULL。"
    - id: path
      type: System.String
      description: "要签名的文件的名称。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Uri,System.String)
  id: SignFile(System.String,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: SignFile(String,Uri,String)
  nameWithType: SecurityUtilities.SignFile(String,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(String,Uri,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "对 ClickOnce 清单或 PE 文件进行签名。"
  remarks: "此重载的方法调用 SignTool.exe，因此需要[!INCLUDE[dnprdnlong](~/add/includes/dnprdnlong-md.md)]安装。"
  syntax:
    content: public static void SignFile (string certThumbprint, Uri timestampUrl, string path);
    parameters:
    - id: certThumbprint
      type: System.String
      description: "指定的指纹，这是保留在你的个人证书存储的签名证书的 SHA1 哈希。"
    - id: timestampUrl
      type: System.Uri
      description: "指示该文件将由位于指定 HTTP 地址的时间戳服务器加盖时间戳。 如果您不希望时间戳，则此参数可以为 NULL。"
    - id: path
      type: System.String
      description: "要签名的文件的名称。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Security.SecureString,System.Uri,System.String)
  id: SignFile(System.String,System.Security.SecureString,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: SignFile(String,SecureString,Uri,String)
  nameWithType: SecurityUtilities.SignFile(String,SecureString,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(String,SecureString,Uri,String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "对 ClickOnce 清单进行签名。"
  remarks: "此函数是仅对清单进行签名，不是 PE 文件。"
  syntax:
    content: public static void SignFile (string certPath, System.Security.SecureString certPassword, Uri timestampUrl, string path);
    parameters:
    - id: certPath
      type: System.String
      description: "要用于对文件进行签名的证书。 证书必须包含私钥。 <xref uid=&quot;langword_csharp_KeyUsage&quot; name=&quot;KeyUsage&quot; href=&quot;&quot;> </xref>扩展名是可选的但如果它存在， <xref uid=&quot;langword_csharp_DigitalSignature&quot; name=&quot;DigitalSignature&quot; href=&quot;&quot;> </xref>必须设置为<xref uid=&quot;langword_csharp_True&quot; name=&quot;True&quot; href=&quot;&quot;> </xref>。 <xref uid=&quot;langword_csharp_EnhancedKeyUsage&quot; name=&quot;EnhancedKeyUsage&quot; href=&quot;&quot;> </xref>扩展名也是可选的但如果存在，则证书必须包含对象标识符 (OID) 支持。"
    - id: certPassword
      type: System.Security.SecureString
      description: "证书密码。"
    - id: timestampUrl
      type: System.Uri
      description: "指示该文件将由位于指定 HTTP 地址的时间戳服务器加盖时间戳。 如果您不希望时间戳，则此参数可以为 NULL。"
    - id: path
      type: System.String
      description: "要签名的文件的名称。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet(System.Xml.XmlElement)
  id: XmlToPermissionSet(System.Xml.XmlElement)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  langs:
  - csharp
  name: XmlToPermissionSet(XmlElement)
  nameWithType: SecurityUtilities.XmlToPermissionSet(XmlElement)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet(XmlElement)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "将 XML 元素为权限集对象。"
  remarks: "将转换<xref:System.Xml.XmlElement>对象传递给<xref:System.Security.PermissionSet>对象。</xref:System.Security.PermissionSet> </xref:System.Xml.XmlElement>"
  syntax:
    content: public static System.Security.PermissionSet XmlToPermissionSet (System.Xml.XmlElement element);
    parameters:
    - id: element
      type: System.Xml.XmlElement
      description: "权限集的 XML 表示形式。"
    return:
      type: System.Security.PermissionSet
      description: "转换后的权限集的对象。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet(System.String,System.Security.PermissionSet,System.String[])
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: ComputeZonePermissionSet(String,PermissionSet,String[])
  nameWithType: SecurityUtilities.ComputeZonePermissionSet(String,PermissionSet,String[])
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet(String,PermissionSet,String[])
- uid: System.Security.PermissionSet
  parent: System.Security
  isExternal: false
  name: PermissionSet
  nameWithType: PermissionSet
  fullName: System.Security.PermissionSet
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet(System.String[])
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: IdentityListToPermissionSet(String[])
  nameWithType: SecurityUtilities.IdentityListToPermissionSet(String[])
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet(String[])
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList(System.Security.PermissionSet)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: PermissionSetToIdentityList(PermissionSet)
  nameWithType: SecurityUtilities.PermissionSetToIdentityList(PermissionSet)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList(PermissionSet)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.Security.Cryptography.X509Certificates.X509Certificate2,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: SignFile(X509Certificate2,Uri,String)
  nameWithType: SecurityUtilities.SignFile(X509Certificate2,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(X509Certificate2,Uri,String)
- uid: System.Security.Cryptography.X509Certificates.X509Certificate2
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509Certificate2
  nameWithType: X509Certificate2
  fullName: System.Security.Cryptography.X509Certificates.X509Certificate2
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: SignFile(String,Uri,String)
  nameWithType: SecurityUtilities.SignFile(String,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(String,Uri,String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(System.String,System.Security.SecureString,System.Uri,System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: SignFile(String,SecureString,Uri,String)
  nameWithType: SecurityUtilities.SignFile(String,SecureString,Uri,String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile(String,SecureString,Uri,String)
- uid: System.Security.SecureString
  parent: System.Security
  isExternal: false
  name: SecureString
  nameWithType: SecureString
  fullName: System.Security.SecureString
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet(System.Xml.XmlElement)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: XmlToPermissionSet(XmlElement)
  nameWithType: SecurityUtilities.XmlToPermissionSet(XmlElement)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet(XmlElement)
- uid: System.Xml.XmlElement
  parent: System.Xml
  isExternal: false
  name: XmlElement
  nameWithType: XmlElement
  fullName: System.Xml.XmlElement
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.ComputeZonePermissionSet*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: ComputeZonePermissionSet
  nameWithType: SecurityUtilities.ComputeZonePermissionSet
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.IdentityListToPermissionSet*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: IdentityListToPermissionSet
  nameWithType: SecurityUtilities.IdentityListToPermissionSet
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.PermissionSetToIdentityList*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: PermissionSetToIdentityList
  nameWithType: SecurityUtilities.PermissionSetToIdentityList
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.SignFile*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: SignFile
  nameWithType: SecurityUtilities.SignFile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities.XmlToPermissionSet*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.SecurityUtilities
  isExternal: false
  name: XmlToPermissionSet
  nameWithType: SecurityUtilities.XmlToPermissionSet
