### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  id: OutputMessageCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  langs:
  - csharp
  name: OutputMessageCollection
  nameWithType: OutputMessageCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  type: Class
  summary: "此类表示输出消息的集合。"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class OutputMessageCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: OutputMessageCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "从集合中移除所有对象。"
  syntax:
    content: public void Clear ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  id: ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "获取集合中的错误消息数。"
  syntax:
    content: public int ErrorCount { get; }
    return:
      type: System.Int32
      description: "集合中的错误消息数。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: OutputMessageCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "返回可循环访问集合的枚举。"
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "返回<xref:System.Collections.IEnumerator>可以循环访问集合的对象。</xref:System.Collections.IEnumerator>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: OutputMessageCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "获取指定索引处的元素。"
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "要获取的项的从零开始的索引。"
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
      description: "返回文件引用实例。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  id: WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  langs:
  - csharp
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "获取集合中的警告消息数。"
  syntax:
    content: public int WarningCount { get; }
    return:
      type: System.Int32
      description: "集合中的警告消息数。"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Clear()
  nameWithType: OutputMessageCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: OutputMessageCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: OutputMessageCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: OutputMessage
  nameWithType: OutputMessage
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessage
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Clear*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Clear
  nameWithType: OutputMessageCollection.Clear
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.ErrorCount*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: ErrorCount
  nameWithType: OutputMessageCollection.ErrorCount
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.GetEnumerator*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: OutputMessageCollection.GetEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.Item*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: Item
  nameWithType: OutputMessageCollection.Item
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection.WarningCount*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.OutputMessageCollection
  isExternal: false
  name: WarningCount
  nameWithType: OutputMessageCollection.WarningCount
